### ISSUE TITLE
Typo issues on Notification Controller command

### ISSUE THREAD

**Issue by Forbinn** [OpenZWave/open-zwave#1022]
Hello,

After using the [OpenZWave::Notification::GetAsString](https://github.com/OpenZWave/open-zwave/blob/master/cpp/src/Notification.cpp#L40) method I found two small typo issues on controller command.
- The first one is here: https://github.com/OpenZWave/open-zwave/blob/master/cpp/src/Notification.cpp#L152 . The string should be **ControllerCommand - Normal** instead of **ControlerCommand - Normal**
- The second one is here: https://github.com/OpenZWave/open-zwave/blob/master/cpp/src/Notification.cpp#L155 . The string should be **ControllerCommand - Starting** instead of **ControllerComand - Starting**

**Comment by Fishwaldo** [comment]
Thanks
