### ISSUE TITLE
Fibaro FGWPE Wall Plug is now type="0602" id="1001"

### ISSUE THREAD

**Issue by OstfrieseUnterwegs** [OpenZWave/open-zwave#1044]
Just receiverd a new Fibaro Wall Plug. Type and ID changed

manufacturer_specific.xml

`		<Product type="0602" id="1001" name="FGWPE Wall Plug" config="fibaro/fgwpe.xml" />`
needs to be added after

`		<Product type="0203" id="1000" name="FGS223 Double Relay" config="fibaro/fgs223.xml"/>`
`		<Product type="0600" id="1000" name="FGWPE Wall Plug" config="fibaro/fgwpe.xml" />`

**Comment by nechry** [comment]
@OstfrieseUnterwegs is the zwave+ revision? if yes be me a specific xml is required

**Comment by GravityRZ** [comment]
yes a specific config file is needed

i will see if i can push it
