### ISSUE TITLE
TZ45A Thermostat support

### ISSUE THREAD

**Issue by darrinsmart** [OpenZWave/open-zwave#1046]
Hi,

Moved into a building that had RCS TZ45A (not TZ45) thermostats installed. These do not currently report the heating setpoint. It appears to be a bug in the thermostat similar to the TZ45. Log attached.

[OZW_Log.txt](https://github.com/OpenZWave/open-zwave/files/601911/OZW_Log.txt)

Our TZ45A's report themselves as a TZ43, so the proposed change below might create a conflict. Unfortunately I do not have access to a TZ43 to check,

I was able to workaround it by using the database entry for TZ45:

```
--- a/config/manufacturer_specific.xml
+++ b/config/manufacturer_specific.xml
@@ -779,7 +779,7 @@
                <Product type="0202" id="8031" name="ZTS-110" config="remotec/zts-110.xml" />
        </Manufacturer>
        <Manufacturer id="0010" name="RCS">
-        <Product type="0001" id="0002" name="TZ43 Thermostat" />
+        <Product type="0001" id="0002" name="TZ43 Thermostat" config="rcs/therm0009.xml" />
         <Product type="0001" id="0005" name="TZ43-IHD SMUD Thermostat" config="rcs/therm0005.xml" />
         <Product type="0001" id="0007" name="TZ45-IHD SMUD Thermostat" config="rcs/therm0007.xml" />
         <Product type="0001" id="0009" name="TZ45 Thermostat" config="rcs/therm0009.xml" />
```

Also the TZ45A manual explains its home/away switch is set using BASIC_SET:

Setback Mode Operation
If your controller does not support full thermostat device class functions, it may still be able to control the energy saving AWAY mode of the thermostat through BASIC_SET commands.
Sending the BASIC_SET (Value = 0x00), the thermostat will go into the AWAY mode and use the predefined AWAY setback setpoints. These setpoints are set in the Main Menu Away Setpoints item.
Sending the BASIC_SET (Value = 0xFF), the thermostat will revert back to the Home mode it was in before the BASIC_SET (Value = 0x00) command was sent.

**Comment by Fishwaldo** [comment]
Thanks
