### ISSUE TITLE
Please add the Popp 012501 Strike Lock Control device

### ISSUE THREAD

**Issue by catweazle0172** [OpenZWave/open-zwave#1047]
Hello,

Please add the Popp 012501 Strike Lock Control 
http://www.popp.eu/wp-content/uploads/2016/11/Manual_ElectricStrikeLockControl_POPP_en.pdf
This code is working for me:
Add the following line in the manufacturer_specific.xml under 	<Manufacturer id="0154" name="Popp">
Product type="0005" id="0001" name="012501 Strike Lock Control" config="popp/012501.xml" /

[012501.xml.zip](https://github.com/OpenZWave/open-zwave/files/604677/012501.xml.zip)
Thanks!

**Comment by nechry** [comment]
close with https://github.com/OpenZWave/open-zwave/commit/d0e42ec0c30f5066b6bac243d99f126d11638687
