### ISSUE TITLE
PH-PAB01.eu and compatibility

### ISSUE THREAD

**Issue by Sebol0187** [OpenZWave/open-zwave#1049]
Hello,
Sorry for my English.
I have a problem after installing Zipato PAB01. It is well recognized by Domoticz, but it doesn't return any value (cf OZC screen). Notably the cumulative energy.
I have the latest beta version of domoticz (3.5985), and openzwave (1.4-2247-g5046b13-dirty).
What do you think ?
Thank you !!
Olivier
![sans titre](https://cloud.githubusercontent.com/assets/23730066/20611433/6a1541d6-b2aa-11e6-9d5f-ae9132ef1066.png)

**Comment by nechry** [comment]
is suppose to do periodic report every 720sec (default value) check parameters

**Comment by Sebol0187** [comment]
But I have nothing in Domoticz :/
![capture](https://cloud.githubusercontent.com/assets/23730066/20633187/2cb07942-b344-11e6-95a9-eb7fba45b9d1.PNG)

**Comment by nechry** [comment]
Ensure associations groups are ok

**Comment by Sebol0187** [comment]
Group 1 : 1.1
Group 2 : 1.1
Group 3 : 1.1
Group 4 : -
Group 5 : -

**Comment by Sebol0187** [comment]
Up ? ;)

**Comment by Fishwaldo** [comment]
what about group 4 and 5? consult the manual and check what they are for.

**Comment by Sebol0187** [comment]
Just groups 1 to 3 :(
[Manuel_Zipato_PAB01.pdf](https://github.com/OpenZWave/open-zwave/files/662329/Manuel_Zipato_PAB01.pdf)

**Comment by nechry** [comment]
why you talk about 4 and 5?

**Comment by nechry** [comment]
I try my PAB01 and I got energy report. 
<img width="1461" alt="screen shot 2016-12-20 at 20 51 18" src="https://cloud.githubusercontent.com/assets/307966/21365578/2d067246-c6f6-11e6-98e3-74fa8a316c47.png">

the default reporting time is 720 sec.

**Comment by Sebol0187** [comment]
Hello,
I don't have energy report with Domoticz : 
![capture](https://cloud.githubusercontent.com/assets/23730066/21369846/2a84990e-c709-11e6-83e5-8fa97ed5adda.PNG)
![capture 1](https://cloud.githubusercontent.com/assets/23730066/21369848/2e81e1d8-c709-11e6-871f-2558ad466152.PNG)
![capture 2](https://cloud.githubusercontent.com/assets/23730066/21369851/305db748-c709-11e6-8d74-18e62ce94193.PNG)

**Comment by Fishwaldo** [comment]
Closing. Old issue

**Comment by Sebol0187** [comment]
Bonjour

Pourquoi clore une issue alors que le problème n'est toujours pas réglé à
ce jour et que nous sommes plusieurs dans le pétrin. Cela gêne ??

Cordialement,

Olivier THIRION


Le ven. 26 oct. 2018 à 11:46, Justin Hammond <notifications@github.com> a
écrit :
