### ISSUE TITLE
fail to install on /callbacks.o

### ISSUE THREAD

**Issue by sag911** [OpenZWave/open-zwave#1053]
Hi guys 

 I'm trying to install OpenZwave on a docker image (hypriot/rpi-node) and i get this error.

Can you give a look ? 

../src/callbacks.cc:436:48: error: no matching function for call to ‘New(const char [11])’
../src/callbacks.cc:436:48: note: candidates are:
/usr/local/lib/node_modules/node-red/node_modules/openzwave-shared/node_modules/nan/nan_implementation_12_inl.h:395:21: note: template<class T, class M> v8::Local<T> Nan::New(const v8::Persistent<S, M>&)
/usr/local/lib/node_modules/node-red/node_modules/openzwave-shared/node_modules/nan/nan_implementation_12_inl.h:400:21: note: template<class T, class M> v8::Local<T> Nan::New(const Nan::Persistent<T, M>&)
/usr/local/lib/node_modules/node-red/node_modules/openzwave-shared/node_modules/nan/nan_implementation_12_inl.h:405:21: note: template<class T> v8::Local<T> Nan::New(const Nan::Global<T>&)
/usr/local/lib/node_modules/node-red/node_modules/openzwave-shared/node_modules/nan/nan_new.h:201:1: note: template<class T> typename Nan::imp::Factory::return_t Nan::New()
/usr/local/lib/node_modules/node-red/node_modules/openzwave-shared/node_modules/nan/nan_new.h:207:1: note: template<class T, class A0> typename Nan::imp::Factory<T>::return_t Nan::New(A0)
/usr/local/lib/node_modules/node-red/node_modules/openzwave-shared/node_modules/nan/nan_new.h:213:1: note: template<class T, class A0, class A1> typename Nan::imp::Factory<T>::return_t Nan::New(A0, A1)
/usr/local/lib/node_modules/node-red/node_modules/openzwave-shared/node_modules/nan/nan_new.h:219:1: note: template<class T, class A0, class A1, class A2> typename Nan::imp::Factory<T>::return_t Nan::New(A0, A1, A2)
/usr/local/lib/node_modules/node-red/node_modules/openzwave-shared/node_modules/nan/nan_new.h:225:1: note: template<class T, class A0, class A1, class A2, class A3> typename Nan::imp::Factory<T>::return_t Nan::New(A0, A1, A2, A3)
/usr/local/lib/node_modules/node-red/node_modules/openzwave-shared/node_modules/nan/nan_new.h:237:1: note: template<class T> typename Nan::imp::Factory::return_t Nan::New(Nan::FunctionCallback, v8::Local<v8::Value>)
/usr/local/lib/node_modules/node-red/node_modules/openzwave-shared/node_modules/nan/nan_new.h:245:1: note: template<class T, class A2> typename Nan::imp::Factory<T>::return_t Nan::New(Nan::FunctionCallback, v8::Local<v8::Value>, A2)
/usr/local/lib/node_modules/node-red/node_modules/openzwave-shared/node_modules/nan/nan_new.h: In function ‘v8::Local<T> Nan::imp::To(v8::Local<v8::Integer>) [with T = v8::Integer]’:
/usr/local/lib/node_modules/node-red/node_modules/openzwave-shared/node_modules/nan/nan_new.h:22:1: warning: control reaches end of non-void function [-Wreturn-type]
make: *** [Release/obj.target/openzwave_shared/src/callbacks.o] Error 1
make: Leaving directory `/usr/local/lib/node_modules/node-red/node_modules/openzwave-shared/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.4.27-hypriotos+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/node-red/node_modules/openzwave-shared
gyp ERR! node -v v4.4.3
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm info openzwave-shared@1.2.0 Failed to exec install script
npm ERR! Linux 4.4.27-hypriotos+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "openzwave-shared"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! openzwave-shared@1.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the openzwave-shared@1.2.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the openzwave-shared package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs openzwave-shared
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls openzwave-shared
npm ERR! There is likely additional logging output above.
npm info preuninstall openzwave-shared@1.2.0
npm info uninstall openzwave-shared@1.2.0
npm info postuninstall openzwave-shared@1.2.0

**Comment by Fishwaldo** [comment]
I think you are looking for node-openzwave. We don't have npm in the core library.
