### ISSUE TITLE
Fibaro motion sensor - Burglar object unknow values 254?

### ISSUE THREAD

**Issue by gjniewenhuijse** [OpenZWave/open-zwave#1054]
What values can i expect when i use the Burglar object from the Fibaro motion sensor?

0 = no motion
3 = tamper
8 = motion
254 = ?

where can i find the values and description that are written to this object?

**Comment by nechry** [comment]
Take a look on Sigma web site the SDK about Alarm CC is fully explain.
http://z-wave.sigmadesigns.com/design-z-wave/

This isn't a OZW issue though. Any further questions, please use our mailing list:

https://groups.google.com/forum/#!forum/openzwave

**Comment by kolossboss** [comment]
254 = Deepsleep
