### ISSUE TITLE
OTA updates

### ISSUE THREAD

**Issue by antares2001** [OpenZWave/open-zwave#1057]
Hello,

AFAIK the ZWave Plus protocol supports OTA firmware updates. It seems that OpenZWave is not yet capable of this. Are there any plans to add support for OTA updates to OpenZWave?

Thanks and cheers!

**Comment by Fishwaldo** [comment]
some vendors that support us with hardware have been reluctant to provide OTA firmware files for us to test with.... and I don't know of other vendors that publicly release their OTA firmware so I see no point at the moment.

**Comment by pbootsma** [comment]
Aeon Labs publishes their firmwares for the Aeotec products : [https://aeotec.freshdesk.com/support/home](url)

**Comment by jvolkman** [comment]
HomeSeer publishes firmware for their line of switches and dimmers (rebranded DragonTech). http://www.homeseer.com/current-downloads.html

**Comment by RoyKas** [comment]
Z-Uno supports firmware update OTA:
[https://z-uno.z-wave.me/z-wave/ota/](https://z-uno.z-wave.me/z-wave/ota/)

**Comment by michapr** [comment]
will it be reopened? Or should be created a new issue?
For Z-Uno (as sample) it is very helpful to have this feature for updating sketches and firmware.
Z-Way support it (as sample) - yes, of course,... same vendor ;)

**Comment by SuneRadich** [comment]
For what its worth, Logicsoft releases ota firmware for their stuff too

http://logichome.dk/index.php/10-support-categories/6-zhc5010-firmware

**Comment by nechry** [comment]
HomeSeer will release soon a OTA tool
![img_1195](https://cloud.githubusercontent.com/assets/307966/25563954/20c267c4-2da8-11e7-8922-9bbb116f3a44.PNG)

**Comment by robbiet480** [comment]
FYI while their firmware is available for download, Homeseer has stated that their firmware is in an encrypted format which can only be written via HS3 or their new Z-Flash tool (which is a paid product btw).

[Source](https://forums.homeseer.com/showpost.php?p=1302933&postcount=8).

**Comment by partytimeexcellent** [comment]
I'm regretting buying the Homeseer switches. I can't believe they want me to spend $45 to update the firmware after spending $500 on switches and their Z-stick. What a racket.

**Comment by JudgeDreddKLC** [comment]
Looks like the firmware is free, but the software to do it costs money? I wonder if the files are compatible with other OTA devices

https://homeseer.com/current-downloads/



  *   Available as a kit with SmartStick+ or UZB stick.
  *   FREE with HS3PRO or any HomeTroller-SEL PRO or HomeTroller S6 PRO

https://shop.homeseer.com/products/homeseer-z-flash-z-wave-ota-firmware-update-software
