### ISSUE TITLE
strange path to config file

### ISSUE THREAD

**Issue by alteholz** [OpenZWave/open-zwave#1061]
The value for the default config file in line 271 of cpp/examples/MinOZW/Main.cpp:
  Options::Create( "../../../config/", "", "" );
looks a bit strange.
Is this really meant to be a relative path or wouldn't something like ~/.config/MinOZW/ be better?

Please see also Debian bug #847062 [1]

  Thorsten

[1] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=847062

**Comment by Fishwaldo** [comment]
That's because upto now, it's been written to run from the source directory. 

MinOZW is more of a example of how to code. I don't see much use as a useful application

**Comment by alteholz** [comment]
Ok, then that's how it should be.
