### ISSUE TITLE
Aeotec by Aeon Labs ZW095 Home Energy Meter not included as secured

### ISSUE THREAD

**Issue by oliverlj** [OpenZWave/open-zwave#1062]
Hi contributors of great ozw project,

I recently bought an ZW095 Home Energy Meter with 1 amper clamp from aeotec device. If i included this one as secured, it works, dont't show me an unlock lock. If I reboot, the device is shown as insecured and the network become laggy. I included the log after the reboot. For the moment, I've included again the device as insecured and all seems good.

p.s : in the log, it is the device 14

[openzwaved.zip](https://github.com/OpenZWave/open-zwave/files/637773/openzwaved.zip)

**Comment by nechry** [comment]
use from Actions TAB the "Refresh node Informations" it should be ok after

**Comment by Fishwaldo** [comment]
Fixed?

**Comment by oliverlj** [comment]
Not tested yet. I'll try in the week

**Comment by Fishwaldo** [comment]
Closing due to no feedback.
