### ISSUE TITLE
Qubino ZMNHID1 cannot set mode

### ISSUE THREAD

**Issue by jotakar** [OpenZWave/open-zwave#1065]
With the last OZwave update the thermostat ON/OFF ZMNHID1 does not accept the mode change. It remains in Off and can not change to Heat.
I've found that if I set this modification in ozwcfg_0xxxxxxxxx
```
            <CommandClass id="64" name="COMMAND_CLASS_THERMOSTAT_MODE" version="1" request_flags="4" innif="true">
                <Instance index="1" />
                <Value type="list" genre="user" instance="1" index="0" label="Mode" units="" read_only="false" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" vindex="0" size="1">
                    <Item label="Off" value="0" />
                    <Item label="No1" value="1" />
                    <Item label="No2" value="2" />
                    <Item label="Heat" value="3" />
                </Value>
                <SupportedModes>
                    <Mode index="0" label="Off" />
                    <Mode index="3" label="Heat" />
                </SupportedModes>
</CommandClass>
```
I see that the value is 3 for Heat, but if I don't use the Items labeles No1 and No2 OpenZwave gives an error.
It looks like OZW assigns the index in the list as the value to be sent to device. So if in OZW control panel I select Heat the device receive the right value, but if I select No1 or No2 it remains in its actual value (Off or Auto).

**Comment by jotakar** [comment]
I've seen in valueList.cpp this code
```
//-----------------------------------------------------------------------------
// <ValueList::SetByValue>
// Set a new value in the device, selected by item index
//-----------------------------------------------------------------------------
bool ValueList::SetByValue
(
    int32 const _value
)
{
    // create a temporary copy of this value to be submitted to the Set() call and set its value to the function param
    ValueList* tempValue = new ValueList( *this );
    tempValue->m_valueIdx = GetItemIdxByValue(_value);

    // Set the value in the device.
    bool ret = ((Value*)tempValue)->Set();

    // clean up the temporary value
    delete tempValue;

    return ret;
}
```
I see that with
 ```
 ValueList* tempValue = new ValueList( *this );
    tempValue->m_valueIdx = GetItemIdxByValue(_value);
```
We send to the device the index of value in the List not the value of the item, because tempValue contains the index not the value. Could be this the problem?
I can't find the definition of Set for ValueList :(

**Comment by jotakar** [comment]
And more:
In the file cpp/src/value_classes/ValueList.cpp  I've replaced
`tempValue->m_valueIdx = GetItemIdxByValue(_value);`
with
`tempValue->m_valueIdx = _value;`
And now I can set the Mode in Qubino and other device (Remotec ZXT120, wth the sme problem in temperature compensation)

**Comment by madarwin** [comment]
I see the same issue when using my Honeywell thermostat. SetByLabel is broken as well due to this change. SetByLabel already calls GetItemIdxByValue and then it calls SetByValue. So with this change GetItemIdxByValue gets called twice.

**Comment by jotakar** [comment]
No, SetByLabel doesnt call GetItemIdxByValue 
`bool ValueList::SetByLabel
(
    string const& _label
)
{
    // Ensure the value is one of the options
    int index = GetItemIdxByLabel( _label );
    if( index < 0 )
    {
        // Item not found
        return false;
    }
    return SetByValue( index );
}`
The argument for **SetByValue** is the **index** in the list. So in **SetByValue**, the call **GetItemIdxByValue** uses as argument _not a value_, but an _index_. 
The name of argument is confuse, I think it should be _index instead f _value.

**Comment by Fishwaldo** [comment]
This is fixed after reverting the ValueList change recently committed.
