### ISSUE TITLE
Remove old docker keys in project settings

### ISSUE THREAD

**Issue by bibi21000** [OpenZWave/open-zwave#1069]
Hi
I use Docker to test python-openzwave. Since a few monthes, I can't pull openzwave from docker:

> Step 9 : RUN make update
> ---> Running in f475da36ffb9
> git clone git://github.com/OpenZWave/open-zwave.git openzwave
> Cloning into 'openzwave'...
> git pull
> Host key verification failed.
> fatal: The remote end hung up unexpectedly
> make: *** [update] Error 1
> Removing intermediate container f475da36ffb9
> The command '/bin/sh -c make update' returned a non-zero code: 2
> ERROR: Build failed: The command '/bin/sh -c make update' returned a non-zero code: 2
> ERROR: Build failed with exit code 2
> ERROR: Build in 'master' (91123558) failed in 0:25:06

Docker has change ... and their keys too

Could you please remove docker key on github. You should find them in settings/deploy keys.
TIA

**Comment by Fishwaldo** [comment]
There are no keys on the settings/deploy for OZW. Check your local known_hosts file on your local machine.
