### ISSUE TITLE
Z Wave

### ISSUE THREAD

**Issue by devvenba** [OpenZWave/open-zwave#1071]
Hi,

We have got ZME UZB1 and we took LM 4 ( Logic Machine 4 ) as the server. Can anyone please let us know how could we reset the Z wave ME stick ( ZME-UZB1 ) ?

Like in Aeotic USB, we have a dedicated reset button. What is the reset procedure here ?

**Comment by Fishwaldo** [comment]
There is a Manager method to reset if it can talk to OZW, otherwise contact ZME
