### ISSUE TITLE
Urgent: Issue coming with OZWException.h file - Please assist

### ISSUE THREAD

**Issue by sidhuy** [OpenZWave/open-zwave#1075]
compiling - $ g++ main.cpp -o run.exe

Compiler Error
In file included from Defs.h:148:0,
                 from Options.h:35,
                 from main.cpp:33:
OZWException.h:46:2: error: expected constructor, destructor, or type conversion before '(' token
main.cpp:344:1: error: expected '}' at end of input

What is the issue with the code in this .h file?  Any help is appreciated.

**Comment by Fishwaldo** [comment]
looks like your compiling with mingw, which isnt officially supported. Please use VS for windows builds.
