### ISSUE TITLE
buildall.bat doesn't work on Windows

### ISSUE THREAD

**Issue by mickyd** [OpenZWave/open-zwave#1088]
The copy command contained an illegal forward-slash '/' in the path thus
preventing further solutions from building

**open-zwave\cpp\build\windows\installer\buildall.bat** 

It should read as

msbuild ..\..\..\examples\windows\MinOZW\vs2010\MinOZW.sln /t:Rebuild /p:Configuration="Debug"
 
msbuild ..\..\..\examples\windows\MinOZW\vs2010\MinOZW.sln /t:Rebuild /p:Configuration="DebugDLL" 

msbuild ..\..\..\examples\windows\MinOZW\vs2010\MinOZW.sln /t:Rebuild /p:Configuration="Release" 

msbuild ..\..\..\examples\windows\MinOZW\vs2010\MinOZW.sln /t:Rebuild /p:Configuration="ReleaseDLL" 

copy ..\..\..\..\dotnet\examples\OZWForm\build\vs2010\*.sln ..\..\..\..\dotnet\examples\OZWForm\src\ 

copy ..\..\..\..\dotnet\examples\OZWForm\build\vs2010\*.csproj ..\..\..\..\dotnet\examples\OZWForm\src\

msbuild ..\..\..\..\dotnet\examples\OZWForm\src\OZWForm.sln /t:Rebuild /p:Configuration="Debug" 

msbuild ..\..\..\..\dotnet\examples\OZWForm\src\OZWForm.sln /t:Rebuild /p:Configuration="Release" 

I created my own local branch but it seems I can't push it as a new **pull request**.  

If you could fix the .bat that would be sweet!  Thanks

**Comment by Fishwaldo** [comment]
That file isn't really used, but I've updated anyway.
