### ISSUE TITLE
Fibaro Universal Sensor FGBS001

### ISSUE THREAD

**Issue by japita-se** [OpenZWave/open-zwave#1101]
With this sensor, when I close/open one of the Input 1/2 Switch, no event "value changed" is generated on the network.

**Comment by nechry** [comment]
Your associations are set correctly?

**Comment by japita-se** [comment]
how can I set the associations?

**Comment by Fishwaldo** [comment]
Hi,
This is a issue tracker and not a support forum. 

Please use our Forums for Questions regarding OpenZWave: 
https://groups.google.com/forum/#!forum/openzwave

Thanks
