### ISSUE TITLE
Fibario Motion sensor and Switched

### ISSUE THREAD

**Issue by japita-se** [OpenZWave/open-zwave#1115]
I have 3 devices: Fibaro Motion Sensor, Switch from Aeotec and Wall Plug from Fibaro.
I deleted Associations and Groups.
If the Fibaro Motion detects 3 times the absence of movements
```
ZWAVE-> value changed -  node64: changed: 48:0:1:Sensor          false->false
ZWAVE-> value changed -  node64: changed: 48:0:1:Sensor          false->false
ZWAVE-> value changed -  node64: changed: 48:0:1:Sensor          false->false
```

my swithces (Wall Plug and Aeotec) goes off. Why?
G

**Comment by Fishwaldo** [comment]
Hi,
This is a issue tracker and not a support forum. 

Please use our Forums for Questions regarding OpenZWave: 
https://groups.google.com/forum/#!forum/openzwave

Thanks
