### ISSUE TITLE
Unable to Pair - FGBHMS-001 and  FGWPF-102 ZW5

### ISSUE THREAD

**Issue by japita-se** [OpenZWave/open-zwave#1119]
Unable to pair the Motion FGBHMS-001 and the Wall Plug FGWPF-102 ZW5
When running the add node operation, and following the instruction of FIBARO (holding down the press button) nothing happens.

**Comment by nechry** [comment]
Always perform a exclude before a include. Check log for remove nodeid 0 after do the include procedure.

Beware to do exactly the click step, one more and you stop the process

**Comment by nechry** [comment]
Your issue is not related to openzwave librairy please use mailling list instead.

**Comment by openzwave-dev-watcher** [comment]
Which mailing list?
This is not supposed to be the mailing list?
Regards



Il giorno mercoledì 1 febbraio 2017 18:31:24 UTC+1, Jean-François Auger ha 
scritto:

**Comment by nechry** [comment]
if you look at github ozw home page:
https://github.com/OpenZWave/open-zwave

it's explained

So the malling list is her: 
https://groups.google.com/forum/#!forum/openzwave

**Comment by openzwave-dev-watcher** [comment]
The same I writing in :)


Il giorno giovedì 2 febbraio 2017 19:42:56 UTC+1, Jean-François Auger ha 
scritto:
