### ISSUE TITLE
Qubino ZMNHAD1 - Failure to leave the network

### ISSUE THREAD

**Issue by dsoulayrol** [OpenZWave/open-zwave#1121]
Hello.

I experience troubles to make some devices leave the network. Here is a simple case with the **Qubino ZMNHAD1.**

I reset my controller to create a new network. I successfully join the device to this network (see `boot_and_add.txt`). However I see three timeouts during this step, which surprises me because the device lays on my desktop, some half a meter from the controller.

I restart my program, keeping the open-zwave cache. I open the network for two minutes and try to remove the device, which fails. I wait for a while, and restart the process, and this fails again. (`boot_and_remove.txt`).

[boot_and_add.txt](https://github.com/OpenZWave/open-zwave/files/750589/boot_and_add.txt)
[boot_and_remove.txt](https://github.com/OpenZWave/open-zwave/files/750590/boot_and_remove.txt)

**Comment by Fishwaldo** [comment]
Hi,
This is a issue tracker and not a support forum. 

Please use our Forums for Questions regarding OpenZWave: 
https://groups.google.com/forum/#!forum/openzwave

Thanks
