### ISSUE TITLE
Issues with the deployment of Fibaro FGS213 modules

### ISSUE THREAD

**Issue by dsoulayrol** [OpenZWave/open-zwave#1122]
Hello.

I observe very low performances with the **Fibaro FGS213**. Because I got this on a large network at first, I have simplified the setup : I now have a fresh new network with four modules, scattered on the story, with only one or two thin dividing walls between them. There is no more than ten meters between each of them. There is no other object in the network, so there is no load.

Below is the logs of a complete boot of the program, and then of the emission of a command to three of them, the fourth one being declared dead on start. All commands are acquitted, but with an important lag. On other occasions, some are lost.

 I do not understand easily what's going on, but I observe that there seems to be a lot of collisions or other communication problems. However other objects, like the older **FGS212**, in the same configuration and in the same place do not present those problems. Could it be some issue with the Z-Wave+ evolution? Where could I search next?

[ozw.txt](https://github.com/OpenZWave/open-zwave/files/750909/ozw.txt)

**Comment by Fishwaldo** [comment]
Hi,
This is a issue tracker and not a support forum. 

Please use our Forums for Questions regarding OpenZWave: 
https://groups.google.com/forum/#!forum/openzwave

Thanks
