### ISSUE TITLE
Add alternative product type for Fibaro FGWPE Wall Plug

### ISSUE THREAD

**Issue by hogend** [OpenZWave/open-zwave#1128]
Please, add Fibaro product type 0200, id 1000 as an alternative for the FGWPE/F Wall Plug.
This one has been sold in the Netherlands (at least for a while).
I.e. 
`<Product type="0200" id="1000" name="FGWPE/F Wall Plug" config="fibaro/fgwpe.xml" />`

**Comment by nechry** [comment]
close by https://github.com/OpenZWave/open-zwave/commit/624bf29d4c11d8baf116c3f55a1bef5b212ed9d5
