### ISSUE TITLE
MutexImpl::Unlock error 0 (1) error every couple of days

### ISSUE THREAD

**Issue by kylehendricks** [OpenZWave/open-zwave#1136]
### Issue Guidelines

I have been using OpenZWave via Home Assistant for a while and have started to get a `MutexImpl::Unlock error 0 (1)` error every few days and need to end up restarting home assistant.

Seems to be `pthread_mutex_unlock` returning an EPERM error which either means the current thread never locked the mutex or the mutex is already unlocked.  Could this be an issue with the usage of the OpenZWave python library in Home Assistant?

Not sure if it matters but I have Home Assistant running in a docker container.

**Comment by tobiasgraf** [comment]
This sounds like this, doesn't it? https://github.com/OpenZWave/open-zwave/pull/1105

**Comment by kylehendricks** [comment]
Ah yes.  That does seem like the same thing.

**Comment by Fishwaldo** [comment]
PR is applied, and some additional code to detect unbalanced Lock/Unlock calls added. Please test.

**Comment by kylehendricks** [comment]
Got it running now.  Probably will have to wait a week or so to really see if it's still happening.

**Comment by Fishwaldo** [comment]
hows it going?

**Comment by kylehendricks** [comment]
So far so good!

**Comment by Fishwaldo** [comment]
Thanks. Closing.
