### ISSUE TITLE
ForceInstances breaks direct association (from Fibaro FGS-223 to FGWPG-102)

### ISSUE THREAD

**Issue by martian** [OpenZWave/open-zwave#1142]
I tried to create a direct association from a fibaro FGS-223, group 4 (S2 on/off) to a fibaro FGWPF-102  (v2.5) wall plug. The association shows up in domoticz and open-zwave-control-panel. I see the association/set command in the log. But in practice, the wall plug does not switch when the FGS button is operated.

After getting this working using a controller using another zwave stack, and some debugging on open-zwave, I found out the ForceInstances workaround not only changes the association to the controller, but also the associations to other nodes. In my case, that causes the association to become non-functional.

**Comment by Fishwaldo** [comment]
please see comments on #1145
