### ISSUE TITLE
Fibaro Multi instance Universal Binary Sensor - Only one detected

### ISSUE THREAD

**Issue by japita-se** [OpenZWave/open-zwave#1168]
I tried to include this device, which has two instances for class 48 and index 0, namely the instance 1 for the first input and the instance 2 for the second input.

However, on the event "node ready" if I print the nodeinfo, I see only one instance.

**Comment by Fishwaldo** [comment]
Log Files please

**Comment by Fishwaldo** [comment]
ping

**Comment by Fishwaldo** [comment]
Closing due to lack of feedback
