### ISSUE TITLE
Issues with Gen5 1Phase meter from AeonLabs

### ISSUE THREAD

**Issue by ado464** [OpenZWave/open-zwave#1180]
Having issues with Gen5 meter suddenly becoming Dead, i did a reset and paired it in again since it wouldn't respond to anything and it then showed up as id 129, even tho the id is currently at 4.
Even after i paired it in again it stays dead, it can't be dead since it's connected to a power source and is somehow paired to the system, so some type of command must be coming through

Anyway, here is the OZW_Log, hope you can help me out

[OZW_Log.txt](https://github.com/OpenZWave/open-zwave/files/850106/OZW_Log.txt)

**Comment by Fishwaldo** [comment]
Hi,
This is a issue tracker and not a support forum. 

Please use our Forums for Questions regarding OpenZWave: 
https://groups.google.com/forum/#!forum/openzwave

Thanks
