### ISSUE TITLE
Out-of-bounds parameter value in Danfoss rsroom.xml

### ISSUE THREAD

**Issue by dsoulayrol** [OpenZWave/open-zwave#1192]
In `config/danfoss/rsroom.xml`, the configuration parameter at index 3 has a out-of-bounds default value (probably a copy of parameter 4):

    <Value type="short" index="3" genre="config" label="Min/Override Setpoint" min="0" max="10" value="12">
      <Help>Min Set-point and override limit</Help>
    </Value>
    <Value type="short" index="4" genre="config" label="Max/Override Setpoint" min="0" max="40" value="12">
      <Help>Max Set-point and override limit</Help>
    </Value>

**Comment by nechry** [comment]
thank's
