### ISSUE TITLE
Security 2 Framework

### ISSUE THREAD

**Issue by danieldeusing** [OpenZWave/open-zwave#1205]
Hello folks,

I just want to clarify if this update has any relevance for open-zwave:

https://castercomm.com/pressrelease/mandatory-security-implementation-z-wave-certified-iot-devices-takes-effect-today/

Kind regards,
Daniel

**Comment by Fishwaldo** [comment]
its been coming for a while, but so far I've not seen any actual devices on the market that support S2.

**Comment by Fishwaldo** [comment]
Hi,
This is a issue tracker and not a support forum. 

Please use our Forums for Questions regarding OpenZWave: 
https://groups.google.com/forum/#!forum/openzwave

Thanks

**Comment by aromanro** [comment]
Just in case others are looking for this info, as far as I can tell from looking over the sources and documentation, no, S2 is not supported right now. It's quite a nuisance to implement (I know, I'm working on it), just the keys exchange is described with 30 steps in the documentation. The documentation (the public one, anyway) is a nightmare, you don't have for example test vectors to check your code results against some known results.

**Comment by NicSil** [comment]
Why is the issue closed? If not implemented, the issue belongs...

**Comment by enobrev** [comment]
I imagine this would count more as a feature request than a support request. 

While there may not have been any S2 products on the market when this ticket was created, there definitely are now.  Are there plans now or in the near future for S2 support.
