### ISSUE TITLE
Incorrect get requests sent to devices

### ISSUE THREAD

**Issue by petrovcicklemen** [OpenZWave/open-zwave#1227]
Hi.

Looking over the inclusion log of the Qubino ZMNHCD1 device I noticed this platform is sending CC_ALARM.ALARM_GET requests instead of the NOTIFICATION_V5.NOTIFICATION_GET requests (which superseded the ALARM class, as stated in the openly released[ zwave specifications, section 4.2.1](url="http://z-wave.sigmadesigns.com/wp-content/uploads/2016/08/SDS12657-12-Z-Wave-Command-Class-Specification-A-M.pdf").

Since the two commands have a different structure, the device doesn't respond to the ALARM_GET command and therefore timeout notifications are received and are appearing in the log (tried it in the Domoticz log and the OpenZwave Control Panel).

Regards.

**Comment by Fishwaldo** [comment]
In later versions of the Spec the renamed ALARM to Notification. But they are essentially the same CC and it's backward compatible. Some work has gone into bringing this CC upto the latest version in the Dev Branch but it still needs more work.
