### ISSUE TITLE
TKB TZ69 sockets don't update KWh (energy)

### ISSUE THREAD

**Issue by stuiow** [OpenZWave/open-zwave#1231]
I've had the newer TKB socket (replacements from TZ88) the TZ69 for a while.

All of them behave in a simialr way.
None of them seem to update energy (kwh accumulated) unless i do a "refresh node info", and then it updates it all in one big clump - not gradual.
I use OZW with domoticz, but it OPZ where this fails in.
1.4-2501-g5af6780-dirty 
Any more info required, please ask.

**Comment by Fishwaldo** [comment]
Hi,
This is a issue tracker and not a support forum. 

Please use our Forums for Questions regarding OpenZWave: 
https://groups.google.com/forum/#!forum/openzwave

Thanks
