### ISSUE TITLE
XML configuration files missing attributes

### ISSUE THREAD

**Issue by olavt** [OpenZWave/open-zwave#1232]
There seems to a be a lot of inconsistencies when it comes to what attributes are present in the XML configuration files. One example is that the "size" attribute is missing on the Value element in lots of the files.

This is just an example: https://github.com/OpenZWave/open-zwave/blob/master/config/qubino/ZMNHADx.xml

**Comment by Fishwaldo** [comment]
Depending upon the type of variable it's completely optional. We do a sanity check on all config files, so if xmllint passes then no issues.

**Comment by nechry** [comment]
@olavt for value of type List, the size is mandatory.
