### ISSUE TITLE
Can't Send basic_set to any device

### ISSUE THREAD

**Issue by rscott78** [OpenZWave/open-zwave#1262]
I'm trying to use the OZWForm sample application that comes with the code. I've got it reading my USB stick and it detects my devices; however, I'm unable to send a BASIC_SET to any devices. Nodes 2, 3 and node 79 are the ones I have primarily been testing with because they are in the same room as I am and easy to see.

I've traced it down to a problem in Basic.cpp, around line 290 where it reads:

```
if( ValueByte* value = static_cast<ValueByte*>( GetValue( 1, 0 ) ) )
{
		value->Set( _level );
		value->Release();
}
```

This if statement always returns false. It seems the BASIC_SET command class isn't being added to the devices' values list.

My devices are Linear/Nortek branded dimmer and switch units; they definitely work with BASIC_SET. Is this a config problem on my end? Or is it a problem with the latest code-base?

Here's the [OZW_Log.txt](https://gist.github.com/rscott78/e948e42267e172250b18c7fa5b84a18b) file.

**Comment by Fishwaldo** [comment]
The dotNet wrapper in 1.4 hasn't had any love for a long time (and is being dropped in the 1.6 version). Suggest you try the wrapper at https://github.com/OpenZWave/openzwave-dotnet-uwp as it's actively maintained and supported by @dotmorten
