### ISSUE TITLE
Binary Switch V2 CC

### ISSUE THREAD

**Issue by Fishwaldo** [OpenZWave/open-zwave#1263]
Add Version 2 of the Spec to our command class. The main difference is:
1) added duration to SET messages (4.12.2)
2) Target Value from a Report message (4.12.3) - This would address #1261 if thats a v2 implementation
3) Duration Value from a Report message

added bonus points: update Value::VerifyRefreshedValue to not have to do another GET if we received a target value.

**Comment by AlCalzone** [comment]
I'm on it, more later...

**Comment by Fishwaldo** [comment]
Cool. Against the Dev Branch please!

**Comment by AlCalzone** [comment]
Regarding 2.:
> Target Value from a Report message (4.12.3) - This would address #1261 if thats a v2 implementation
Would you expose the target value to applications as a separate value? 
Or just use it internally? If so, how?

**Comment by Fishwaldo** [comment]
Thanks
