### ISSUE TITLE
Flow Stop gas/water shut-off controller POPE009501

### ISSUE THREAD

**Issue by ulferi** [OpenZWave/open-zwave#1275]
My device is recognized as:
<Product type="0005" id="0001" name="012501 Strike Lock Control" config="popp/012501.xml

But it is a:
Product type="0005" id="0001" name="009501 Flow Stop" config="popp/009501.xml

It works with this file. 
Can someone solve this issue

.......... 
<?xml version="1.0" encoding="utf-8"?>
<Product xmlns='http://code.google.com/p/open-zwave/'>

	
	<CommandClass id="112">
        <Value type="list" index="0" genre="config" label="LED status" units="status" min="0" max="1" size="1" value="0">
			<Help>No help available, self explanatory.....</Help>
			<Item label="LED always ON (Only on operation OFF), Default" value="0" />
			<Item label="LED always OFF (Only on operation ON)" value="1" />
		</Value>
        <Value type="list" index="1" genre="config" label="Shut-off controller behavior" units="status" min="0" max="4" size="1" value="0">
			<Help>The parameter defines how to control the shut-off controller.</Help>
			<Item label="Remote and manually open/close (Default)" value="0" />
			<Item label="Remote open/close only" value="1" />
			<Item label="Only remote open; only manually closing" value="2" />
			<Item label="Only manually open; only remote closing" value="3" />
			<Item label="Manually open/close only" value="4" />
		</Value>
	</CommandClass>
		
	<CommandClass id="133">
		<Associations num_groups="2">
			<Group index="1" max_associations="10" label="Lifeline" />
			<Group index="2" max_associations="10" label="Local Valve Operation" />
		</Associations>
	</CommandClass>

</Product>

**Comment by nechry** [comment]
the Strike Lock Control have the product type=0005 id=0001:
http://products.z-wavealliance.org/products/2147

Popp mixed pcb and products ids many times. so we can't do anything for this.

but from your side you can temporary patch your xml before inclusion process. Your device will be discovered as you expect. if you remove your zwcfg file you must do this trick again.
