### ISSUE TITLE
All Z-Wave devices show battery level at 100%

### ISSUE THREAD

**Issue by jsg4** [OpenZWave/open-zwave#1289]
Wondering if anyone can help, I am running OZW with around 75 devices, about 15 battery-powered and all of them show battery level at 100% even though there are some that are old and even have stopped working due to battery level, but it does not update. I have tried to heal the network every night, lights, switches, motion, open/close status all is great except battery level. Anyway to fix this?

**Comment by Fishwaldo** [comment]
Check the device config options, sometimes you need to configure the device to send periodic updates. If not, then you should occasionally poll the ValueID for updates.
