### ISSUE TITLE
RSSI level of the network nodes

### ISSUE THREAD

**Issue by fonss** [OpenZWave/open-zwave#1301]
Is there any standard method to obtain the power level of a Z-Wave node?

The idea is to determine a threshold level to guarantee a good coverage or to decide to use a repeater.

**Comment by Fishwaldo** [comment]
Hi,
This is a issue tracker and not a support forum. 

Please use our Forums for Questions regarding OpenZWave: 
https://groups.google.com/forum/#!forum/openzwave

Thanks

**Comment by nowox** [comment]
Not sure it is a support request, but a feature request. There is no trace of `rssi` in the openzwave source code, but Z-Wave mention this field.
