### ISSUE TITLE
Adding CT-32 Thermostat (id=2002, type=0100)

### ISSUE THREAD

**Issue by qient** [OpenZWave/open-zwave#1302]
I have an AT&T Digital Life thermostat. It appears to be a variant of the CT-30 thermostat that already exists in the device database - I have verified as best I can with my unit that the operation and configuration parameters are the same.

I would be grateful if you could consider adding this to the device database:

<Manufacturer id="98" name="2GIG Technologies">
<Product type="2002" id="100" name="AT&T Digital Life Thermostat" config="2gig/ct30.xml"/>

**Comment by nechry** [comment]
can you provide more information

**Comment by Fishwaldo** [comment]
No Reply. Closing.
