### ISSUE TITLE
Soft Reset with Z-Stick Gen5 USB key from AEOTEC

### ISSUE THREAD

**Issue by jmberhault** [OpenZWave/open-zwave#1318]
Soft reset with this dongle looks not working well for windows (7 in my case), and raspberry Pi. After soft reset function calls (inclusion, ....), return failed.

**Comment by Fishwaldo** [comment]
Hi,
This is a issue tracker and not a support forum. 

Please use our Forums for Questions regarding OpenZWave: 
https://groups.google.com/forum/#!forum/openzwave

Thanks
