### ISSUE TITLE
New Device: Zooz Light Switch ZEN23 V2.0

### ISSUE THREAD

**Issue by Ittiz** [OpenZWave/open-zwave#1327]
Manufacturer: Zooz
Type: Toggle Switch
ID: ZEN23 V2.0
Name: Zooz ZEN23 Toggle Switch Ver2
[Config.zip](https://github.com/OpenZWave/open-zwave/files/1335292/Config.zip)

**Comment by LouiS22** [comment]
You have to push your files into the repo. You can find a how to at the main page.

**Comment by nechry** [comment]
I will check

**Comment by nechry** [comment]
the ZEN23 V2 and V1 share same config file, I use the same
