### ISSUE TITLE
Doxyfiles XML_SCHEMA and XML_DTD tags generating warnings on install

### ISSUE THREAD

**Issue by dnoliver** [OpenZWave/open-zwave#1329]
This is not actually an issue! but every time I install openzwave, I see the warnings logs about deprecated properties being used. 

```
Creating Documentation at /opt/open-zwave/docs/api/
warning: Tag `XML_SCHEMA' at line 1786 of file `Doxyfile' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using
"doxygen -u"
warning: Tag `XML_DTD' at line 1792 of file `Doxyfile' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using
"doxygen -u"
Linking Shared Library
```

You should only see that warning once in your lifetime, when you first install openzwave, but in my case, I am using Travis to build a library that use openzwave, so each time a build is executed, this warnings appear. :)

Sorry for annoying you with this minor issue

**Comment by Fishwaldo** [comment]
Unfortuantly we gotta support older doxygen's (CentOS 6) so not much we can do about that yet. its harmless like you mention though.
