### ISSUE TITLE
OZW Compatibility with Bridge Controller

### ISSUE THREAD

**Issue by lcbudnick** [OpenZWave/open-zwave#1345]
Compatibility page lists "Sigma Designs UZB Stick" as compatible. Please note that the Bridge Controller version (ACC-UZB3-U-BRG) appears to not be compatible. Ref: https://groups.google.com/forum/#!msg/openzwave/iV1klDgeZQ0/30RFCNkRDAAJ and personal experience.

**Comment by Fishwaldo** [comment]
we don't support any bridge firmware etc.
