### ISSUE TITLE
Z-Wave Secure Boiler Receiver HRT (SRT 322) - doesnt update relay status

### ISSUE THREAD

**Issue by vladitep** [OpenZWave/open-zwave#1362]
Device marked as supported, added to openzwave properly, shown as it should, i can control relay position, but cant see relay status if it change by thermostat.
With vera lite, relay status shown properly, so receiver send it to controller, but when i try to use it with openzwave - i can not see state, openzwave ignore state change

**Comment by nechry** [comment]
Is possible vera do polling to get refresh ?

**Comment by japita-se** [comment]
I have the same problem for Aeotec devices and only if I use S2 inclusion.

**Comment by Fishwaldo** [comment]
Make sure the controller node is in the right Association Groups on the device. 

If still problems, please take this to the mailing list.
