### ISSUE TITLE
missing symbols for shared library when cross-compiling

### ISSUE THREAD

**Issue by artynet** [OpenZWave/open-zwave#1373]
Hello folks,

after cross-compiling the library using the OpenWRT makefile :

https://github.com/openwrt/packages/blob/master/utils/openzwave/Makefile

all zwave symbols are missing in the shared library while are normally archived in static one :

```
root@lede-17014 /root [#]# objdump -t /usr/lib/libopenzwave.so.1.4 

/usr/lib/libopenzwave.so.1.4:     file format elf32-i386

SYMBOL TABLE:
no symbols
```
please also refer to the main issue on the OpenWRT packages feed here :

https://github.com/openwrt/packages/issues/5120

The system running is a LEDE virtualbox x86 VM relying on the embedded C library MUSL. Any help would be appreciated...thanks in advance.

Best, Arturo

**Comment by Fishwaldo** [comment]
This is a issue with openwrt, not OZW. We dont strip the library.
