### ISSUE TITLE
Fibaro Heat Controller

### ISSUE THREAD

**Issue by gjniewenhuijse** [OpenZWave/open-zwave#1374]
Is there any plan to support the Fibaro Heat Controller?

https://www.fibaro.com/en/products/the-heat-controller/
also the dedicated temperature sensor - FGBRS-001

**Comment by riemers** [comment]
If someone gets his hands on one, you can read it out and give the information so that it can be supported too. I will get one to play around with, but they are out of stock at my local shop (and the on vacation)

**Comment by nechry** [comment]
Hi,
This is a issue tracker and not a support forum.

Please use our Forums for Questions regarding OpenZWave:
https://groups.google.com/forum/#!forum/openzwave

Thanks
