### ISSUE TITLE
Eurotronics Spirit Z-Wave Plus radiator thermostat

### ISSUE THREAD

**Issue by reimerm** [OpenZWave/open-zwave#1375]
The radiator thermostat is recognized through autodiscovery but the target temperatur and such cannot be controlled.

Attached is the vendors documentation with the classes. As I'm new to OpenZWave I will try to get a funcational xml running but maybe somebody is more fluent with this.

[Spirit_Z-Wave_BAL_web_EN_view_04[1].pdf](https://github.com/OpenZWave/open-zwave/files/1475064/Spirit_Z-Wave_BAL_web_EN_view_04.1.pdf)

**Comment by travellingkiwi** [comment]
There's a pull request in to fix this already... We're all just waiting...

**Comment by reimerm** [comment]
Thanks for the info - forgot to check the pull requests.
