### ISSUE TITLE
Aetoec Multisensor S2 Not Notify Change

### ISSUE THREAD

**Issue by japita-se** [OpenZWave/open-zwave#1394]
We succeed to add Multisensor with S2 (Network Key enabled).
But, strangely, no state change is reported any more.
Without S2, i.e. with an empty Network Key), no poblem encountered.
Same for Fibaro Smoke.
Anyone had these problems?

**Comment by Fishwaldo** [comment]
Hi,
This is a issue tracker and not a support forum. 

Please use our Forums for Questions regarding OpenZWave: 
https://groups.google.com/forum/#!forum/openzwave

Thanks
