### ISSUE TITLE
Update Notification CC

### ISSUE THREAD

**Issue by Fishwaldo** [OpenZWave/open-zwave#1395]

**Comment by tobiasgraf** [comment]
A while ago I implemented the notificaton CC up to Version 5 (based on master branch), but never got to make a PR out of it.
From a quick look at the code on the Dev branch, it looks kinda similar.
I don't have the time for this at the moment but perhaps someone can merge them together or can reuse some defines out of it.
You can find it here: 
https://github.com/tobiasgraf/open-zwave/tree/notificationCC

hope this helps.

**Comment by Fishwaldo** [comment]
Should be done now.
