### ISSUE TITLE
FIBARO FGT-001 - The Heat Controller Radiator Thermostat

### ISSUE THREAD

**Issue by lcervo** [OpenZWave/open-zwave#1396]
I bought 2 new Fibaro radiator valves (https://www.fibaro.com/en/products/the-heat-controller/), their "code" is FGT-001 (https://manuals.fibaro.com/content/manu ... T-v1.0.pdf)  but I don't see any xml for this devices. Is it possible adding the support for those new valves?

Ta.

**Comment by nechry** [comment]
this device require Thermostat Mode ManufacturerSpecific in dev branch https://github.com/OpenZWave/open-zwave/pull/1386 patch to fully operate.

**Comment by NigelRook** [comment]
The dev branch seems to be way behind and lacks fgt001.xml and various other related changes. Is there a process to get this integrated into master?

**Comment by chilicheech** [comment]
Or how do we get the the device configs merged into the dev branch from master?

**Comment by rzr** [comment]
It looks like dev branch is still not merged in master:

https://github.com/OpenZWave/open-zwave/blob/master/cpp/src/command_classes/ThermostatSetpoint.cpp

https://github.com/OpenZWave/open-zwave/pull/1386/commits/47dcee16719eb0338342c372233fa86ce584b56e
