### ISSUE TITLE
Force multichannel on ZMNHBDx

### ISSUE THREAD

**Issue by mbevilacqua** [OpenZWave/open-zwave#1404]
As per #857 could we add `ForceInstances="true"` to ZMNHBDx?
Tested the fix and now both realys + metering work correctly for both individual relays and the aggregated one.

**Comment by mbevilacqua** [comment]
For the sake of anyone reading this, you'll need to exclude and re-associate the devices for this to take affect.

**Comment by nechry** [comment]
Yse like any changes in configuration files
