### ISSUE TITLE
Error in the ZMNHIDxS1.xml config file

### ISSUE THREAD

**Issue by ricozen** [OpenZWave/open-zwave#1431]
Hi, 
I have just managed to point out why the setpoint on my Qubino was not working : 
In the ZMNHIDxS1.xml the following command is wrong

CommandClass id="67" override_precision="2" 

It should be :
CommandClass id="67" base="0" override_precision="2" 
as it is in the ZMNHIDxS2.xml

Could you please apply the correction ?
Thanks
Eric

**Comment by nechry** [comment]
Thanks for being careful here, Qubino has several firmware version of their modules. We have none to apply a version-specific config at the time of detection by openzwave. 

The S2 file is for version 2 but is commented in the code, you have to manually comment the S1 line and uncomment the S2 line and then make your inclusion for opebzwave to apply the correct configuration file. 
```
<Product type="0005" id="0051" name="ZMNHIDx Flush on/off thermostat (H1S1P1)" config="qubino/ZMNHIDxS1.xml"/>
		<!--<Product type="0005" id="0051" name="ZMNHIDx Flush on/off thermostat (H1S2P1)" config="qubino/ZMNHIDxS2.xml"/>-->
```
This is the only possible bypass in the moment.
