### ISSUE TITLE
ZWave devices are not properly identified

### ISSUE THREAD

**Issue by sebk-666** [OpenZWave/open-zwave#1451]
Hi,

I'm using OZW usually only through home-assistant and for some months now, I have an issue where newly added devices are not identified with their proper manufacturer/product names but only appear as "Unknown: id=..." and "Unknown: type=...".
The id and type values however match the values in the `manufacturer_specific.xml` file, so - as far as I understand it - the devices should be easy to identify correctly.

To isolate the issue, I downloaded the most recent openzwave-control-panel Docker image and launched that:

![screen shot 2018-02-24 at 12 02 12](https://user-images.githubusercontent.com/21690487/36629834-43b5ce2e-195c-11e8-8789-9509e882908b.png)

I didn't wait for all devices to wake up, but you can see, the devices that were awake are only shown as "Unknown".
The controller is an Aeotec Z-Stick Gen5; the marked device (node ID 27) is an Aeotec ZW117 range extender.
So nothing fancy here and all of the devices are in the `manufacturer_specific.xml`.

![screen shot 2018-02-24 at 12 01 50](https://user-images.githubusercontent.com/21690487/36629900-3aa5b6e0-195d-11e8-9120-ea025ac77718.png)

Sebastian

**Comment by Fishwaldo** [comment]
Sounds like the device database files are not in the right place... anyway...
This is a issue tracker and not a support forum. 

Please use our Forums for Questions regarding OpenZWave: 
https://groups.google.com/forum/#!forum/openzwave

Thanks
