### ISSUE TITLE
Qubino ZMNHADx I2 and I3

### ISSUE THREAD

**Issue by davidnajar** [OpenZWave/open-zwave#1487]
With qubino flush 1 relay ZMNHADx, I'm not able to see I2 and I3 status change. I saw several issues being closed, but after contact with qubino support they say that those inputs does not work with open zwave based controllers. Any workaround?

**Comment by guymcswain** [comment]
See #948.  Instructions provided on how to fix the device xml file.  I'm using the ZMNHAD3 and have a scene switch connected to I2 that reports its state.

**Comment by Fishwaldo** [comment]
#948 is closed. So closing this one.
