### ISSUE TITLE
How to read the value of a configuration parameter with OpenZWave?

### ISSUE THREAD

**Issue by nowox** [OpenZWave/open-zwave#1488]
I am using Python OpenZwave and I noticed that my Nodon Soft Remote does not have any configuration values inside the CONFIGURATION command class despite the support for it (https://github.com/OpenZWave/open-zwave/blob/master/config/nodon/crc360xSofremote.xml). 

I would like to manually read/write parameter directly to my device. Is that possible?

I have opened a very similar issue here: https://github.com/OpenZWave/python-openzwave/issues/121

**Comment by Fishwaldo** [comment]
Make sure that the device is awake and fully completed the interview process. Then config parameters should work. 

Finally,
This is a issue tracker and not a support forum. 

Please use our Forums for Questions regarding OpenZWave: 
https://groups.google.com/forum/#!forum/openzwave

Thanks
