### ISSUE TITLE
New NeoCoolCam PIR variant

### ISSUE THREAD

**Issue by cannfoddr** [OpenZWave/open-zwave#1493]
Just came across a new device variant for and existing device with id="108d":

<Manufacturer id="0258" name="Neo CoolCam">
         <Product type="0003" id="108d" name="Battery Powered PIR Sensor" config="shenzen_neo/nas-pd01z.xml"/>

**Comment by nechry** [comment]
this entry already exist:
https://github.com/OpenZWave/open-zwave/blob/master/config/manufacturer_specific.xml#L891

**Comment by cannfoddr** [comment]
Ok great - was not present in the latest Docker image of Home Assistant
