### ISSUE TITLE
ValueRaw length

### ISSUE THREAD

**Issue by Ryszard-Trojnacki** [OpenZWave/open-zwave#1502]
I have a problem with **UserCodeCmd_Report**. This uses value of **ValueRaw** type.
I have checked and I can send code **UserCode::SetValue** to device with length from 4 to 10. This is done correct because the code is send with length.
But when the code is received with **UserCodeCmd_Report** is also has length from 4 to 10 - ozw.log:
```
2018-05-07 12:50:42.349 Info, Node017, User Code Packet is 10
2018-05-07 13:14:00.509 Info, Node017, User Code Packet is 4
```
and this also is correct.
Problem is with **ValueRaw** -> **OnValueRefreshed**(data,size).
Size in **UserCode::HandleMsg** is correct, but it is used invalid in **ValueRaw::OnValueRefreshed**.
And there is also a memory leak in this **ValueRaw** implementation.

For example:
**ValueRaw** has initial size 10 (`m_valueLength=10`). 
Device sends **UserCodeCmd_Report** with _User Code Packet is 4_. 
**OnValueRefreshed** is called with `_length=4.` 
Value is changed: `m_value = new uint8[_length];` the array **m_value** has size 4, but **GetValueAsRaw** is calling memcpy with initial size - that is 10:
```c++
*o_length = value->GetLength();  // GetLength() returns 10
*o_value = new uint8[*o_length];   // o_value array is a size of 10
memcpy( *o_value, value->GetValue(), *o_length ); // value->GetValue() is array of size 4; 6 bytes are copied from random memory (garbage)...
```
This problem also occures in **Value::VerifyRefreshedValue** code:
```c++
	case ValueID::ValueType_Raw:			// raw
		bOriginalEqual = ( memcmp( _originalValue, _newValue, _length ) == 0 );
```
is called on arrays (`_originalValue`, `_newValue`) with can have diffrent size. Same with:
```c++
		case ValueID::ValueType_Raw:
			bCheckEqual = ( memcmp( _checkValue, _newValue, _length ) == 0 );
```

There is also problem with length not beeing check.
For example if I have code with length 10: _1234567890_ and I change it to code _1234_ (length 4) then **Value::VerifyRefreshedValue** will return 0, because:
```c++
memcmp("1234567890", "1234", 4) == 0
```

**Comment by Fishwaldo** [comment]
Ok. Good catch. Thanks!
