### ISSUE TITLE
ValueRaw memory leak

### ISSUE THREAD

**Issue by Ryszard-Trojnacki** [OpenZWave/open-zwave#1503]
While checking issue #1502 I have spotted a memory leak - memory is not freed.

Memory is allocated in **ValueRaw::OnValueRefreshed**:
```c++
		m_valueCheck = new uint8[_length];
```
but it is not freed in destructor.

I'm not sure if this also shouldn't bee freed in **ValueRaw::OnValueRefreshed:** case 2?

**Comment by Fishwaldo** [comment]
I don't see in the PR #1504 where you fix this?

**Comment by Fishwaldo** [comment]
ehhh. I'm blind.... sorry. Ignore that comment.
