### ISSUE TITLE
100% CPU and not able to send commands

### ISSUE THREAD

**Issue by bostjane** [OpenZWave/open-zwave#1531]
Hi,

I use OZW in Domoticz and from time to time it happens (once per 2-3 days) that OZW takes 100% CPU. When this happens, messages from nodes still get to Domoticz, but I'm unable to send any commands to devices. Disabling and enabling OZW module solves the problem - Domoticz service does not need to be restarted. Domoticz is version 3.8153 and OZW is 1.4.2501.g5af6780.dirty

Considering the symptoms, this is not a known bug in OZW in case USB controller is plugged out of USB, but something else. Maybe some sort of dead lock/race condition between OZW threads? If I see correctly in attached logs, looks like problems with sending queue/thread? The two logs include switching node 43 to off in one it works and in other doesn't anymore. I have a complete logs if necessary, but is around 150MB so I didn't include it for now.

[OZW_Log02 - node43 off - OK.txt](https://github.com/OpenZWave/open-zwave/files/2100884/OZW_Log02.-.node43.off.-.OK.txt)
[OZW_Log07 - node 43 off - doesn't work.txt](https://github.com/OpenZWave/open-zwave/files/2100885/OZW_Log07.-.node.43.off.-.doesn.t.work.txt)

**Comment by Fishwaldo** [comment]
There is nothing obvious in the Log Files. if you know how to drive a debugger, best would be to get a backtrace of OZW when its 100% utilization.

**Comment by Fishwaldo** [comment]
ping

**Comment by bostjane** [comment]
After weeks of using latest Domoticz with slightly newer version of OZW (1.4.2893.g22d04077.dirty) issue does not seem to arise any more. It could be it was fixed in version between, so at least for now I can say it's a closed case.
