### ISSUE TITLE
Possible Bug with Schlage BE469 deadbolt - Command Class Alarm Index 10 Burglar

### ISSUE THREAD

**Issue by ptdalen** [OpenZWave/open-zwave#1544]
Using OpenZwave with Home Assistant I've noticed that if a tamper alert is received that the value changes from 0 to 2 (or 3 as it should), but never returns to '0'

```
<CommandClass id="113" name="COMMAND_CLASS_ALARM" version="3" request_flags="2" issecured="true">

<Value type="byte" genre="user" instance="1" index="10" label="Burglar" units="" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="255" value="0" />
```
The alert does not clear even after removing power from the lock, or restarting OpenZwave.  It seems as if this should clear after the alert has cleared.

**Comment by Fishwaldo** [comment]
We only report what the device reports. If you refresh the Value, and it remains at 2 or 3, then thats what the device is reporting... best to check with the manufacturer what the intended behavior is. 

This is a issue tracker and not a support forum. 

Please use our Forums for Questions regarding OpenZWave: 
https://groups.google.com/forum/#!forum/openzwave

Thanks
