### ISSUE TITLE
Remove Node Failed

### ISSUE THREAD

**Issue by SlyAndrew** [OpenZWave/open-zwave#1549]
When I try to remove a node, the sensor it's been removed but it stay inside the memory chip; in fact the operation is successful for sensor but not for the chip because it response with a Failed.

**Comment by Fishwaldo** [comment]
Hi,
This is a issue tracker and not a support forum. 

Please use our Forums for Questions regarding OpenZWave: 
https://groups.google.com/forum/#!forum/openzwave

Thanks
