### ISSUE TITLE
ZSticks

### ISSUE THREAD

**Issue by kdschlosser** [OpenZWave/open-zwave#1552]
I am not sure where to post this information. And I have not done any work with GitHub wiki elements. But possibly someone may want to add/make changes for this.

The  Aeon Z-Stick Gen5 is actually a Sigma Designs UZB Stick. that should be put into the comments for the Aeon Z-Stick Gen5. the Hardware ID for this device is VID_0658&PID_0200 You may want to add a column to contain this information as well. so if a user was wanting to create an automatic discovery of the controllers the information is available to do so. 

I also wanted to say Thank You to all of those involved, for spending the time to put together this code.
I do apologize if I have put this in the wrong place

### Issue Guidelines

Before opening a new issue, please review the following:
* The Github Issues is for OZW Bugs only. Please do not use this for general questions or howto type conversations. If you have a question, please post to our mailing list at https://groups.google.com/forum/#!forum/openzwave
* Please use the search feature to see if your issues have been raised or addressed first.
* Try the OpenZWave Log Analyzer at http://www.openzwave.com/log-analyzer if you are experiencing problems with a device on your network.
* Often we will require Log Files to help diagnose the issue. Please stop any application you are using, remove zwcfg_*.xml/ozwcache_*.xml files, and restart your application. After experiencing your issue, stop your application and attach the OZW_Log.txt file to this issue (please do not filter the log file, we often need the full log file to diagnose issues)
* If you want to add a new device to the OZW Database, please consult https://github.com/OpenZWave/open-zwave/wiki/Adding-Devices

**Comment by Fishwaldo** [comment]
This isn't quite correct. The Sigma UZB is the reference design. Aeon labs have built on additional features/functionality into their stick, so they are different devices.
