### ISSUE TITLE
NONCE REQUEST TIMER

### ISSUE THREAD

**Issue by lijia00** [OpenZWave/open-zwave#1561]
Hi,

When using the library to send a command to a S0 device, how long will will it wait for the Nonce Report message after sending a Nonce Get before retrying? Is there a way to adjust the timeout for this? I could not find it in the source. The issue is that when sending to a FLiRS device, if the destination device does not reply fast enough, the library will do a re-try and send out additional wake up beams to the FLiRS device - not giving it enough time to reply. This issue doesnt occur if the FLiRS device (Door lock) replies within milliseconds, but as range increases it won't reply fast enough.

**Comment by Fishwaldo** [comment]
We don't implement timeouts specifically for NONE_GET. You can adjust the ACK_TIMEOUT or RETRY_TIMEOUT in Defs.h
