### ISSUE TITLE
Improper product types and product id's

### ISSUE THREAD

**Issue by kdschlosser** [OpenZWave/open-zwave#1577]
I am almost certain this is a bug. 

I have an Aeotec gen 5 US model z-stick. There are several configuration parameters that are available for this device.

I looked into the device configuration files and there is a file for this device.
I check the manufacturer_specific.xml to see if there is a proper pointing to the device file. there are 3 entries for this model number. one for each region.

    <Product type="0001" id="005a" name="ZW090 Z-Stick Gen5 EU" config="aeotec/zw090.xml"/>
    <Product type="0101" id="005a" name="ZW090 Z-Stick Gen5 US" config="aeotec/zw090.xml"/>
    <Product type="0201" id="005a" name="ZW090 Z-Stick Gen5 AU" config="aeotec/zw090.xml"/>

then I take a look in the save file for my network and i see the entry for the controller but there are is no other information on the config parameters

    <Node id="1" name="Aeotec ZW090 Z-Stick Gen5 US" location="Z-Wave Network Controller" basic="2" generic="2" specific="1" type="Static PC Controller" listening="true" frequentListening="false" beaming="true" routing="false" max_baud_rate="40000" version="4" query_stage="Complete">
        <Manufacturer id="86" name="Aeotec">
            <Product type="101" id="5a" name="ZW090 Z-Stick Gen5 US" />
        </Manufacturer>
        <CommandClasses>
            <CommandClass id="32" name="COMMAND_CLASS_BASIC" version="1" after_mark="true">
                <Instance index="1" />
                <Value type="byte" genre="basic" instance="1" index="0" label="Basic" units="" read_only="false" write_only="false" verify_changes="false" poll_intensity="1" min="0" max="255" value="0" />
            </CommandClass>
        </CommandClasses>
    </Node>

I am not entirely sure what is causing this behavior. I would like to adjust/check the radio transmission power output. 

I have tried resetting the user config data with no luck. any assistance would be appreciated 

Thanks again
Kevin

**Comment by nechry** [comment]
Unfortunately the primary controller can’t self assign parameters settings. You can use the aeotec backup utility tool to change power level, but I didn’t recommend, for network reliability.
