### ISSUE TITLE
Color of RGBW devices being refreshed extensively 

### ISSUE THREAD

**Issue by thucar** [OpenZWave/open-zwave#1578]
I'm having some issues with my Fibaro RGBW modules. Every time I set a color, they generate massive amounts of network chatter. Looking at the log files, it would seem that every time a "ColorCmd_Set" is sent, it is followed by a long list of "ColorCmd_Get" queries. I've counted up to 32 "ColorCmd_Get" requests after a single "ColorCmd_Set."

I do understand that for better data accuracy, after sending a command it is followed by a request to see if the new values have been set by the node. However, at the moment I wish there was a way to disable the follow-up polling. With three RGBW devices my whole network becomes unresponsive every time I change a color in any of them.

The node in question is Node016
[OZW_Log_log.txt](https://github.com/OpenZWave/open-zwave/files/2279929/OZW_Log_log.txt)

**Comment by Fishwaldo** [comment]
`2018-08-11 07:23:17.426 Detail, Node016, Changes to this value are verified
2018-08-11 07:23:17.426 Info, Node016, Changed value (changed again)--rechecking`

You have SetChangeVerified on the Color ValueID. Disable that, and it should reduce the chatter.
