### ISSUE TITLE
Secure inclusion not working

### ISSUE THREAD

**Issue by Venni27** [OpenZWave/open-zwave#1583]
Hello,

I have problems with secure connections in current master branch.
The Fix #1560 should fixed this, as it is in the actual master.
I am using the lib in conjunction with:
https://github.com/ioBroker/ioBroker.zwave

The lib master branch is also installed in the script:
`function installOpenZwaveFromSource() {
  doScript('curl -L -O https://github.com/OpenZWave/open-zwave/archive/master.zip');
  doScript('rm -rf open-zwave-master');
  doScript('unzip master.zip && rm master.zip');
  // Add Patch 1125, needed for CentralScene Support
  doScript('cd open-zwave-master && curl -O -L https://github.com/OpenZWave/open-zwave/pull/1125.patch && patch -p1 < 1125.patch');
  doScript('cd open-zwave-master && make && sudo make install');
}`

The error in the log:
2018-08-18 13:10:55.401 - info: zwave.0 controller command feedback: state: "Command invocation had error(s) and was aborted", error: "Failed", helpmsg: "ControllerCommand - Error - Failed"

The device is included, but unsecure.

**Comment by Fishwaldo** [comment]
Need to see the full OZW logfile. Not the application log.

**Comment by Fishwaldo** [comment]
Closing. No Response.
