### ISSUE TITLE
Seen "handle request for 0x0a** Please report this message"

### ISSUE THREAD

**Issue by jviki** [OpenZWave/open-zwave#1586]
When connecting ZME_UZB1 USB Stick (0115:0001) from Z-Wave.Me (Static Controller library, version Z-Wave 4.05) I can sometimes see the following lines in the log:

```
Sending (Command) message (Callback ID=0x00, Expected Reply=0x20) - FUNC_ID_ZW_MEMORY_GET_ID: 0x01, 0x03, 0x00, 0x20, 0xdc
**TODO: handle request for 0x0a** Please report this message.
```

**Comment by Fishwaldo** [comment]
That can be safely ignored. I should remove that message one day!
