### ISSUE TITLE
cpp/src/command_classes/Color.cpp:749: suspicious expression ?

### ISSUE THREAD

**Issue by dcb314** [OpenZWave/open-zwave#1588]
cpp/src/command_classes/Color.cpp:749]: (style) Boolean result is used in bitwise operation. Clarify expression with parentheses.

Source code is

  if (colvalset[COLORIDX_WARMWHITE] & !colvalset[COLORIDX_COLDWHITE]) {

maybe better code

  if (colvalset[COLORIDX_WARMWHITE] && !colvalset[COLORIDX_COLDWHITE]) {

**Comment by Fishwaldo** [comment]
Fixed.
