### ISSUE TITLE
Access violation when refreshing a node

### ISSUE THREAD

**Issue by dotMorten** [OpenZWave/open-zwave#1609]
When calling RefreshNodeInfo on a node that is not last in the list, an Access Violation is thrown at.

```
>	OpenZWave.dll!OpenZWave::Driver::ReloadNode(const unsigned char _nodeId) Line 7300	C++
 	OpenZWave.dll!OpenZWave::Manager::RefreshNodeInfo(const unsigned int _homeId, const unsigned char _nodeId) Line 785	C++
 	OpenZWave.dll!OpenZWave::ZWManager::[OpenZWave::__IZWManagerPublicNonVirtuals]::RefreshNodeInfo(unsigned int homeId, unsigned char nodeId) Line 385	C++
```
![image](https://user-images.githubusercontent.com/1378165/46188339-6da53e00-c29d-11e8-9893-058842551600.png)

This occurs because when the node is found, the node is removed, and the while-loop continues. However when the NextSibling is called on the now-removed node, it returns an invalid memory location and the next ToElement() will throw:

https://github.com/OpenZWave/open-zwave/blob/39695691bc6fe04c24ede7b037782c52b7c286da/cpp/src/Driver.cpp#L7298-L7313

There's two solutions here: The obvious one is to break out of the loop once the node has been found, the second is to get the nextsibling before removing the node (but I'm assuming there's no point in continuing).

The issue has been observed on UWP and Win32 (not sure about any other platforms), but I'm guessing the while check there might be handling this slightly different.

To reproduce run the Windows Form or UWP app in https://github.com/OpenZWave/openzwave-dotnet-uwp/tree/master/src
Right-click the node in WinForms or if UWP select a device and click the settings-icon in the upper-right in UWP and then select "Refresh Node":

![image](https://user-images.githubusercontent.com/1378165/46189101-d68eb500-c2a1-11e8-8c2e-0d4d553e4632.png)
![image](https://user-images.githubusercontent.com/1378165/46189155-135aac00-c2a2-11e8-8e74-9f2859a4c94b.png)

I confirmed adding a break inside this if-check resolves the issue:
https://github.com/OpenZWave/open-zwave/blob/39695691bc6fe04c24ede7b037782c52b7c286da/cpp/src/Driver.cpp#L7307-L7308

Ref: https://github.com/OpenZWave/openzwave-dotnet-uwp/issues/22

**Comment by Fishwaldo** [comment]
Closed with #1610
