### ISSUE TITLE
Qubino ZMNHCDx Flush Shutter

### ISSUE THREAD

**Issue by arteck** [OpenZWave/open-zwave#1611]
if i set the level value as sample 99 the value is taken over but jump to other value 30..
but the shutter is going to 99.. only the value is wrong.. i can set this now as sample 30 .. same procedure the value is selected and the shutter go to 30.. the value go to 76..

which high value is correct ..254 or 99 ?

**Comment by Fishwaldo** [comment]
Enable Polling. Its probably reporting the current position rather than the final position. Otherwise its a device bug.
