### ISSUE TITLE
Changes in device/values identification (OZW Dev branch) breaks HomeAssistant 

### ISSUE THREAD

**Issue by AlbertoLopSie** [OpenZWave/open-zwave#1615]
Recently installed the Dev branch to my HA installation  (using a shared pyOZW flavor) and noted a few of breaking changes:

- HA changed the (calculated?) unique_id of every zwave sensor/switch/light and thus it adds them as new nodes.
- It no longer recognizes some internal sensors for some devices. As example, on an Aeotec Dimmer, OZW1.4 detected several sensors like "_sensor.aeotec_zw111_nano_dimmer_alarm_level_", "_sensor.aeotec_zw111_nano_dimmer_power_" or "_sensor.aeotec_zw111_nano_dimmer_voltage_".  With the Dev branch it detects them as "_sensor.aeotec_zw111_nano_dimmer_2_", "_sensor.aeotec_zw111_nano_dimmer_3_", "_sensor.aeotec_zw111_nano_dimmer_4_" and so on. It's impossible to correlate them with the previous version.

For other type of devices, the detected entities are like "_switch.unknown_id0000_unknown_type0000_id0000_switch_2_" or "_switch.enerwave_zwnrsm1_plussmart_single_relay_switch_module_switch_6_" 

Could anyone pinpoint the change that's causing this behavior?  I have a forked repo and with the proper guidance I could try to revert that change in my repo.

Thanks!

**Comment by Fishwaldo** [comment]
This is specific to Home Assistant. Not a OZW issue.
