### ISSUE TITLE
unused-private-field on FreeBSD 11.2

### ISSUE THREAD

**Issue by Wraul** [OpenZWave/open-zwave#1626]
https://github.com/OpenZWave/open-zwave/blob/f749fe9cbd82cb0e168f3b217c3de99c37235702/cpp/build/Makefile#L42

For MacOS Mojave you appear to be setting `-Wno-unused-private-field`.
I believe this is needed for FreeBSD 11.2 too, See https://github.com/OpenZWave/python-openzwave/issues/137
I have not tried it on any other versin than 11.2 so I don't know for sure if it is limited to that version.

As I mentioned in the linked issue I think it might be fixed by #1580. But seeing the CFLAG for Mojave I'm not sure if #1580 is your preferred solution.

**Comment by Fishwaldo** [comment]
I prefer to fix the code that add a workaround that hides the issue. This should be fixed in the code. 

I've just removed that flag in commit dd40388 as that slipped through
