### ISSUE TITLE
Cannot compile on MacOS Mojave because of i386 flags

### ISSUE THREAD

**Issue by nospam2k** [OpenZWave/open-zwave#1627]
OpenZWave::SerialControllerImpl::Write(unsigned char*, unsigned int) in SerialControllerImpl.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [/Users/david/Downloads/openzwave-1.4.1/libopenzwave-1.4.dylib] Error 1
make: *** [all] Error 2

Is there a command line, export way of disable i386. I believe it's because Apple is phasing out i386. I can remove i386 flags from cpp/build/Makefile and examples/MinOZW/makefile and it will compile but I don't know if that is the best way to do it.

I am having problems with communicating with my Z-wave device after compiling this but that may be something else.

**Comment by Fishwaldo** [comment]
Fixed in #1606
