### ISSUE TITLE
Release cycle

### ISSUE THREAD

**Issue by alekslyse** [OpenZWave/open-zwave#1646]
I see the latest release is about two years ago but repo quite active. Is the master repo stable enough to replace the outdated release from 2016 or will it be a new release soon?

**Comment by hellfyre** [comment]
I'd also be interested in the answer to this question. It seems that the debian package relies on your releases.

**Comment by Fishwaldo** [comment]
This was just discussed 1 day ago on the mailing list. 

And unfortunately Debian picked the dev tree, which we don’t make releases on.
