### ISSUE TITLE
Devolo home Control Scene Switch MT2652+

### ISSUE THREAD

**Issue by RicardP** [OpenZWave/open-zwave#1653]
Hi,

I cant get this device to show switches/states in control panel, it is found and things looks nice .xml available under under Devolo for this node. 

I am using Domoticz application and I got 4 switches populated in the Domoticz Device list, however I am not even here able to get switches to change state (on vs. off) by pushing any of the 4 buttons.

Tested different setting of buttons from Scene to Basic on/off but nothing helps... a pity as this is a really nice Z-Wave wall switch.

Any idea someone?

Cheers!

**Comment by Fishwaldo** [comment]
Please send logs to the mailing list
# #
Hi,
This is a issue tracker and not a support forum. 

Please use our Forums for Questions regarding OpenZWave: 
https://groups.google.com/forum/#!forum/openzwave

Thanks
