### ISSUE TITLE
Qubino ZMNHLDx setting Antifreeze

### ISSUE THREAD

**Issue by termdude** [OpenZWave/open-zwave#1660]
In the manual for the Qubino ZMNHLDx it says that the configuration parameter 45 is 2 bytes long, however it isn't and you can't change the parameter. When changing to short in the xml, it works though. I have no idea of how to create a pull request for this!

**Comment by termdude** [comment]
It seems as if the format have changed with newer firmware versions...So I guess I'm back to manual editing.

**Comment by nechry** [comment]
yes according to the firmware versions the parameter definition can be different. It's a issue with Qubino device for maintaining clean config file
