### ISSUE TITLE
Zipato RGB is stuck on white 

### ISSUE THREAD

**Issue by warcanoid** [OpenZWave/open-zwave#1669]
Zipato bulb2 is stuck on white color, can only switch on/off. It won’t change to colors anymore, no blue, no red,....

**Comment by Fishwaldo** [comment]
See #1647 

Hi,
This is a issue tracker and not a support forum. 

Please use our Forums for Questions regarding OpenZWave: 
https://groups.google.com/forum/#!forum/openzwave

Thanks
