### ISSUE TITLE
Add a new manufacturer for Weiser locks and a product ID

### ISSUE THREAD

**Issue by BigPino67** [OpenZWave/open-zwave#1671]
Hello

I've bought a Weiser SmartCode 10 with Z-Wave (sku # 9GED18000-002) and my device is not recognized by OpenZWave. Weiser and Kwikset are very similar and I supposed these 2 brands uses Kwikset's z-wave integration. Once i've added my product id in the manufacturer config file, I've got a lot of improvements.

Weiser has the same manufacturer id as Kwikser which is "0090".

I've added this line under the Kwikset manufacturer :
`<Product type="0006" id="0440" name="SmartCode 10" config="kwikset/smartcode.xml"/>`

https://products.z-wavealliance.org/products/2369

Thank you!

**Comment by nechry** [comment]
https://github.com/OpenZWave/open-zwave/commit/2f0290286d8d8d94cbbd0d2fc3d3641e37539e1c
