### ISSUE TITLE
ZW130 Slide event

### ISSUE THREAD

**Issue by ptorrent** [OpenZWave/open-zwave#1677]
Hello there !

I'm trying to get Swipe event but I only have press (value =0), longpress 2sec, (value=2) release (value=0).

Is it normal ? I'm using openzwave 1.5

Thanks a lot for your work !

**Comment by nechry** [comment]
yes, please check the Aeotec user guide

https://aeotec.freshdesk.com/support/solutions/articles/6000162392-wallmote-quad-user-guide-

> **Dimmer control via sliding the button area.**
> 
> The WallMote Quad also supports sliding control, when the parameter 4 [1 byte] has been set to 3, you can slide up or down on the button area to control a dimmer device by sliding up or down. Swiping up once will dim up a dimmer device by a certain percentage, while swiping down once will dim down a dimmer device by a certain percentage.
> 
> **This application is only suitable for Group Association control, it does not work with scene controls.**

This is a issue tracker and not a support forum.

Please use our Forums for Questions regarding OpenZWave:
https://groups.google.com/forum/#!forum/openzwave

Thanks
