### ISSUE TITLE
Porting to baremetal/RTOS platform

### ISSUE THREAD

**Issue by umanayana** [OpenZWave/open-zwave#1696]
We are looking at integrating ZWave controller into out existing IoT product. The product already has a tranciever that operates in the ISM band (908.42MHZ). 

Can this stack be easily ported to baremetal or RTOS platform? 

A brief review of the source code leads me to believe that porting to these kind of platforms are going to be a huge development effort, which may require stack changes. 

Any help is greatly appreciated. 

Thanks

**Comment by Fishwaldo** [comment]
I doubt it very much. we use to much OS supported features like threading etc.
