### ISSUE TITLE
New Open Source Project

### ISSUE THREAD

**Issue by robertsLando** [OpenZWave/open-zwave#1704]
Hi everyone I have developed an open souce project based on this library and it's NodeJS wrapper `node-openzwave-shared` that works as a gateway to MQTT protocol and also Control Panel with almost all open-zwave features and APIs. 

If anyone is interested to contribute or test it every help is welcome

https://github.com/robertsLando/Zwave2Mqtt

Thanks

**Comment by Fishwaldo** [comment]
Hi,
This is a issue tracker and not a support forum. 

Please use our Forums for Questions regarding OpenZWave: 
https://groups.google.com/forum/#!forum/openzwave

Thanks
