### ISSUE TITLE
Opening ttySx dose not work on AMD64

### ISSUE THREAD

**Issue by x-roast** [OpenZWave/open-zwave#1713]
I am aware that this is not a usual use case, but for stability reasons I have to do it this way. I am using a rpi shield  with a rs232 level converter connected to a RS23 port of a PC.
According to the logs, opening ttySx is successful, but no data is sent out (verified with oscilloscope). If I connect the device via usb-serial converter, or create a virtual serial port (ie. using interceptty) openzwave connects properly to the interface.

I traced back the problem and it seems it is related to
`int bits;`
`bits = 0;`
`ioctl( m_hSerialController, TIOCMSET, &bits );`
from  open-zwave/cpp/src/platform/unix/SerialControllerImpl.cpp

If I comment out the above control flag settings it also works properly directly on ttySx, but possibly affects ARM systems.
I suggest that it would be best to clear only the necessary control flags (not all of them).

**Comment by Fishwaldo** [comment]
Patches welcome!
