### ISSUE TITLE
can you add devolo flush-mounted module / Devolo home Control Unknown: type=0002, id=0052

### ISSUE THREAD

**Issue by TheMrg** [OpenZWave/open-zwave#1718]
It is
https://www.devolo.de/smart-home/komfort/smart-home-unterputzgeraete.html

may <Product type="0002" id="0052" name="Smart Metering Modul" config="devolo/mt02792.xml"/>
The Module is nearly like the plug.

**Comment by Fishwaldo** [comment]
https://github.com/OpenZWave/open-zwave/wiki/Adding-Devices
