### ISSUE TITLE
NAS-WR01ZE S2

### ISSUE THREAD

**Issue by Peboli** [OpenZWave/open-zwave#1726]
The new version of the power plug NAS-WR01ZE with support of S2 from Neo Coolcam with Product type="0200" and id="1027" does not use the same parameter index as the previous version.
I got the manual from Neo support, here it is.
[nas-wr01z S2 SmartPlug Manual.pdf](https://github.com/OpenZWave/open-zwave/files/2919783/nas-wr01z.S2.SmartPlug.Manual.pdf)
We need to define a new version in config/shenzen_neo/ folder like nas-wr01z_s2.xml for example.
Here is the version I've made for this new power plug, hope everything is correct as I've a limited knowledge in Zwave config.
[nas-wr01z-s2.zip](https://github.com/OpenZWave/open-zwave/files/2919809/nas-wr01z-s2.zip)

I was not able to include this new module in secured mode, may be there is something else to adapt in the config file, but I don't know what.

**Comment by nechry** [comment]
2 PRs target this device
https://github.com/OpenZWave/open-zwave/pull/1723
https://github.com/OpenZWave/open-zwave/pull/1722
