### ISSUE TITLE
Fibaro keyfob

### ISSUE THREAD

**Issue by jacha05** [OpenZWave/open-zwave#1731]
The central scene support fort the fibaro keyfob only works with 6 scenes (one click) on each button. Not like fibaro designed it to like up to 30 scenes. Like double press hold etc, when doing so the same button central scene gets activated. 

The fibaro dimmer 2 is well implemented and supports double clicks and hold scenes to central scene. Can we do this with this keyfob as well?

**Comment by Fishwaldo** [comment]
Central Scene is fixed in Dev Branch.

**Comment by jacha05** [comment]
Are you saying this work i beta? Some presses on the keyfob work but not all like hold double press etc.
