### ISSUE TITLE
Add new parameters to Linear LB60Z-1

### ISSUE THREAD

**Issue by ropeguru** [OpenZWave/open-zwave#1743]
According to linear, there are three parameters available on this bulb.

http://www.gocontrol.com/manuals/LB60Z-1-Install.pdf

Could the following be added to the xml for the additional parameters?

Parameter 9: Dim / Bright Step Level
When the brightness is adjusted by the controller/gateway, how much the bulb
brightness will change is set by the programmed dimming step level.
Parameter Length Valid Values Confi guration Option
9 1 Byte 1 - 99
Default = 1
The step level is small when the value is low
The step level is large when the value is high

Parameter 10: Dim / Bright Speed
When the brightness is adjusted by the controller/gateway, how fast the bulb
brightness will change is set by the programmed dimming step speed.
Parameter Length Valid Values Configuration Option
10 1 Byte 1 - 10
Default = 3
The step speed is fast when the value is low
The step speed is slow when the value is high

Example: If Parameter 9 is set to the default value of 1, setting Parameter 10
from 1 to 10 will equal the number of seconds it takes to dim down the bulb
when the bulb is turned off, i.e. 1 equals 1 second for the bulb to dim down and
turn off, 10 equals 10 seconds for the bulb to dim down and turn OFF.

**Comment by Fishwaldo** [comment]
https://github.com/OpenZWave/open-zwave/wiki/Adding-Devices
