### ISSUE TITLE
Devolo Smoke Detector MT2651 Wrong ID

### ISSUE THREAD

**Issue by streilu** [OpenZWave/open-zwave#1746]
https://github.com/OpenZWave/open-zwave/blob/c7420ef8dfb9706bf0aca2a47111c7dc3897bde2/config/manufacturer_specific.xml#L516

I was just struggling with my Devolo MT2651 smoke detectors and found out that there's the wrong product-id in the manufacturer_specific.xml.
It should be "04a4" instead of "2001".

See screenshot for reference.

BR Luke
![devolo_mt2651](https://user-images.githubusercontent.com/48616109/54473117-e9576080-47d3-11e9-82ec-e823ec38fceb.png)

**Comment by nechry** [comment]
it can be another version, I have the 2004 version in my hand and this is the right id. I will add your as same product

**Comment by nechry** [comment]
close https://github.com/OpenZWave/open-zwave/commit/986c8f3f4446a40b3eeab7018867e13f5f66ae1b
