### ISSUE TITLE
Where do I can find Openzwave Dockerfile

### ISSUE THREAD

**Issue by robertsLando** [OpenZWave/open-zwave#1753]
I have found your repo on [Docker Hub](https://hub.docker.com/r/openzwave/openzwave-control-panel) But I can't find the source Dockerfile. I would like to use it to create a docker container for my project [Zwave2Mqtt](https://github.com/robertsLando/Zwave2Mqtt) that uses Openzwave. Is there also any prebuild binaries for alpine?

**Comment by Fishwaldo** [comment]
Hi,
This is a issue tracker and not a support forum. 

Please use our Forums for Questions regarding OpenZWave: 
https://groups.google.com/forum/#!forum/openzwave

As for your question - https://github.com/OpenZWave/DockerImages

But as OZW is a library, its images for OZW programs, not OZW itself. 


Thanks
