### ISSUE TITLE
No thermostat set point on Horstmann HRT4-ZW

### ISSUE THREAD

**Issue by sucesor** [OpenZWave/open-zwave#1787]
My thermostat Secure SRT321 (Horstmann HRT4-ZW) worked normally before update up to version 1.6. I use ioBroker smart home server. After update up to 1.6 version, a thermostat has no set point at all in the ioBroker system. When I replaced appropriate command class COMMAND_CLASS_THERMOSTAT_SETPOINT 
`<CommandClass id="67"><Compatibility><Base>0</Base></Compatibility></CommandClass>`
on old format `<CommandClass id="67" base="0" override_precision="2" />` thermostat Setpoint value appeared in the ioBroker system however, it had wrong setpoint type "Cooling 1".

If I use OpenZWave Control Panel, thermostat Setpoint is showed in any case but it has the wrong setpoint type "Cooling 1". The OZW_Log.txt file was attached to the issue.
[OZW_Log.txt](https://github.com/OpenZWave/open-zwave/files/3165070/OZW_Log.txt)

**Comment by Fishwaldo** [comment]
I think I found the problem and just pushed a fix. Please test with > 1.6.158 and let us know how it goes.
