### ISSUE TITLE
Bug in Powerlevel.cpp (setting TestFrames)

### ISSUE THREAD

**Issue by ChPeSc** [OpenZWave/open-zwave#1789]
According to me, there is a bug in the Powerlevel.cpp.

In the method Powerlevel::SetValue( Value const& _value ) there seems to be a wrong type. 
In the "case PowerlevelIndex_TestFrames:" section it reads 

value->OnValueRefreshed( (static_cast<ValueByte const*>( &_value))->GetValue() );

however, the TestFrames value is a **ValueShort**. After correcting to 

value->OnValueRefreshed( (static_cast<ValueShort const*>( &_value))->GetValue() );

and recompiling the library and the concerned application (e.g. ozwcp which seems to links statically to open-zwave) the TestFrames can be set as expected. (Before setting the TestFrames value was impossible and the powerlevel-testing with ZwavePlus was not possible).

Thanks a lot for this very nice piece of software and apologies in case I am mistaken...

CPS

--------------------

Here my git diff (I started from Tag v1.6, but I verified manually that this issue is also present in master branch [47af834] at the same line (line 286) ):

git diff Powerlevel.cpp
diff --git a/cpp/src/command_classes/Powerlevel.cpp b/cpp/src/command_classes/Powerlevel.cpp
index bd8e120..198d487 100644
--- a/cpp/src/command_classes/Powerlevel.cpp
+++ b/cpp/src/command_classes/Powerlevel.cpp
@@ -283,7 +283,7 @@ bool Powerlevel::SetValue
                {
                        if( ValueShort* value = static_cast<ValueShort*>( GetValue( instance, PowerlevelIndex_TestFrames ) ) )
                        {
-                               value->OnValueRefreshed( (static_cast<ValueByte const*>( &_value))->GetValue() );
+                               value->OnValueRefreshed( (static_cast<ValueShort const*>( &_value))->GetValue() );
                                value->Release();
                        }
                        res = true;

**Comment by Fishwaldo** [comment]
Thanks
