### ISSUE TITLE
BeNext AlarmSound : configuration items

### ISSUE THREAD

**Issue by jano42** [OpenZWave/open-zwave#1793]
Hello

I'm facing a problem to configure my BeNext AlarmSound module.

As we can see in config file:  (https://github.com/OpenZWave/open-zwave/blob/master/config/BeNext/AlarmSound.xml) we have many config values.

The value at index 10, is for "Sound/Light index 1" and mapped as single byte.
But in help it is sayed that Params 10 until 27 are used. (total of 18 BYTES)
Only n°10 is in file but from 11 to 27 are not.

````xml
<Value genre="config" index="10" instance="1" label="Sound/Light index 1" type="byte" value="-1">
      <Help>Params 10 until 27 are the values to configure the sound and light thtat are played when index 1 is selected</Help>
</Value>
<Value genre="config" index="28" instance="1" label="Sound/Light index 2" type="byte" value="-1">
      <Help>Params 28 until 45 are the values to configure the sound and light thtat are played when index 2 is selected</Help>
</Value>
<Value genre="config" index="46" instance="1" label="Sound/Light index 3" type="byte" value="-1">
      <Help>Params 46 until 63 are the values to configure the sound and light thtat are played when index 3 is selected</Help>
</Value>
````

So in OpenZWave manager I can configure only item index 10 but not 11 (in fact item 11 to 27 are not autmatically created.

What should I do ? update the xml file by defining each missing parameter ? Or there is something in OZW to manage those "hidden" configuration bytes.

Thanks

Regards

**Comment by Fishwaldo** [comment]
Yes - You would need to add Value Blocks for each missing entry. No way around it :)
