### ISSUE TITLE
Cannot find MergeAllianceProduct tool

### ISSUE THREAD

**Issue by brandond** [OpenZWave/open-zwave#1799]
The [wiki](https://github.com/OpenZWave/open-zwave/wiki/Using-the-MergeAllianceProduct-Script) claims that:
```
The MergeAllianceProduct script is a perl script that we have written to import the 
Device from the Z-Wave Alliance Product Database to the OZW Device Database.

The script is written in perl and is available in the OZW Source distribution 
under the tools directory or you can download it here
```
Where "here" links to this repository. However, there does not seem to be a 'tools' directory in this repo, nor can I find any trace of this script anywhere within the revision history. Has it been replaced with something else? If so, where is it and how do I go about running it?

**Comment by Fishwaldo** [comment]
Hi,
The script is still pretty buggy... the Alliance Database has lots of errors, so I havn't released it yet... 
For the moment, you can copy something like [this](https://github.com/OpenZWave/open-zwave/blob/master/config/aeotec/zw098.xml) as a template for the MetaData Fields

Sorry - we just released 1.6 recently and there is a *LOT* of things todo now to catch up :) (including documentation!)
