### ISSUE TITLE
Many exceptions when querying PST02-A 4 in 1 Multi-Sensor

### ISSUE THREAD

**Issue by gdave321** [OpenZWave/open-zwave#1813]
[OZW_log-exception.txt](https://github.com/OpenZWave/open-zwave/files/3204232/OZW_log-exception.txt)

See attached OZW_log, during startup there are many exceptions being reported for an PST02-A 4 in 1 Multi-Sensor node17  (this is using openzwave-1.6.156)

**Comment by Fishwaldo** [comment]
This is a problem with whatever application is using OZW. The application needs to be fixed. 

As you never stated the application, I can’t help you further.
