### ISSUE TITLE
Carbon Dixoide iso Carbon dioxide in NotificationCCTypes.xml

### ISSUE THREAD

**Issue by gdave321** [OpenZWave/open-zwave#1816]
Noticed that both NotificationCCTypes.xml & Localization.xml spell CO2 as: Carbon Dixoide.
Seems this should be "Carbon Dioxide"

**Comment by gdave321** [comment]
Also Carbon Monoxied should be Carbon Monoxide

**Comment by petergebruers** [comment]
Thank you for reporting this. I'll have a look at that file
