### ISSUE TITLE
Philio PSM02-1 - CommandClass: Door/Window device not added

### ISSUE THREAD

**Issue by a-b-s** [OpenZWave/open-zwave#1846]
Moving from Domoticz Stable V4.10717 using OpenZWave version 1.4-3335-g74e05982-dirty to **Domoticz Beta V4.10717 using OpenZWave version 1.6-764-g210c300b-dirty**, partly breaks the Philio PSM02-1 multisensor. Only **the Door/Window device is not properly included**. 

Error in the domoticz log is the following: 

> OpenZWave: Value_Added: Node: 20 (0x14), CommandClass: SENSOR BINARY, Label: Sensor, Instance: 1, Index: 0

> OpenZWave: Value_Added: Node: 20 (0x14), CommandClass: BATTERY, Label: Battery Level, Instance: 1, Index: 0

> OpenZWave: Value_Added: Node: 20 (0x14), CommandClass: SENSOR MULTILEVEL, Label: Temperature, Instance: 1, Index: 1

> OpenZWave: Value_Added: Node: 20 (0x14), CommandClass: SENSOR MULTILEVEL, Label: Luminance, Instance: 1, Index: 3

> Error: OpenZWave: Exception. Type: 101, Msg: Invalid ValueID passed to GetValueLabel, File: /home/travis/build/domoticz/domoticz/open-zwave-read-only/cpp/src/Manager.cpp (Line 1496)

**Comment by Fishwaldo** [comment]
> Error: OpenZWave: Exception. Type: 101, Msg: Invalid ValueID passed to GetValueLabel, File: /home/travis/build/domoticz/domoticz/open-zwave-read-only/cpp/src/Manager.cpp (Line 1496)

This error is from how domoticz interfaces with OZW. You need to get @gizmocuz to fix it first. If you still have problems after thats fixed, then please reopen this issue with a Full OZW_Log.txt file (after removing ozwcache*.xml file. )
