### ISSUE TITLE
Popp Door/Window Sensor with external sensor

### ISSUE THREAD

**Issue by krsam74** [OpenZWave/open-zwave#1848]
Hi! 
I recently bought a Popp Dorr/WIndow sensor with external sensor. I run Home Assisistant on Hassio/RPi 3B and the sensor is not identified. I can not find it in the open z-wave list so I guess that is why.

Could it be added? What kind of information is needed?  :-D

This is a product link: https://products.z-wavealliance.org/products/3345?fbclid=IwAR0J8H9uEiTTCREbSPR1PJDIJ2rhf2_zmL8bf_R7yQKaFRdus_SNm9ri4gs

Best regards
Kristofer

**Comment by Fishwaldo** [comment]
https://github.com/OpenZWave/open-zwave/wiki/Adding-Devices-(1.4---Old-Version)
