### ISSUE TITLE
Add Node does not comply to Z-Wave protocol specification

### ISSUE THREAD

**Issue by velocityzen** [OpenZWave/open-zwave#1903]
This implementation has `AddNode` method to activate _add mode_ on a controller. 

From the spec:
* Add Node command is used to activate and **de-activate** _add mode_. 
* Mode parameter is used to indicate that
  * value 0x01 – ADD_MODE_ANY
  * value 0x05 – ADD_MODE_STOP

How do you de-activate _add node_ mode in OZW?

The same goes to `RemoveNode` as well

**Comment by petergebruers** [comment]
Not sure what you are saying are asking, OpenZWave really does implement that.

If you write software, always use the "Manager" functions... In this case:

bool Manager::CancelControllerCommand	(	uint32 const 	_homeId	)	

Have a look at its implementation in cpp/src/Driver.cpp

bool Driver::CancelControllerCommand

This one calls

void Driver::AddNodeStop

And there is your ADD_NODE_STOP

msg->Append( ADD_NODE_STOP );

**Comment by velocityzen** [comment]
I thought that BeginControllerCommand and CancelControllerCommand were deprecated. Thank you for explanation. I couldn't find this in docs!

**Comment by Fishwaldo** [comment]
BegincontrollerCommand is depreciated. Use the dedicated controller command methods. CancelControllerCommand can be used for them if necessary
