### ISSUE TITLE
Aeotec Doorbell 6 (zw162) long tone name cause crash

### ISSUE THREAD

**Issue by kennetn** [OpenZWave/open-zwave#1931]
Device: Aeotec ZW162-C Doorbell 6
OpenZWave library: 1.6.902

The doorbell has tone names longer then the 32 characters set aside here: https://github.com/OpenZWave/open-zwave/blob/8aba705ea01d4296fbbd61d53a12a2495e931dfd/cpp/src/command_classes/SoundSwitch.cpp#L163
The names are i.e. "Westminster Chimes (Hearing Enhanced)".
This will cause the debug version to stop with a "buffer to small" message.
I suggest to increase the buffer size to 64 chars.
The other tone names can be seen here: https://aeotec.freshdesk.com/support/solutions/articles/6000202226-doorbell-6-user-guide-

**Comment by Fishwaldo** [comment]
it can actually be a max of 268 chars as the name can be upto 255 chars, and after appending the duration, its 267 + null terminator.

Good catch tho. Glad they updated from the crappy DOS 8.3 format for the old tone names finally.
