### ISSUE TITLE
1.6 branch needed

### ISSUE THREAD

**Issue by cburghardt** [OpenZWave/open-zwave#1938]
The current version 1.5.6 of openzwave-shared fails to compile with the latest version of openzwave. It relies on the master branch which extremely sucks for projects that depend on a working chain of libraries. That is not the first time this chain breaks so I wonder if you have plans to stabilize that.

**Comment by Fishwaldo** [comment]
This is a issue with the wrapper, not OZW.  1.6 is the released version, but they fact they build against HEAD is asking for issues. I’ve already suggested they should go with specific commits but it’s upto the wrapper authors to update.
