### ISSUE TITLE
Reset a meter (command class METER) action at index 257 !

### ISSUE THREAD

**Issue by gxapplications** [OpenZWave/open-zwave#1945]
Hello,

I have a Fibaro FGWPE/F Wall Plug Gen5, and another Fibaro product that both supports METER command class.
Since I migrate to the OpenZwave 1.6 (from 1.4) I noticed the Reset feature of METER Command Class index changed from 33 to 257.

The problem is the main JS framework that uses OZW (your OZW-shared) uses indexes as small int (limited to 0-255) so index 257 cannot be reached anymore :
When trying to call action at index 257, I receive this error :
TypeError: OpenZWave valueId not found: 4-50-1-1
In my code, I'm not asking index 1, but index 257... It should be out of 0-255 bounds...
I looked in your code and confirmed that the Reset feature is well affected at index 257:
https://github.com/OpenZWave/open-zwave/blob/4478eea26b0e1a29184df0515a8034757258ff88/cpp/src/ValueIDIndexesDefines.h#L86

In ozwcache file, I have this, confirming the feature Reset at unreachable index:
```
<Node id="4" name="Plug test" location="Escaliers" basic="4" generic="16" specific="1" roletype="5" devicetype="1792" nodetype="0" type="Binary Power Switch" listening="true" frequentListening="false" beaming="true" routing="true" max_baud_rate="100000" version="4" configrevision="5" query_stage="Complete">
		<Manufacturer id="10f" name="FIBARO System">
			<Product type="602" id="1001" name="FGWPE/F Wall Plug Gen5">
				<MetaData>
					......
				</MetaData>
			</Product>
		</Manufacturer>
		<CommandClasses>
			<CommandClass id="50" name="COMMAND_CLASS_METER">
				<Compatibility />
				<State>
					<CCVersion>2</CCVersion>
					<InNif>true</InNif>
					<StaticRequests>2</StaticRequests>
				</State>
				<Instance index="1" />
				<Value type="decimal" genre="user" instance="1" index="0" label="Electric - kWh" units="kWh" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="0.42">
					<Help></Help>
				</Value>
				<Value type="decimal" genre="user" instance="1" index="2" label="Electric - W" units="W" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="0.0">
					<Help></Help>
				</Value>
				<Value type="bool" genre="user" instance="1" index="256" label="Exporting" units="" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="False">
					<Help></Help>
				</Value>
				<Value type="button" genre="system" instance="1" index="257" label="Reset" units="" read_only="false" write_only="true" verify_changes="false" poll_intensity="0" min="0" max="0">
					<Help></Help>
				</Value>
			</CommandClass>
....
```
How to reset a METER if we cannot use pressButton(x, y, z, 257) ???
Maybe you want to change OZW-shared lib to work with it, or change index in this repository ?

Thanks !

**Comment by Fishwaldo** [comment]
You need to open a issue against the wrapper. This is only for the C++ library. The wrappers are by different authors.
