### ISSUE TITLE
Wrong thermostat Horstmann HRT4-ZW setpoint type

### ISSUE THREAD

**Issue by sucesor** [OpenZWave/open-zwave#1950]
I use ioBriker smart home system. The thermostat Horstmann HRT4-ZW has setpoint type Cooling_1_1 instead Heating_1_1 from version 1.6.0 to 1.6.1

**Comment by Fishwaldo** [comment]
Eh? could you please explain as I don't follow?

**Comment by AlCalzone** [comment]
I'll try to chime in. ioBroker has changed the installation routine for OZW so it uses the downloads from old.openzwave.com as you suggested. This probably has lead to an update of OZW for @sucesor.

It seems that the mentioned thermostat now has a `Cooling` setpoint type when it should be `Heating`

**Comment by sucesor** [comment]
After the last update of the adapter ioBroker.zwave the setpoint type became Heating.
This issue resolved.
Thanks.
