### ISSUE TITLE
Assert message because of wrong type (Type_Notification or Type_UserAlerts)

### ISSUE THREAD

**Issue by kennetn** [OpenZWave/open-zwave#1953]
In HandleMsg a Notification is created with m_type Type_Notification.
https://github.com/OpenZWave/open-zwave/blob/dc9cdaf68ef6c8a243d49dba8630bef5759629de/cpp/src/command_classes/ApplicationStatus.cpp#L56
However when SetUserAlertNotification is called there is an assert that the m_type is Type_UserAlerts and that will fail.
My guess is that the notification should be create with Type_UserAlerts and only send if there actually is something to send.

**Comment by Fishwaldo** [comment]
Thanks!
