### ISSUE TITLE
Zooz Zen27 v2 missing config options

### ISSUE THREAD

**Issue by WizKid** [OpenZWave/open-zwave#1956]
In firmware v2 they added 3 more config options 13, 14 and 15. Example on how they should be configured can be found at https://www.home-assistant.io/docs/z-wave/device-specific/#zooz-scene-capable-onoff-and-dimmer-wall-switches-zen26--zen27---firmware-20

My question before putting up a diff that just adds them in the current zen27 config file will that be bad for people that are running firmware v1? Or should add a new config and somehow gate it to >v2 and if so how do I do that? Or is there something I should put for each of those configs to tell that they are only available in v2?

**Comment by Fishwaldo** [comment]
We can't differentiate between versions (see #644) so just add the new Config Options to the existing list, and put a note in the MetaData ChangeLog with the firmware version you are using.
