### ISSUE TITLE
Getting the queue position of data that is to be sent

### ISSUE THREAD

**Issue by kdschlosser** [OpenZWave/open-zwave#1963]
I have a question/suggestion if it is not yet added.

I am working with command class switch multilevel. This command class offers 2 values that I am interested in using to be able to provide users with a mechanism to be able to programmatically control the speed in which a light raises and lowers it's level.

The 2 values are button values so when set it stays latched until unset. because those 2 values also depend on other values.. the duration value and the start level value we are able to calculate when to press the stop based on the duration.. I know that newer versions of the command class support setting a duration for the set level command. But I do not think that openzwave supports this. and thee are also still a lot of devices out there that do not support the newer command class as well..

The duration the bright and dim values use are based on the length of time to go from 0 to 99 and from 99 to 0.

so if we set a duration of say 30 seconds and the start level is 20 and the target level is 88

30 * 1000 = 30000 (convert to milliseconds)
30000 / 100 = 300 (find out the milliseconds per level)

88 (target level) - 20 (start level) = 68 (number of steps to take)

68 (number of steps) * 300 (milliseconds per step) = 20400 (milliseconds to wait before releasing the button)

It does work as I have outlined above except there are 2 problems that will occur on a busy network. My issues are going to be other commands that are queued ahead of pressing the button. I cannot start the timer blindly without knowing either the position or if the command sent. if there are other commands in the queue and I start the timer right after pressing the button those other commands are going to consume time and the release is going to get sent before it should. the other issue is if there are queued items ahead of the release command being sent. this would cause the ramping to run longer then it should.

Is there a way to prioritize button releases so they would take priority and "skip the line" so to speak. This would be the only way to guarantee the button got released when it is supposed to

But I would also need to know is there a way to leverage the API in order to find out what position in the queue the pressed command is in? or to get some kind of a notification that the pressed command has been sent? This would allow me to know when to start counting down until the release. I am not sure if the device would send an ACK for getting the command or not and this is what would trigger the notification that the command was sent. this may be what is used to remove the command from the queue IDK.. If the ability to check the queue to see if the command is no longer in it would work as well.

If there is a way to achieve this with the current API help would be greatly appreciated. If it cannot be done with the current API adding it may be useful I would imagine there are other command classes that use the button values and it may prove beneficial.

A thought would be to timestamp a value for the last time it was used successfully. This would allow me to adjust the wait time accordingly in order to release it on time.

**Comment by Fishwaldo** [comment]
Even if we "exposed" the queue position, its almost impossible for you to "estimate" when a packet would be delivered, due the nature of the mesh routing. (it can take upto 20 seconds for that to complete, with no feedback to OZW if the actual command was even accepted)

The ValueButton valueID's are not that reliable as a result. Significant rework would be required to change that.
