### ISSUE TITLE
Zooz ZEN22 v3.0

### ISSUE THREAD

**Issue by JakeCK** [OpenZWave/open-zwave#1965]
It appears the ZEN22 v3.0 has not been added, my hassio install has the wrong config parameters and is showing my three ZEN22 v3 switches as v2. I've tried to update the .xml file of the zen22v2 by adding all of the parameters in the manual. This is my first attempt at this, it probably wouldn't work but at least all of the parameters from the manual are included. I have also included a copy of the manual from their website as a PDF.
Maybe someone else more capable can add it in. 

[zooz-z-wave-plus-dimmer-zen22-VER3.01-manual.pdf](https://github.com/OpenZWave/open-zwave/files/3693383/zooz-z-wave-plus-dimmer-zen22-VER3.01-manual.pdf)

[ZEN22v3.zip](https://github.com/OpenZWave/open-zwave/files/3693377/ZEN22v3.zip)

**Comment by Fishwaldo** [comment]
https://github.com/OpenZWave/open-zwave/wiki/Adding-Devices
