### ISSUE TITLE
[REQUEST] Support new Silicon Labs UZB-7 (Z-Wave 700 series controller USB dongle)

### ISSUE THREAD

**Issue by Hedda** [OpenZWave/open-zwave#1970]
Please consider adding support for Silicon Labs UZB-7 (Z-Wave 700 series controller USB dongle)

https://www.silabs.com/documents/public/data-sheets/DSH14483.pdf

https://fccid.io/2ADB9-UZB-7/User-Manual/Users-Manual-4147020

This is Silicon Labs reference design of a Z-Wave 700 series controller USB dongle based on their EFR32ZG14 "Zen Gecko" Z-Wave 700 modem System-on-Chip.

**Comment by petergebruers** [comment]
This is, kind of, a duplicate request of this:

https://github.com/OpenZWave/open-zwave/issues/1768

"Sigma Static Bridge Controller support"

At the moment, all I can do is repeat what I've said in that other issue. Please go there for progress/comments/updates...

I've hacked in bridge support based on OZW 1.6 (master). It works on UZB-7 and on a "Aeotec Z-Stick ZW5" that has the reference implementation of the SK 6.81 bridge firmware + an antenna modification. The test network is small, only 2 relays. Basic functionality with ozwcp and hass is there, this is enough for me to show that it is possible to support bridge library. Update neighbor seems broken, I haven't had time to investigate. If you want to try it, use the "bridge" branch of my fork:

https://github.com/petergebruers/open-zwave
