### ISSUE TITLE
Ability to disable confirmation get for devices with reliable automatic state reporting

### ISSUE THREAD

**Issue by matejdro** [OpenZWave/open-zwave#1980]
Check out the following log. It contains simple action of me toggling (dimming) an Aeotec LED Bulb 6 Multi-Color (E27).

[OZW_Log.txt](https://github.com/OpenZWave/open-zwave/files/3737382/OZW_Log.txt)

From what I understand, this happened:

* Single multilevel set is sent to the bulb
* Because OZW apparently assumes bulb does not properly report its own state, it also sends another get.
* When bulb starts actually dimming, it sends automatic value update
* On first value update, OZW sends THREE ADDITIONAL GET REQUESTS. It looks like device cannot handle those at once, so OZW of course receives timeout, which starts cascading and bogging down the network with retries

Could an option be added in the future to disable confirmation gets for specific devices (that behave well)?

This is from Home Assistant, which is supposedly still based on OZW 1.4 (my apologies if I should not report HA OZW issues here).

**Comment by matejdro** [comment]
This might be related: https://github.com/OpenZWave/python-openzwave/blob/8be4c070294348f3fc268bc1d7ad2c535f352f5a/src-api/openzwave/command.py#L611

**Comment by matejdro** [comment]
Not sure why, but setting the color seems to be even worse, sending 5 get requests for every set request:

[OZW_Log_Colors.txt](https://github.com/OpenZWave/open-zwave/files/3742254/OZW_Log_Colors.txt)

**Comment by Fishwaldo** [comment]
I have not had a chance to look at the issue yet, but multiple requests are required to get each Color Channel (Eg, Red, Green, Blue, Warm White, Cool White etc). Hence the multiple requests. So this is normal.

**Comment by matejdro** [comment]
Yes, that is true. But my point was that many devices (including this bulb) self-report their state on change. So there is no need to get all the data after setting it.
