### ISSUE TITLE
How to activate Network Wide Inclusion?

### ISSUE THREAD

**Issue by thucar** [OpenZWave/open-zwave#1990]
I'm using ZME_UZB1 USB Stick as my controller. It is a Z-wave Plus capable device and since my house has thick indoor walls I rely heavily on the z-wave mesh to have everything working.

Unfortunately I'm currently able to include only about a third of all devices installed in my house. The rest just do not get picked up.

Is NWI supported in the latest OZW? I could not find any references to it in the documentation.

**Comment by Fishwaldo** [comment]
It’s enabled by default. Either you have some devices that don’t support it in your mesh or something else is going on.

**Comment by thucar** [comment]
Well, I have no idea what it might be. I ended up connecting the controller to my laptop, moving around the house and adding all devices by moving next to them.

Communication works fine after adding each node, the mesh looks solid, everyone has loads of neighbors. So I have no idea what might have been the cause

**Comment by petergebruers** [comment]
I would have to guess but possibly this: not only the device has to support NWI, but also the devices between the one you try to include and the controller have to support NWI...

**Comment by thucar** [comment]
I have a number of Z-Wave Plus devices scattered around the house. Mainly Fibaro Dimmer 2's and Switch 2's. Couple roller shutter 2's as well. I'd say about 1/4 of my 60 devices should be Plus capable.

Also, I do not remember having this issue when I originally moved to Node-Red + nodered-openzwave plugin setup. I only ever had issues with devices inside the garage, which is about 20m from the house.
