### ISSUE TITLE
Handling dead nodes due to power failures

### ISSUE THREAD

**Issue by fehguy** [OpenZWave/open-zwave#1993]
Hi all, I've been using ozw for several years and when things are working well, it's just magic. I now have some 55 nodes in a network and it is typically quite reliable.

I have had some excruciatingly painful experiences with nodes "disappearing" which has caused many un-fun weekends. I am probably a slow learner, but it looks like the root cause has been power outages. I have an old house and work on the wiring from time to time, which means I switch the breaker off to avoid early death. In doing so, inevitably a zwave node will go offline long enough for the system to consider it dead.

When this happens, things get ugly. I won't get into details but when the zwave network is unhappy (due to my own poor software design or other), there are hangs, delays, etc. The only 100% reliable solution has been to reinitialize the zwave stick (Aeotec Gen 5) and re-add all the devices. This now takes hours because there are so many.

What is the right process to bring nodes back from the dead? It happened just last night, where two nodes went offline because a breaker was tripped. Now they're dead and I'm trying to revive them without physical intervention.

To make matters worse, I have tried removing dead nodes from the system and re-adding them, which seems to have created some ghost nodes--ones that I do not expect to be in the system any longer but something in the network does, and they are re-added to the ozw cache.

Any tips on programmatic recovery from a power outage? Thanks in advance!

**Comment by Fishwaldo** [comment]
Try using the Manager::HasNodeFailed command when a node is reported dead and you know its online again. The results will come in as a Notification. This will trigger the Controller to retry.

To remove "Failed" or Ghost Nodes, use RemoveFailedNode (will only work if the Controller thinks its failed though). 

Other times, you need (with Battery powered devices) you need to "wake them up" before using the HasNodeFailed command. This is often via a button press or removing a cover. Consult the device manuals for that. 

In the future, please use our mailing list for questions.
