### ISSUE TITLE
Bug in the xml file for the GE ZW 6302 Motion Sensor

### ISSUE THREAD

**Issue by vivekparamdbk** [OpenZWave/open-zwave#2041]
Looks like this xml file (https://github.com/OpenZWave/open-zwave/blob/master/config/ge/zw6302.xml) has an issue with the range for PIR Timeout Duration.

The minimum and maximum are set to 0 and 1, respectively, but the documentation, and even the helptext in the document indicate that a range from 1-255 is accepted.

**Comment by petergebruers** [comment]
Config file updated! Thanks!
