### ISSUE TITLE
Update existing device id Fibaro fgs213 Switch

### ISSUE THREAD

**Issue by gbuktenica** [OpenZWave/open-zwave#2061]
I have an Australian Fibaro FGS213 reporting id 3000 and type 0403 and coming up as unknown.

Please add line 651 to manufacturer_specific.xml
```xml
<Product config="fibaro/fgs213.xml" id="3000" name="FGS213 Switch" type="0403"/>
```

**Comment by Fishwaldo** [comment]
Please see
https://github.com/OpenZWave/open-zwave/wiki/Adding-Devices
