### ISSUE TITLE
Popp 700793 available in config/popp but not in manufacturer_specific.xml 

### ISSUE THREAD

**Issue by HB787** [OpenZWave/open-zwave#2074]
Hi Team,

The Popp wallplug 700793 is available in the config/popp directory as 700793.xml but not in the manufacturer_specific.xml

Thanks in advance!

**Comment by Fishwaldo** [comment]
https://github.com/OpenZWave/open-zwave/wiki/Adding-Devices

PR's welcome

**Comment by petergebruers** [comment]
So if you want this to be added, please follow the instructions @Fishwaldo posted a while ago

https://github.com/OpenZWave/open-zwave/wiki/Adding-Devices

And please do not open a new issue with the same question... Doing that only creates "noise".

**Comment by petergebruers** [comment]
Fixed, PR #2098
