### ISSUE TITLE
(GE) JASCO ZW4101 Smart Wall Plug not recognized

### ISSUE THREAD

**Issue by apla2016** [OpenZWave/open-zwave#2075]
Please add to database (GE) JASCO ZW4101 Smart Wall Plug

**Comment by petergebruers** [comment]
Bad news, I cannot do that for you, I don't have one and the database is a "community effort". So the good new is... You can help us add it! Instructions are here:

https://github.com/OpenZWave/open-zwave/wiki/Adding-Devices
