### ISSUE TITLE
Missing Popp 700793 device in manufacturer_specific.xml

### ISSUE THREAD

**Issue by HB787** [OpenZWave/open-zwave#2097]
Team,

Although the device XML is available in the popp directory.
This row is missing in the manufacturer_specific.xml:

<Product config="popp/700793.xml" id="1002" name="700793 Smart Power Plug" type="0003"/>

This issue was added before and closed

**Comment by petergebruers** [comment]
Indeed, we expect the community to add them

**Comment by petergebruers** [comment]
So we were waiting on you to do that... But because nobody stepped in, a bot closed it...

**Comment by petergebruers** [comment]
You can comment on closed issues... And we can repoen issues... That is what I did... So to keep everything in one please I'll close this one.
