### ISSUE TITLE
FR: Add Zooz ZEN30 switch config.

### ISSUE THREAD

**Issue by aph3rson** [OpenZWave/open-zwave#2119]
The [ZEN30](https://www.thesmartesthouse.com/products/zooz-z-wave-plus-s2-double-switch-zen30-white-for-light-fan-combo) is a newer device from Zooz, and incorporates a dry-contact relay and dimmer into one body.

I'll be following the instructions in the wiki for adding devices, but wanted to open an issue to attach the PR to.

**Comment by Fishwaldo** [comment]
This is Done
