### ISSUE TITLE
[question] Device Association between secured and insecure

### ISSUE THREAD

**Issue by billiaz** [OpenZWave/open-zwave#2128]
I have two devices. One is securely included and the other insecure.

When I associate secure device to insecure (apply that on Insecure)

It seems like the insecure cannot control the secure

Is this a normal behaviour? ( protocol )

Devices are Fibaro Wall Plug Switches (FGWPE/F- 102 3.2 firmware)

I had the same issue when the Fibaro switch was securely included and Nodon is insecure

**Comment by Fishwaldo** [comment]
Thats not possible. All devices you want to associate together need to be either both Secure or Non-Secure.
