### ISSUE TITLE
AEON Labs ZW132 - Cannot find endpoint map to instance for Command Class COMMAND_CLASS_HAIL endpoint

### ISSUE THREAD

**Issue by Dulcow** [OpenZWave/open-zwave#2148]
Hi there,

I started to play with Z-Wave a few days ago but it does not work very well for me so far. I have an AEON Labs Gen5 Stick on a Raspberry Pi 3 B+ and an AEON Labs Dual Nano Switch to command some Wi-Fi lights via Home Assistant.

The electric setup does work perfectly (I can hear the relay clicking when use each switch). On Home Assistant side, things are unreliable and I noticed the following behaviour : the switch will not work if I haven’t used it for a while. When it starts reworking again, then it’s fine for a few minutes and then it stops again.

I browsed the logs from Open ZWave and I found the following errors (many occurrences):

```
2020-03-05 07:22:50.349 Error, Node002, Cannot find endpoint map to instance for Command Class COMMAND_CLASS_HAIL endpoint 1

2020-03-05 07:22:50.377 Error, Node002, Cannot find endpoint map to instance for Command Class COMMAND_CLASS_HAIL endpoint 2
```
Node002 being the Nano Switch. It looks to me like Open ZWave component does not know how to route the switch event. I tried to reboot and it keeps coming back. I have cleared out everything (remove all devices and configurations) and tried again. Same results.

What can I do to fix that?

[OZW_Log.txt](https://github.com/OpenZWave/open-zwave/files/4297617/OZW_Log.txt)

**Comment by Fishwaldo** [comment]
Check if you can configure the device to send something other than hail messages. It’s old, outdated and deprecated in the specifications
