### ISSUE TITLE
Aeotec Limited ZW175 Smart Switch 7 does not seem to be recognised properly

### ISSUE THREAD

**Issue by Dulcow** [OpenZWave/open-zwave#2149]
Hi,

I paired one of the Aeotec smart plug today and I noticed that the device wasn't recognised properly, despite being in the device database in OZW 1.6. I cannot access the ZWave parameters in Home Assistant.

![Screenshot_1](https://user-images.githubusercontent.com/34809515/76076478-4036e680-5f9f-11ea-85d9-d5bd0fbb5432.png)

![Screenshot_2](https://user-images.githubusercontent.com/34809515/76076479-41681380-5f9f-11ea-84cf-aaf36deac3e9.png)

Should I remove and reinclude the device? You can find the OZW logs below.

[OZW_Log.txt](https://github.com/OpenZWave/open-zwave/files/4297860/OZW_Log.txt)

**Comment by Fishwaldo** [comment]
Home assistant (native integration) uses forked version of OZW 1.4. You have to open your issue there.
