### ISSUE TITLE
Depreciate SetNodeOn/Off and related calls. 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [OpenZWave/open-zwave#215]
```
What steps will reproduce the problem?
1. MinOZW program with calls to SetNodeOn and SetNodeOff (see attachment)
2.
3.

What is the expected output? What do you see instead?
See the attached OZW_Log.txt file

What version of the product are you using? On what operating system?
OZW version r653 compiled on VS2010 under 32-bit Windows 7.

Please include the file OZW_Log.txt from your program. Make sure the file
zwcfg*.xml is NOT present.

Please provide any additional information below.


```

Original issue reported on code.google.com by `observ...@gmail.com` on 14 Apr 2013 at 9:05

Attachments:
- [OZW_Log.txt](https://storage.googleapis.com/google-code-attachments/open-zwave/issue-215/comment-0/OZW_Log.txt)
- [Main.cpp](https://storage.googleapis.com/google-code-attachments/open-zwave/issue-215/comment-0/Main.cpp)

**Comment by nihilus** [comment]
@Fishwaldo Any news on this?

**Comment by Fishwaldo** [comment]
SetNodeOn/Off and SetNodeLevel and SwitchAllOn/Off will be depreciated functions in 1.6 release. Its way to device specific, and almost impossible to support universally.

as mentioned above, ValueID's should be the "only" way you control a device. Its much more robust and flexible.

**Comment by Fishwaldo** [comment]
Marked as Depreciated already.
