### ISSUE TITLE
xml for Inovelli lzw30-sn looks wrong

### ISSUE THREAD

**Issue by kevinkahn** [OpenZWave/open-zwave#2155]
The config file for this device specifies specific labels for Top and Bottom button presses rather than using the default Scene labels.  It also seems to not allow multi-press above 2 (not as sure).  I edited a local copy to delete the command class 91 override in the xml file and this seems to make it now behave correctly regarding button taps.  Not sure if this is all that it needs.  There is an additional command item on that switch which is its configuration button which is supposed to also send a central scene command if used.  Since I'm not really knowledgeable about the configuration files I wasn't able to do anything about this. 

ETA: just tried the config button and with my mod it does indeed send a scene activation with "Scene 3" as its label.

**Comment by Fishwaldo** [comment]
Thanks
