### ISSUE TITLE
Fibaro Smoke sensor incorrect text for parameter 12

### ISSUE THREAD

**Issue by jvberlo** [OpenZWave/open-zwave#2159]
Hello,

For Firbaro device 'FGSD002 Smoke Sensor' is the configuration text for setting 12 incorrect.

Current text is:
BASIC OFF frame is sent in case of FIRE ALARM cancellation. Available settings: (1 - 99) or 255. Default setting: **255**

The default setting according the Fibaro site https://manuals.fibaro.com/smoke-sensor/

BASIC ON frame value
BASIC OFF frame is sent in case of FIRE ALARM cancellation. Its value is defined by the parameter.
Available settings: 0-99, 255
0 – turn off the device
1-99 – set the device to 1-99%
255 – set the last status
Default setting: **0**
Parameter size: 1 [byte]

**Comment by Fishwaldo** [comment]
Pull Request Welcome. 

https://github.com/OpenZWave/open-zwave/wiki/Adding-Devices
