### ISSUE TITLE
Possibility to log to stdout only

### ISSUE THREAD

**Issue by wilmardo** [OpenZWave/open-zwave#2160]
Related: #675

I am trying to get Zwave2MQTT as cloudnative as possible and one of the principles is just log to stdout. So I looked through the [configuration options](https://github.com/OpenZWave/open-zwave/wiki/Config-Options) but it seems that there are just three scenarios:
* No logging
* Logging to file
* Logging to file and console

But I want just logging to console, not to file :)

I think this is a useful feature is this era of containerization where stdout logging has become the norm.

**Comment by Fishwaldo** [comment]
Added to #2146
