### ISSUE TITLE
Node024 Door/Window Sensor Read Status Not working

### ISSUE THREAD

**Issue by T3rr0rByte13** [OpenZWave/open-zwave#2162]
Hi, Not really sure why the status is not reading, I open and closed the sensor 2 times in this log file after deleting ZWconfig
[Log.txt](https://github.com/OpenZWave/open-zwave/files/4364453/Log.txt)

**Comment by Fishwaldo** [comment]
>2020-03-21 17:46:07.347 Info, Node024, WARNING: ZW_SEND_DATA failed. No ACK received - device may be asleep.
2020-03-21 17:46:07.348 Info, Node024,   Node 24 has been marked as asleep
2020-03-21 17:46:07.348 Info, Node024, Node not responding - moving QueryStageComplete command to Wake-Up queue


Its sleeping - You need to wake it up after restarting your application.
