### ISSUE TITLE
26933-motion-dimmer.xml Association Group 2 and 3 have same label

### ISSUE THREAD

**Issue by Botched1** [OpenZWave/open-zwave#2166]
open-zwave/config/ge/26933-motion-dimmer.xml

Association groups 2 and 3 have the same label (this is actually truer on many of the GE device xml files, not just the one mentioned). This causes issues in zwave2mqtt, or any interface that uses the label for item enumeration, as you can't tell which "Basic Set"  association group is number 2 and which is number 3.

Request: Consider adding a prefix or suffix to the label to make it clear which is which.

**Comment by Fishwaldo** [comment]
This is a application related issue. Nothing todo with OZW. We provide API’s to iterate the group numbers and labels. It’s upto the application to determine the best way to present it to the user.

**Comment by robertsLando** [comment]
@Fishwaldo I think he means, there is an error on configuration file, there are 2 associatons group with the same name

**Comment by Fishwaldo** [comment]
It’s not strictly a error. 

Regardless, PR is welcome. I don’t have own this device, can’t test it and with over 900 devices in the database, I rely on the community to help maintain and update config files.

**Comment by Botched1** [comment]
> @Fishwaldo I think he means, there is an error on configuration file, there are 2 associatons group with the same name

I'm not really sure it is a bug, per se. This is from the zwave cert report. Notice it lists 2xbasic set association groups:
![image](https://user-images.githubusercontent.com/19985320/77440923-da2bcb00-6db6-11ea-9d9b-dd3547b6e244.png)

**Comment by robertsLando** [comment]
@Botched1 Find the config file here and submit a PR to fix that label please
