### ISSUE TITLE
Added Duco ventilation system

### ISSUE THREAD

**Issue by markvankemenade** [OpenZWave/open-zwave#2175]
I've created files for 2 Vero Duco products:

1. 
Manufacturer: Vero Duco, ID=0080
Product Type: 0003
Product ID: 0001
Product name: DucoBox Motor

2.
Manufacturer: Vero Duco, ID=0080
Product Type: 0004
Product ID: 0001
Product name: Ducotronic CO-RH sensor

I'll put the configuration files on the mailing list.

**Comment by Fishwaldo** [comment]
Please submit via Pull Requests.. We rely on the community to help maintain the databases.
