### ISSUE TITLE
Error compilig Open-Zwave on a Raspi 3

### ISSUE THREAD

**Issue by HubertusH** [OpenZWave/open-zwave#2186]
Hi,

i download the actual open-zwave 1.6 und try to compile it on a raspi 3. But on the sources of doorlock and doorlocklocking i get errors like this:

`Building DoorLockLogging.o
/home/pi/open-zwave-1.6/cpp/src/command_classes/DoorLockLogging.cpp: In member function ‘virtual bool OpenZWave::DoorLockLogging::HandleMsg(const uint8*, uint32, uint32)’:
/home/pi/open-zwave-1.6/cpp/src/command_classes/DoorLockLogging.cpp:277:13: error: ‘char* strncat(char*, const char*, size_t)’ output may be truncated copying between 0 and 253 bytes from a string of length 253 [-Werror=stringop-truncation]
      strncat(usercode, tmpusercode, sizeof(usercode) - strlen(usercode) - 1 );
      ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make[1]: *** [/home/pi/open-zwave-1.6/cpp/build/support.mk:153: /home/pi/open-zwave-1.6/.lib/DoorLockLogging.o] Fehler 1
make[1]: Verzeichnis „/home/pi/open-zwave-1.6/cpp/build“ wird verlassen
make: *** [Makefile:23: all] Fehler 2
`

Thanks for any help
br
Hubertus

**Comment by Fishwaldo** [comment]
This was fixed a long time ago. Please use the downloads from www.openzwave.com
