### ISSUE TITLE
Added Greenwave Reality 5 Port Plug

### ISSUE THREAD

**Issue by big-ted** [OpenZWave/open-zwave#2189]
Based on the OpenWave Greenwave 6 Port but for UK market

Manufacture: Greenwave Reality, ID 0099
Product Type: 0003
Product ID: 0003
Product Name: Greenwave 5 Port UK Socket

Configuration file on the mailing list.

**Comment by Fishwaldo** [comment]
Please submit via a Pull Request. We rely on the community to update our Database.
