### ISSUE TITLE
Setting zwave node parameter results in int16 overflow error

### ISSUE THREAD

**Issue by cjmjmartens** [OpenZWave/open-zwave#2190]
- Home Assistant release with the issue: 107.5
- Last working Home Assistant release (if known): Unknown
- Operating environment (Hass.io/Docker/Windows/etc.): Hass.io
- Integration causing this issue: I have a Fibaro FGS222 Relay Switch. I want to set parameter 4 and 5 of this node to 57000 to make sure that the relay switch is automatically switched off after 95 minutes. Trying to set a value of 57000 results in a failure and an error is logged. According to the manual, it must be possible to add values between 1 and 65535 are possible for this parameter. See the manual online: https://manuals.fibaro.com/content/manuals/en/FGS-222/FGS-222-EN-A-v1.1.pdf. Entering smaller values for this parameter is possible, however bigger values are not accepted and lead to this error. 

Who can help me to resolve this issue? Thanks in advance.

[OZW_Log.txt](https://github.com/OpenZWave/open-zwave/files/4523046/OZW_Log.txt)

**Comment by Fishwaldo** [comment]
This is a HA error and is not related to OZW. 

But the current z-wave integration is being depreciated in HA, and development is being directed to a new integration, so you will probably have to wait for that.
