### ISSUE TITLE
incorrect mapping: specific device driver vs Localization.xml

### ISSUE THREAD

**Issue by quinnhosler** [OpenZWave/open-zwave#2193]
While using a [Honeywell T6 Pro](https://github.com/OpenZWave/open-zwave/blob/master/config/honeywell/th6320zw2003.xml) with qt-openzwave it appears that the Celsius/Fahrenheit mapping (likely from here, though I'm not 100%) gives preference to Localization.xml instead of the device driver xml. Specifically, 0=Fahrenheit and 1=Celsius for the device driver, while the Localization page maps 0=Celsius and 1=Fahrenheit.

The effect of this is incorrect (opposite) units, which with homeassistant-zwave_mqtt causes temperatures to be >100F in Home Assistant.

**Comment by bmight** [comment]
I think I am also having this issue. Was this fixed? I am using zwave2mqtt (v4.0.6) and openzwave v1.6.0.
