### ISSUE TITLE
New devices - Fantem (Oomi) FT112 door/window and FT118 extender

### ISSUE THREAD

**Issue by jefft4** [OpenZWave/open-zwave#2198]
manufacturer_specific.xml additions:
    <Product config="oomi/ft112.xml" id="0070" name="FT112 Door-window sensor" type="0002"/>
    <Product config="oomi/ft118.xml" id="0076" name="FT118 Range extender 6" type="0004"/>

[Oomi April2020.zip](https://github.com/OpenZWave/open-zwave/files/4540829/Oomi.April2020.zip)

**Comment by Fishwaldo** [comment]
Please open a PR - We rely on the community to maintain the database.
