### ISSUE TITLE
New device - Namron LED Dimmer Z-Wave 200W

### ISSUE THREAD

**Issue by perwei** [OpenZWave/open-zwave#2206]
Hi

I'd like to have this device added to the repository. I've been in contact with the vendor Namron aka Elektroimportoren who told me the device is manufactured by Sunricher but with ManufacturerID 0438. I coudn't find any Sunricher product matching the dimmer in the Config/sunricher directory but I found a Namron product that looked quite like the one I bought at https://products.z-wavealliance.org/products/3797. When checking the Product Data specs in the XML file there was some discrepancies so I decided to try to create a config file myself based on the template, the vendor documentation and browsing some other configfiles.    

ManufacturerID: 0x0438
ProductTypeId: 0x0202
ProductID: 0x0002
ProductName: LED Dimmer Z-Wave 200W

In the config file I've used the same identifier as used in the z-wavealliance entry for the product.

I've tried the basic functionality, turning on/off, setting brightness which seems to work ok.

Per W.

[nmzc10.zip](https://github.com/OpenZWave/open-zwave/files/4567684/nmzc10.zip)

**Comment by Fishwaldo** [comment]
Thank you 
Few points:
1) Please run "make xmltest" to fix any issues next time
2) it would be good if you could have provided the documentation/pics etc
3) We prefer receiving this via Pull Requests - as the database is community maintained and I'm the only one actively working on this project.
