### ISSUE TITLE
FGDW002 Door Opening Sensor 2 (FIBARO System) not show open/close

### ISSUE THREAD

**Issue by poudenes** [OpenZWave/open-zwave#2208]
Hi All,

I have add  2 FGDW002 Fibaro Door Sensors in Zwave2MQTT with some other nodes as well.
They don't have any MQTT part to send OPEN/CLOSE

Fibaro:
FGDW-002(1)EU Ver. 32ZW5
Made in Poland S/N: 00073876
ER14250 1/2AA 3,6V

Openzwave 1.6.974

What can I do to let those 2 devices work correct?

In debug i see this line

When open
```
OpenZWave Info, Node099, Received Notification report (>v1): Type: Unknown (6) Event: Unknown (23) Status: true, Param Length: 0
```

When close
```
OpenZWave Info, Node099, Received Notification report (>v1): Type: Unknown (6) Event: Unknown (22) Status: true, Param Length: 0
```

**Comment by Fishwaldo** [comment]
Please update to the latest version of OZW (1.6.1xxx) - there was a fix related to not loading specific config files. (in this case, NotificationCCTypes.xml - Please check the log files at the start for messages about unable to load this file)

**Comment by poudenes** [comment]
@Fishwaldo Im so sorry, I solved the issue. The Path was not correct to config files:
Add this: "/etc/openzwave"

Removed the 2 sensors, add them again and got all the missing options.

Forgotten to post it here and close it myself.
