### ISSUE TITLE
Scene activation functionality always disabled (in domoticz using OpenZwave.)

### ISSUE THREAD

**Issue by skywalker1979** [OpenZWave/open-zwave#2209]
If using Zwave devices, (it's happening to me with fibaro dimmer2) and you try to enable the function "28. Scene activation functionality" the function stays disabled after being saved.

**Comment by Fishwaldo** [comment]
Logs Please. 

Its possible that the device is "newer" or "older" than what the config file is created for. If its older than the config file - its possible your version doesn't support this config variable, and you would need to consult with Fibaro

**Comment by skywalker1979** [comment]
After reinstalling Domoticz it's working.
