### ISSUE TITLE
[question] add device renames xml file.  is this a bug?

### ISSUE THREAD

**Issue by jaredgudnason** [OpenZWave/open-zwave#2210]
I have an Inovelli sensor which i had to manually add the manufacturer xml file for configuration options.
simple enough, i add to manufacturer_specific.xml, and copy the device xml file into the brand's sub folder.
what's super weird though, if i add a device of that type, it works, reads the file, but then renames the specific device file from file.xml to file.xml.1   
I have no idea why.  If i have to add another one, i have to rename the file (remove the .1) between every device. super weird, doesn't occur with any other device i know of.

suppose i should add, it's ozw 1.6.1105 running in the zwave2mqtt docker container.

**Comment by Fishwaldo** [comment]
This is the "auto update" function of the config files. If your revision of the config file is "lower" than what is available in the OZW repository then OZW will download the version. 

1) Check if your changes are already in the OZW repository - If so, then just let it autoupdate.
2) if its, not, when you make your changes, bump the revision number to something "high" so its doesn't get overwritten.
3) turn of auto update (not sure if your application supports that, but it can be disabled in the options.xml file).
