### ISSUE TITLE
Incorrect Config Parameters for Trane XR524

### ISSUE THREAD

**Issue by xannor** [OpenZWave/open-zwave#2216]
My Trane AC controller is, i believe, an XR524, and gets configured using the TZEMT524AA21MA config. The issue is that two of the configuration options are incorrect.

 Changing my thermostat from Run to Hold set config index 76 from 1 to 0, this is listed as the Fan Off Time in the XML. Setting it back to run changes 76 from 0 to 1. I believe this function is listed as index 132 in the config.

Also setting the thermostat to ESM (away) mode will change index  77 from 0 to 2 (it also sets this index to a few other values while it adjusts the low and high setpoints, but it settles on 2) turning off away sets it back to 0. This parameter is listed as 2nd Stage heat in the xml. I believe this function is in the config as index 25, but mine does not seem to set that value.

It seems most of these values are duplicated from the other two files, so I don't know if this is just an assumption that was made when these were created or if the 524 is different than the rest. How I found these values is by an old post for the home assistant community, I have verified that they work as suggested in that article.

https://community.home-assistant.io/t/trane-xr524-with-control-of-the-schedule-run-hold-esm-modes/94461

**Comment by Fishwaldo** [comment]
As I don't own this device, and our config database is mainly maintained by the community, please submit a Pull Request with the fixes outlines above. You can consult [here](https://github.com/OpenZWave/open-zwave/wiki/Adding-Devices) for more info.
