### ISSUE TITLE
Aeotec DoorBell 6 (ZW162)

### ISSUE THREAD

**Issue by matjoker** [OpenZWave/open-zwave#2242]
Hello,
On the OpenZwave console (from Domoticz), there's a list of parameters available that we can update for the ZW162 doorbell 6.
The first part of the list is defined in the xml config file and the update is working fine.
![image](https://user-images.githubusercontent.com/15871046/84275660-4fc64e00-aaff-11ea-9db9-b7a441cfc221.png)

The second part of the parameters are the most important (change tones and volumes) but are not part of the xml config file and after a "submit", changes are not applied.
![image](https://user-images.githubusercontent.com/15871046/84275804-84d2a080-aaff-11ea-8252-3566637dc5f7.png)

Thanks for your help.

Matthieu

**Comment by Fishwaldo** [comment]
That is a Domoticz issue. I believe they used a fork of ozwcp, but thats no longer maintained on our side so you will have to work with the domoticz people
