### ISSUE TITLE
Qubino ZMNHCD1 - Wrong pourcent & no Electricity consumption

### ISSUE THREAD

**Issue by m4dm4rtig4n** [OpenZWave/open-zwave#2257]
Hi, 

I have recently buy Qubino ZMNHCD1 and i use it with zwave2mqtt 3.3.0 but i :
* Don't receive current status (need to launch other command to recevieve current status)
* Electricity consumption stay to 0kw :/

At 113-1-8, i have this message : Over Load Detected.
have you idea why i receive this message ?

Thx

**Comment by Fishwaldo** [comment]
Please ensure the controller is added to the correct association groups (consult the product manual). 

OZW only reports what a device says - If you get that message, consult the device manual.
