### ISSUE TITLE
MCOhome FCU-thermostat

### ISSUE THREAD

**Issue by kostas2911** [OpenZWave/open-zwave#2267]
Manufacturer: McoHome Technology Co Ltd
Product Type: 0803
Product ID: 5102
Product Name: MH8-FC
[mco.zip](https://github.com/OpenZWave/open-zwave/files/4812373/mco.zip)

**Comment by Fishwaldo** [comment]
1) Please add a MetaData Block and Image file please (https://github.com/OpenZWave/open-zwave/wiki/Adding-Devices#creating-the-metadata-block)
2) there is several old 1.4 settings mixed in with 1.6. (eg,alttypeintepretation). Please consult the above link and https://github.com/OpenZWave/open-zwave/wiki/CommandClass-Compatibility-Flags for the correct way on 1.6.

**Comment by kostas2911** [comment]
Is this ok?
[mcofcu.zip](https://github.com/OpenZWave/open-zwave/files/4823936/mcofcu.zip)

**Comment by Fishwaldo** [comment]
Not really - But I fixed up a few things and commited it. Thanks!

**Comment by kostas2911** [comment]
Hi,

I think that there is an error on manufacturer_specific.xml. id should be 5102 not 3102

Also on mh8fceu0803.xml without below lines:

<CommandClass id="67" name="COMMAND_CLASS_THERMOSTAT_SETPOINT" version="2" innif="true" base="1" typeInterpretation="B">
	<Instance index="1" />
	<Value type="decimal" genre="user" instance="1" index="1" label="Heating 1" units="C" read_only="false" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="0" />
	<Value type="decimal" genre="user" instance="1" index="2" label="Cooling 1" units="C" read_only="false" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="0" />

i cannot set heat temperature

**Comment by kostas2911** [comment]
![image](https://user-images.githubusercontent.com/48488448/86903244-bc8d3200-c117-11ea-82ea-6cdd48214669.png)
![image](https://user-images.githubusercontent.com/48488448/86903283-cb73e480-c117-11ea-8007-67301eff945f.png)

**Comment by kostas2911** [comment]
There is an error on manufacturer_specific.xml. id should be 5102 not 3102
