### ISSUE TITLE
Add support for Schlage BE369.xml

### ISSUE THREAD

**Issue by tehspaceg** [OpenZWave/open-zwave#2270]
I know this is an ANCIENT issue, but I was able to use this BE369.xml (from the linked issue) on my HASS implementation running the OZW 1.4 version.

I added this to the manufacturer_specific.xml file under the Schlage section.

`<Product type="634b" id="5044" name="BE369 Z-Wave enabled lock" config="schlage/BE369.xml"/>`

I'm brand spanking new to the OZW world, so please let me know if I should do a new PR. I also have no idea if this will work on OZW 1.6.

_Originally posted by @tehspaceg in https://github.com/OpenZWave/open-zwave/pull/1598#issuecomment-648506501_

**Comment by Fishwaldo** [comment]
That config file is from 1.4 days. For 1.6 it needs to be updated as per https://github.com/OpenZWave/open-zwave/wiki/Adding-Devices (Metadata, images etc). 

Please update and post a new PR and I'll merge. (I don't own this device so someone that does needs to - and test it)
