### ISSUE TITLE
Barrier value doesn't support exact positions

### ISSUE THREAD

**Issue by kpine** [OpenZWave/open-zwave#2285]
Barrier Report::State supports a value that indicates the barrier is stopped at an exact position, with values 0x1 to 0x63. It is optional for devices to support this.

OZW [doesn't handle](https://github.com/OpenZWave/open-zwave/blob/0dba812c2568a59e1cbe9f06c84b5f1adbda3ccb/cpp/src/command_classes/BarrierOperator.cpp#L201) these values, it sets the value to "Unknown".

**Comment by Fishwaldo** [comment]
So (without looking) either thats part of a new CC version, or was never implemented in the first Version.

**Comment by kpine** [comment]
Probably not implemented in the first place, it's listed as part of V1. I don't actually own a device that supports this, but I was just poking around when reviewing the HA implementation of covers. Figured I'd log this bug in case it was ever needed, as position values 1-4% would collide with the current list indices 1-4 (i.e. a breaking change).
