### ISSUE TITLE
Namron LED Dimmer wrong ID and Type

### ISSUE THREAD

**Issue by lwalbert** [OpenZWave/open-zwave#2292]
Hi,

Namron device id and type seems to be swapped.
Device appears unknown.
in file: manufacturer_specific.xml
the ID and Type number should be swapped:
<Product config="namron/1402756.xml" id=**"0202"** type=**"0002"** name="LED Dimmer Z-Wave 200W"/>

to:
<Product config="namron/1402756.xml" id=**"0002"** type="**0202"** name="LED Dimmer Z-Wave 200W"/>

Br
Lennart

**Comment by Fishwaldo** [comment]
Thanks!
