### ISSUE TITLE
MCOHome A8-9 multisensor config file is outdated

### ISSUE THREAD

**Issue by Jofreathome** [OpenZWave/open-zwave#2301]
Hi, I have a MCOHome A8-9 multisensor EU version and it is not working as expected, for instance the PIR sensor is recognized as "General Sensor" and the Smoke sensor is recognized as "Smoke density" while they both are 0 or 1 sensors.
 ̷T̷h̷e̷ ̷V̷O̷C̷ ̷s̷e̷n̷s̷o̷r̷ ̷i̷s̷ ̷n̷o̷t̷ ̷r̷e̷c̷o̷g̷n̷i̷z̷e̷d̷ ̷a̷t̷ ̷a̷l̷l̷ ̷a̷s̷ ̷a̷ ̷s̷e̷n̷s̷o̷r̷.̷

Can someone investigate this and update the config file?
Regards,

**Comment by Fishwaldo** [comment]
I do not own these devices and the majority are contributed by the community, so you would need to investigate and make the changes to the config yourself. 

Information about the config format can be found here: https://github.com/OpenZWave/open-zwave/wiki/Adding-Devices
