### ISSUE TITLE
Can't change Send interval for ZW096 device

### ISSUE THREAD

**Issue by andrerod** [OpenZWave/open-zwave#2308]
Somewhat strange but cant' change the value of interval for a zw096 using ozwadmin. Not sure if it is an openzwave issue (device definition) or a ozwadmin issue though. 

Essentially, the UI doesnt tallow me to input any integer different than 0.

![Screen Shot 2020-07-12 at 12 07 32 PM](https://user-images.githubusercontent.com/457481/87254594-78ac6c80-c438-11ea-838c-7cd3bcb0c485.png)

**Comment by andrerod** [comment]
Was able to set this correctly via MQTT with the sendvalue api. So i think this is somehow a ozwadmin issue.

**Comment by kpine** [comment]
https://github.com/OpenZWave/ozw-admin/issues/33

**Comment by andrerod** [comment]
@kpine  yeah that seems to be the same issue. 

If it helps for any reader the workaround i did was:
- Open up MQTT Explorer
- Grab the valueidkey from the field definition in the instance node of the device node.
- Use the setvalue command which expects two fields in the payload: the valueidkey and the new value.
- Observe that openzwave replies with an ack / success response and prosper.

**Comment by andrerod** [comment]
Closing this here and this is being tracked, correctly, in ozw-admin.
