### ISSUE TITLE
Battery powered devices dead on startup

### ISSUE THREAD

**Issue by robertsLando** [OpenZWave/open-zwave#2312]
Many users are reporting me this problem on startup, someone says that after some hours they come back but still investigating on this. @Fishwaldo is something changed on the library that could cause this? 

Issues refrences:
https://github.com/OpenZWave/Zwave2Mqtt/issues/626#issuecomment-659356318

https://github.com/OpenZWave/Zwave2Mqtt/issues/11#issuecomment-658396747

**Comment by dick902** [comment]
For my case all devices included both battery or non-battary powered were dead.

**Comment by Fishwaldo** [comment]
https://github.com/OpenZWave/Zwave2Mqtt/issues/626#issuecomment-660485083
