### ISSUE TITLE
OpenZWave not (always) reporting back status when binary switch toggled

### ISSUE THREAD

**Issue by petertq** [OpenZWave/open-zwave#2335]
When turning on a switch in Home Assistant an MQTT message for updating the status is not always received.

When all goes well a message like this is sent from qt-openzwave:
`OpenZWave/1/node/11/instance/2/commandclass/37/value/189349920/ - {"Value":true,"CommandClass":"COMMAND_CLASS_SWITCH_BINARY"}`

But sometimes this message is missing. The relevant logging output is in [notok.txt](https://github.com/OpenZWave/open-zwave/files/5014921/notok.txt). A similar output when it works as expected is in [ok.txt](https://github.com/OpenZWave/open-zwave/files/5014928/ok.txt)

I've tried to compare them and [this](https://github.com/OpenZWave/open-zwave/files/5014934/diff.txt) is the diff output.

I upgraded to openzwave/ozwdaemon:latest yesterday(digest d530803f6e04, so it should be build 170). Not sure how it relates to OpenZWave versions.

Running docker on Ubuntu (64 bits) on an R-Pi 4.

Home Assistant version is 0.113.2, with a clone from the dev branch for OpenZWave (for dealing with the slow dimming problem - as suggested in the forum).

The switch is a Fibaro FGS223 Double Relay and the controller is a Z-Wave.Me USB Stick.

Please tell me if there's anything more I can provide to solve this problem!

And I hope it's not a hardware issue (or that I need to upgrade the firmware for the Fibaro switch);-). I don't think I had this problem with my old setup (with the Razberry controller hat).

Perhaps not relevant for this issue, but I'm getting a few critical logging messages now and then. And also some Node reports for non-existing nodes (like Node 0).

I've posted this issue in qt-openzwave, but I'm not sure whether the problem is related to the base OpenZWave or the wrapper.

Peter

**Comment by Fishwaldo** [comment]
Known Issue. Please follow #1321
