### ISSUE TITLE
Leviton DZ15S-1BZ switch not properly reporting target value

### ISSUE THREAD

**Issue by jeremyrea** [OpenZWave/open-zwave#2342]
### Known affected versions
1.6-1210-g6cf37295 with [qt-openzwave](https://github.com/OpenZWave/qt-openzwave) (docker build 170)
1.6-1240-g01c8d001 with [zwave2mqtt](https://github.com/OpenZWave/Zwave2Mqtt) v4.0.0

### Description
After toggling the switch on and back off, the switch is stuck being reported as on. When the switch returns to the Off state, the logs seem to be spammed awaiting for the target value to be attained.

### Steps to reproduce
Toggle switch to On, then Off (physically, via Home Assistant or MQTT using the reported _command_topic_)

### Expected Behaviour
Switch reports as being off

### Actual Behaviour
Switch reports as being on

### Steps already taken
- Exclude nodes from network
- Factory reset switches

### Attachments
[logs.zip](https://github.com/OpenZWave/open-zwave/files/5017320/logs.zip)

**Comment by Fishwaldo** [comment]
Known Issue. This is WIP. Please follow #1321
