### ISSUE TITLE
Many configuration parameters with type list are missing min and max values

### ISSUE THREAD

**Issue by kpine** [OpenZWave/open-zwave#2369]
According to the [wiki](https://github.com/OpenZWave/open-zwave/wiki/Adding-Devices#list-value-types), list types should specify a min and max value. There doesn't seem to any XML schema or test that verifies this.

Roughly 27% of all list config parameters are missing this value.
```
$ git grep 'Value.*genre=\"config\"' -- '*.xml' | grep 'type=\"list\"' | wc -l
2499

$ git grep 'Value.*genre=\"config\"' -- '*.xml' | grep 'type=\"list\"' | grep -E -v '(min.*max|max.*min)' | wc -l
688
```
Example:
https://github.com/OpenZWave/open-zwave/blob/01c8d001e5a4342313f34496bf1ab56849b461f4/config/aeotec/zw062.xml#L121

Can you clarify if the min and max values are a **requirement**?

**Comment by nechry** [comment]
The min max attributes are not required, but can help users to apply a supported value. But with list items not needed
