### ISSUE TITLE
Instance 1: Sensor (48-1-0) on a ZMNHDA2 Flush Dimmer (Qubino (Goap)) has ceased to work

### ISSUE THREAD

**Issue by besynnerlig** [OpenZWave/open-zwave#2376]
Running Zwave2Mqtt in docker compose (robertslando/zwave2mqtt:latest which is V 4.2) on Ubuntu. I [originally reported this issue](https://github.com/OpenZWave/Zwave2Mqtt/issues/690) on the Zwave2Mqtt repo but was recommended to start a new issue here instead.

```
 volumes:
      - /opt/zwave2mqtt/store:/usr/src/app/store
      - /opt/zwave2mqtt/openzwave:/usr/local/etc/openzwave
```

I had an issue recently that made me upgrade to the latest Zwave2mqtt, Doing that solved the problem but there's a new issue instead. Unfortunately I'm a newbie and I can't figure out how to solve the problem.

The binary input of my ZMNHDA2 Flush Dimmer doesn't work any longer. However I get 2 entries in the log every time I operate the switch connected to that input:

```
OpenZWave Warning, Node018, Received invalid MultiInstanceReport from node 18. Attempting to process as MultiChannel
OpenZWave Error, Node018, Received a MultiChannelEncap for endpoint 1 for Command Class 3, which we can't find

```

Trying to solve that, I downloaded  the latest open-zwave source and copied the config directory recursively into /opt/zwave2mqtt/openzwave. Doing that and restarting Zwave2mqtt didn't cause any new problems, nor did it solve the issue above. (Actually I don't even know how to properly update open-zwave on my docker container but I did what I thought was appropriate. I haven't been able to find any info on how to doing that.)

Any ideas where I should start looking? Thanks!

**Comment by Fishwaldo** [comment]
After updating config files, you need to remove ozwcache_*.xml files or issue a RefreshNodeInfo
