### ISSUE TITLE
Custom config file for GE 14280 causes crash

### ISSUE THREAD

**Issue by ljtilley** [OpenZWave/open-zwave#2378]
I’m in the process of transferring all of my zwave devices over from my smartthings hub directly to my HA instance and one of my devices is causing openzwave to crash. Here are the details of my setup:

Virtualized HA install using the qcow2 image
HA 0.114.4
OpenZWave addon 0.5.2
When I first set things up, almost everything worked properly. I have two inovelli dimmers that detected the proper config XML file and loaded fine. I also have a GE plug dimmer (14280) that doesn’t have a config file. It was detected and works for the most part, except for a known issue with SwitchMultiLevel devices.

To work around the SwithMultiLevel issue I did some digging and it looks like I need to either change some of the manufacturer specific device config options, or add the VerifyChanged device compatibilty flag in the openzwave config, so I set about creating a custom config file.

I based my config file off of a similar GE/Jasco plugin dimmer that was already included in openzwave 1.6. It looks to have the same configuration options, but my version has a couple extra association groups accoring to the z-wave alliance database entry for my 14280

The final config file is here: https://gist.github.com/ljtilley/28d337b302aa9599d56f372a36558595

I also added the appropriate line to the manufacturer_specific.xml file

To get it working I removed the plug from my existing network and removed the ozwcache file to make sure no previous settings were messing with things. When I re-add the dimmer, it properly detects the device and manufacturer IDs and matches them with the appropriate entry in manufacturer_specific.xml, but somewhere along the line when it tries to load the config file, it crashes the whole OpenZWave addon container.

At first I thought I had a malformed config file, so I tried first verifying the xml using the schema provided and everything checked out. Then I thought it might be something specific with the association groups or configuration entries, so I created a barebones file with just the metadata and it still caused openzwave to crash.

I’ve tried looking at the logs for errors, but I don’t really know enough about how devices get loaded to decipher the logs: https://gist.github.com/ljtilley/2c1bd5797cfcf465777317a647a3041f

I've also tried to do the log analyzer, but the login system for the web page doesn't seem to be working.

The Node for the GE dimmer in the logs about is Node 21

Any ideas why my GE plugin dimmer will work with no device config, but crashes every time I try to include even a basic config file with metadata only?

**Comment by Fishwaldo** [comment]
what docker image is this? The backtrace doesn't give anything usefull. Please try the qt-openzwave image if possible.
