### ISSUE TITLE
Qubino Flush Dimmer ZMNHDD1: parameter 249 (Enable/Disable Reporting on Set command) missing from config file

### ISSUE THREAD

**Issue by abey79** [OpenZWave/open-zwave#2400]
While adding Qubino Flush Dimmers (ZMNHDD1) in my network (via Home Assistant 0.115.2), I noticed that the parameter 249 (Enable/Disable Reporting on Set command) is missing from the configuration file:
<img width="1069" alt="image" src="https://user-images.githubusercontent.com/49431240/93883193-87898800-fce1-11ea-8a36-6120ea2dfc93.png">

It looks like it may solve the refresh issues I'm encountering (light level is not updated after a change despite being properly applied to the light). Is there a reason for this missing parameter?

**Comment by Fishwaldo** [comment]
Please submit a PR. The device database is maintained by the community.
