### ISSUE TITLE
Adding the European TZ67G version as an alias to TKB home TZ67 Dimmer plug

### ISSUE THREAD

**Issue by MNM-TB** [OpenZWave/open-zwave#2410]
The European version of the TKB home TZ67 dimmer plug has a different ID and type compared to the included version. This version is called TZ67G

When copying the line for the TZ67 but changing the id and type accordingly, everything works perfectly. All functionality of the dimmer plug is there. Here is the line:

```
<Product config="wenzhou/tz67.xml" id="0008" name="TZ67G Wall Plug Dimmer" type="0003"/>
```

It would be fantastic if you could include this in the next release. Thank you for the fantastic work everyone involved in OpenZWave!

**Comment by Fishwaldo** [comment]
Please open a PR. the device database is maintained by the community.
