### ISSUE TITLE
AEON Labs ZW090 Z-Stick Gen5 ZWave Plus Flag

### ISSUE THREAD

**Issue by Veldkornet** [OpenZWave/open-zwave#2436]
I have a [AEON Labs ZW090-C Z-Stick Gen5 EU](https://products.z-wavealliance.org/products/1355), which support ZWave Plus; however according to OZWAdmin, ZWave Plus is not enabled.

I am currently using the [OpenZWave of HomeAssistant](https://github.com/home-assistant/hassio-addons/tree/master/zwave)

![zw090](https://user-images.githubusercontent.com/10297361/97345341-36ddef80-188a-11eb-9ae7-1d27690321db.png)

![image](https://user-images.githubusercontent.com/10297361/97345697-ac49c000-188a-11eb-9fe6-ce913b2a9a94.png)

**Comment by kpine** [comment]
This is the current behavior for all Z-Wave Plus controllers. Controllers do not expose this flag the way other nodes do so it is no reported correctly.

This is a duplicate of #2129 and has already been fixed in the Dev branch. The fix will not be available until the next OZW 1.7 release.

**Comment by Veldkornet** [comment]
Ah okay, thanks!
