### ISSUE TITLE
manufacturer_specific.xml - type and id probably inverted for MHS314 (MCO Home) device

### ISSUE THREAD

**Issue by loomyr** [OpenZWave/open-zwave#2520]
Hi, 
When adding a MCO-Home MH-S314 switch, OZW was unable to detect it correctly : 

![image](https://user-images.githubusercontent.com/73883405/103287665-607ada80-49e3-11eb-80ce-7ac7a9270879.png)

After checking the "**_manufacturer_specific.xml_**" file I figured out that the type and the id of the MCO-Home MH-S314 might be inverted: 
https://github.com/OpenZWave/open-zwave/blob/776eeda3b571b5f82c77166a60878fa75eb5c499/config/manufacturer_specific.xml#L1229

Based on my device inclusion (attached picture above), I assume it should be referenced like that :

> `id="5102" name="MH-S314 Four-load" type="3141"`

Best Regards,
Vincent

**Comment by Hystersis** [comment]
I found the same inversion when updating the MH-S513 (see PR #2516).

**Comment by stuartwishart** [comment]
I found a similar issue with the MCO MH-S513 definition, see PR #2516
