### ISSUE TITLE
McoHome Technology Co Ltd, Roller Shutter Controller , 5102, C221 - unknown

### ISSUE THREAD

**Issue by Ascariota** [OpenZWave/open-zwave#2532]
The McoHome Technology Co Ltd is unknown in OpenZwave.

Name : Unknown: type=c221, id=5102
Manufacturer : Unknown: id=015f

In the past is unknow but work like a Roller Shutter but now work like a switch.
I have found the mhc221.xml

[https://gist.githubusercontent.com/adrianmo/88e9fd959f9a4cf0e0d01cb7787c518e/raw/06d4e80b7185b9cb50ee017e8da3fb118c371a17/mhc221.xml](url)

**Comment by rrozema** [comment]
As stated in the readme: if you want a device supported by openzwave, you can add it yourself. The instructions are in the [wiki](https://github.com/OpenZWave/open-zwave/wiki/Adding-Devices). You'll be helping yourself and others at the same time.
