### ISSUE TITLE
ZDB5100, config param 1 is actually a bitset

### ISSUE THREAD

**Issue by LordMike** [OpenZWave/open-zwave#2539]
The configs for the ZDB5100 (Logic soft) [indicates param 1 is a dropdown-list](https://github.com/OpenZWave/open-zwave/blob/dc843b6f3d7e5cb79828dc0be586b63b97510edd/config/logicsoft/ZDB5100.xml#L23-L30) of values to select. After consulting the manual, i see it's actually a bitset. 

Value 1 indicates Button 1, value 2 Button 2, and 3 is then Buttons 1 & 2. 

I don't know how to put this in the XML.. But here it is :)

**Comment by LordMike** [comment]
@nechry I think you copy-pasted once too many.

`id="1"` appears twice.

**Comment by nechry** [comment]
ho yes, I will fix
