### ISSUE TITLE
Can we get the Zooz Zen77 switches added to OZW?

### ISSUE THREAD

**Issue by peterbaker** [OpenZWave/open-zwave#2563]
Here are the parameters and values for the switch.
https://www.support.getzooz.com/kb/article/550-zen77-s2-dimmer-700-advanced-settings/

**Comment by nechry** [comment]
@peterbaker did you take a look on the Wiki https://github.com/OpenZWave/open-zwave/wiki/Adding-Devices for adding a new device?
If you can create the xml file this will be easy.

**Comment by peterbaker** [comment]
@nechry Ah great, I hadn't seen that. I'll give it a try.

**Comment by deiger** [comment]
@peterbaker please note that this is a Z-Wave 700 switch, so it will be supportable only in the next version of OpenZWave (v1.7).

**Comment by peterbaker** [comment]
> @peterbaker please note that this is a Z-Wave 700 switch, so it will be supportable only in the next version of OpenZWave (v1.7).

Oh crap, for real? It feels like I've been hearing about 1.6 becoming adopted "soon" for a couple of years, and now 1.7 is needed for a whole new set of stuff coming out? Any expectation that 1.7 will be incorporated into systems like Home Assistant any quicker than 1.6 was/is?

**Comment by deiger** [comment]
Now that HA is integrated with OpenZWave through an add-on, it should be fairly quickly, once 1.7 is rolled out. When that will be? #2570

**Comment by cybergrimes** [comment]
700 series devices should work just fine on OZW 1.6, I've got the Zooz ZEN34 remote switch working on 1.4 even

**Comment by blhoward2** [comment]
> Now that HA is integrated with OpenZWave through an add-on, it should be fairly quickly, once 1.7 is rolled out. When that will be? #2570

Uh, about that. The maintainer of ozw said he was taking a step back so HA changed its development path to focus on node-zwave-js.

**Comment by cybergrimes** [comment]
Zooz ZEN77 added in https://github.com/OpenZWave/open-zwave/pull/2581

The same config file can be edited to use with OZW 1.4 if necessary
