### ISSUE TITLE
BeNext Molite Sensor/Digital Home Systems DHS-ZW-SNMT-01 Multi Sensor - not working properly

### ISSUE THREAD

**Issue by GoogleCodeExporter** [OpenZWave/open-zwave#267]
```
What steps will reproduce the problem?
1.I added the sensor to the network using AEON LABS Z STICK 2 and I am using 
DomotiGa software
2.Them given that the MOLITE sensor was not recognized correctly and not 
showing the on/off for the presence, the temperature and the light situation I 
tried to do a configuration file for it(Molite.xml)


What is the expected output? 
All 3 parameters shown correctly.
What do you see instead?
 If I use the configuration file: I see just the on/off status that is not updated as I move in front of the sensor it is updated after 45 minutes as default(NOT AS SET IN CONFIGURATION FILE), the temperature and no light information. 
If I don't use the configuration file: I see the the light as 30 with not 
updating and the status stays off no matter what. 

What version of the product are you using? On what operating system?
BeNext Molite
UBUNTU 13.10
DomotiGa last version




```

Original issue reported on code.google.com by `ckbsm...@gmail.com` on 5 Feb 2014 at 12:55

Attachments:
- [manufacturer_specific.xml](https://storage.googleapis.com/google-code-attachments/open-zwave/issue-267/comment-0/manufacturer_specific.xml)
- [Molite.xml](https://storage.googleapis.com/google-code-attachments/open-zwave/issue-267/comment-0/Molite.xml)
- [OZW_Log.txt](https://storage.googleapis.com/google-code-attachments/open-zwave/issue-267/comment-0/OZW_Log.txt)
- [molitesensor.pdf](https://storage.googleapis.com/google-code-attachments/open-zwave/issue-267/comment-0/molitesensor.pdf)

**Comment by RKnol** [comment]
Just to let you know: The BeNext DHS-ZW-SNMT-01 Multi Sensor are still not working as it should. 

The devices are recognized as it should, but upon first poll the temp, lux and power are no longer responding. BeNext support told me to enable polling, which gave me the result that temp, lux and power were working as it should but motion is no longer responding. 

Tested on Domoticz v3.5510

Best,

Richard
