### ISSUE TITLE
COMMAND_CLASS_CENTRAL_SCENE

### ISSUE THREAD

**Issue by GoogleCodeExporter** [OpenZWave/open-zwave#367]
```
What steps will reproduce the problem?
1. Use the BeNext Scene Controller 
(http://www.benext.eu/en/products/scene-controller/)

What is the expected output? What do you see instead?
Activate a scene when pushing a button

What version of the product are you using? On what operating system?
Rev 903 on linux

What branch of the code were you using? (if you just followed the
instructions on the source checkout page, then say trunk.. if you checked
out a branch, please let us know what branch it was)
Trunk

Please include the file OZW_Log.txt from your program. Make sure the file
zwcfg*.xml is NOT present.

Please provide any additional information below.

Hello,
It seems that the command class 0x5b is not supported.
Log message: ApplicationCommandHandler - Unhandled Command Class 0x5b

The node is Node018

Thanks you !
```

Original issue reported on code.google.com by `tmartine...@gmail.com` on 17 Sep 2014 at 12:30

Attachments:
- [OZW_Log.log](https://storage.googleapis.com/google-code-attachments/open-zwave/issue-367/comment-0/OZW_Log.log)

**Comment by nechry** [comment]
hello the new Fibaro SWIPE also use this CC. Any news about possible support for this CC ?

**Comment by ehallq** [comment]
I will help in anyway I can, just tell me what you want. What data do you want from the OZW log, when adding the device and when pressing a button? :)

I got the ZRC-90EU

**Comment by ehallq** [comment]
Hi found this on a other forum, two post that i think might help :)
`So I've been playing recently with a pretty nifty 8-button Z-Wave controller that complies to the central scene command class. Indigo doesn't support it yet, but I'm keen to demonstrate it and try it out in my own house and show it off to some clients.

Indigo does add the device and does log the Z-Wave responses and requests. Indigo does request, interpret, and display the battery level status. As for button presses, button held down, button double clicks, etc, it just spits out the Z-Wave requestReply coming from the controller such as:

Single click:
RCVD requestReply1: 01 0B 00 04 00 03 05 5B 03 76 00 01 D9 (hex)

Byte 6 is the device number, 0x03 in this case.
Byte 12 is the button number, 0x01 in this case.
Byte 10 is the level, 0x76 in this case (up from 0x75) (decimal 118)
Byte 11 is the type of press, with 0x0 being a single click. 

Double click:
RCVD requestReply1: 01 0B 00 04 00 03 05 5B 03 79 03 01 D5 (hex)

Byte 11 is 0x03

Button held-down:
RCVD requestReply1: 01 0B 00 04 00 03 05 5B 03 7A 02 01 D7 (hex)
.
.
RCVD requestReply1: 01 0B 00 04 00 03 05 5B 03 81 02 01 2C (hex)
RCVD requestReply1: 01 0B 00 04 00 03 05 5B 03 82 02 01 2F (hex)
.
.
RCVD requestReply1: 01 0B 00 04 00 03 05 5B 03 83 01 01 2D (hex)

Byte 11 is 0x02 when held down
When released, byte 11 changes to 0x01, marking the end of the user's intention.


What I think would work:
Turn on Z-Wave debug logging
Use SQL Logger plug-in and ensure that event log entries are stored in the database
Use an external python script that monitors the sqlite db.
Whenever the script detects changes, it checks to see if any of the above are present. Obviously I will need to account for different device numbers and button numbers. Then it matches it to some pre-defined action group and executes it via the REST API.

This is basically a quick idea I've had and will most likely go ahead and try to implement it sometime this week after work. If anyone thinks it's off or there's a better way, do let me know please.

What would be awesome is if Indigo allowed us to define our own device files, etc for unknown/unsupported Z-Wave devices.`


`It's a Remotec ZRC-90 (called ZRC-80 in CES 2015: https://www.youtube.com/watch?v=kPxrVxFjbaQ).

Event log as follows:

Z-Wave Syncing - started for device "003 - Portable Remote Controller"
Z-Wave Debug SENT getNodeNeighbors: 01 06 00 80 03 01 01 7A
Z-Wave Debug RCVD getNodeNeighbors: 01 20 01 80 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 5E
Z-Wave Debug . . getNodeNeighbors: nodeId 003, neighbors: - none -
Z-Wave Syncing - retrieved module neighbors list: - none -
Z-Wave Debug SENT requestNodeInfo: 01 06 00 60 03 04 F3 6D
Z-Wave Debug RCVD requestNodeInfo: 01 16 00 49 84 03 10 01 01 01 5E 85 72 84 86 80 73 59 5A 5B EF 5B 84 06
Z-Wave Debug . . requestNodeInfo: node 003, combined class list: 20v1 80v1 84v1 85v1 86v1 72v1 73v1 59v1 5Av1 5Bv1 5Ev1
Z-Wave Debug SENT requestManufactureInfo: 01 09 00 13 03 02 72 04 05 F4 63
Z-Wave Debug RCVD requestManufactureInfo: 01 0E 00 04 00 03 08 72 05 52 54 00 01 85 10 1B
Z-Wave Debug . . requestManufactureInfo: node 003, manufacturerId 5254, productId 00018510
Z-Wave Debug . . requestManufactureInfo: Remotec, Portable Remote Controller
Z-Wave Syncing - retrieved manufacture and model names: Remotec - 5254, Portable Remote Controller - 00018510
Z-Wave Debug SENT requestVersInfoGen: 01 09 00 13 03 02 86 11 05 F5 83
Z-Wave Debug RCVD requestVersInfoGen: 01 11 00 04 00 03 0B 86 12 02 04 05 01 00 03 01 00 06 70
Z-Wave Debug . . requestVersInfoGen: node 003, protoVers 4.05, appVers 1.00
Z-Wave Syncing - retrieved protocol version 4.05, app version 1.00
Z-Wave Debug RCVD packet: 01 05 00 13 F5 00 1C (hex)
Z-Wave Debug RCVD requestVersInfoGen: 01 11 00 04 00 03 0B 86 12 02 04 05 01 00 03 01 00 06 70
Z-Wave Debug RCVD packet: 01 05 00 13 F5 01 1D (hex)
Z-Wave Debug RCVD requestVersInfoGen: 01 11 00 04 00 03 0B 86 12 02 04 05 01 00 03 01 00 06 70
Z-Wave Debug SENT requestVersInfoCmdClass: 01 0A 00 13 03 03 86 13 84 05 F6 04
Z-Wave Debug RCVD requestVersInfoCmdClass: 01 0A 00 04 00 03 04 86 14 84 02 E2
Z-Wave Debug . . requestVersInfoCmdClass: node 003, class command 84 using version 2
Z-Wave Debug . . requestVersInfoCmdClass: node 003, combined class list: 20v1 80v1 84v2 85v1 86v1 72v1 73v1 59v1 5Av1 5Bv1 5Ev1
Z-Wave Syncing - retrieved class hierarchy: Controller : Portable Controller : Portable Remote Controller (01 : 01 : 01, base 00)
Z-Wave Syncing - retrieved command classes: 20v1 80v1 84v2 85v1 86v1 72v1 73v1 59v1 5Av1 5Bv1 5Ev1
Z-Wave Debug SENT requestWakeInterval: 01 09 00 13 03 02 84 05 05 F7 97
Z-Wave Debug RCVD requestWakeInterval: 01 0C 00 04 00 03 06 84 06 00 00 00 01 71
Z-Wave Debug . . requestWakeInterval: node 003, interval 0 minutes, wakeTarget 001
Z-Wave Syncing - retrieved wake interval of 0 minutes
Z-Wave Debug SENT setWakeInterval: 01 0D 00 13 03 06 84 04 00 0E 10 01 05 F8 86
Z-Wave Syncing - device "003 - Portable Remote Controller" wake interval changed to 60 minutes
Z-Wave Debug SENT requestAssociationGroupCount: 01 09 00 13 03 02 85 05 05 F9 98
Z-Wave Debug RCVD requestAssociationGroupCount: 01 09 00 04 00 03 03 85 06 01 70
Z-Wave Debug . . requestAssociationGroupCount: node 003, group count: 1
Z-Wave Debug SENT requestAssociations: 01 0A 00 13 03 03 85 02 01 05 FA 9F
Z-Wave Debug RCVD requestAssociations: 01 0C 00 04 00 03 06 85 03 01 01 00 01 75
Z-Wave Debug . . requestAssociations: node 003, group: 1, num associations: 1, max associations: 1, replies left: 0
Z-Wave Debug . . requestAssociations: node 003, group: 1, associations: [1]
Z-Wave Syncing - retrieved group 1 associations: [1]
Z-Wave Syncing - group 1 association to interface already exists (skipping)
Z-Wave Debug SENT requestBatteryLevel: 01 09 00 13 03 02 80 02 05 FB 98
Z-Wave Debug RCVD requestBatteryLevel: 01 09 00 04 00 03 03 80 03 46 37
Z-Wave Debug . . requestBatteryLevel: node 003, level 70
Z-Wave Syncing - retrieved battery level of 70%
Z-Wave Syncing - complete
Z-Wave Debug SENT requestBatteryLevel: 01 09 00 13 03 02 80 02 05 FC 9F
Z-Wave Debug terminatingSyncUI
Z-Wave Debug RCVD requestBatteryLevel: 01 09 00 04 00 03 03 80 03 46 37
Z-Wave Debug . . requestBatteryLevel: node 003, level 70
Z-Wave received "003 - Portable Remote Controller" status update battery level 70%
Z-Wave Debug SENT goToSleep: 01 09 00 13 03 02 84 08 04 FD 91
Z-Wave Debug RCVD packet: 01 05 00 13 FD 00 14 (hex)
Z-Wave Debug RCVD requestBatteryLevel: 01 09 00 04 00 03 03 80 03 46 37
Z-Wave Debug . . requestBatteryLevel: node 003, level 70
Z-Wave received "003 - Portable Remote Controller" status update battery level 70%`

**Comment by michapr** [comment]
Any idea when it can be added in code? ZRC-90 use central scene only - can not be used with OZW just now... 
Command class will be added soon?

`2016-05-11 13:56:45.460 Detail, Node090,   Received: 0x01, 0x0b, 0x00, 0x04, 0x00, 0x5a, 0x05, 0x5b, 0x03, 0xcd, 0x00, 0x01, 0x3b`
`2016-05-11 13:56:45.461 Detail,`
`2016-05-11 13:56:45.463 Info, Node090, Received Central Scene set from node 90: scene id=1 in 0 seconds. Sending event notification.`
`2016-05-11 13:56:45.464 Warning, Node090, No ValueID created for Scene 1`
`
2016-05-11 13:56:47.706 Detail, Node090,   Received: 0x01, 0x0b, 0x00, 0x04, 0x00, 0x5a, 0x05, 0x5b, 0x03, 0xce, 0x00, 0x02, 0x3b`
`2016-05-11 13:56:47.708 Detail,`
`2016-05-11 13:56:47.709 Info, Node090, Received Central Scene set from node 90: scene id=2 in 0 seconds. Sending event notification.`
`2016-05-11 13:56:47.712 Warning, Node090, No ValueID created for Scene 2`


Thanks,
Michael

**Comment by Fishwaldo** [comment]
I have no device to test/develop against, and this CC requires a different approach to what we normally do with most CC's... so no progress till I get a device.

**Comment by michapr** [comment]
write me a PM / mail with your postal address - I will check how to send to you a sample ;)

Best regards
Michael

**Comment by nechry** [comment]
I can also send you device sample like Fibaro Swipe. I just wait a postal address

**Comment by ehallq** [comment]
Did you get a device @Fishwaldo  ? :)

**Comment by Fishwaldo** [comment]
@michapr I'd love too, but I honestly don't see any PM/contact options on Github... :)
@nechry Ill resend
@ehallq not yet.

**Comment by nechry** [comment]
We jeedom, you will reach a Swipe soon as possible. I'm waiting for your answer.

**Comment by michapr** [comment]
@Fishwaldo, sorry forgot that there is no PM in Github ;)
Have added contact mail in profile.

**Comment by nrd2001** [comment]
Has any progress been made on this? I stupidly bought the fibaro swipe before making sure it worked with openzwave

**Comment by nechry** [comment]
At this time you can only use it in direct association.

**Comment by turbokongen** [comment]
Is it possible to make it issue a notification over the network like the scene does? The logs say sending notificatouon but no notification appears in log. It will be alot more useful.

**Comment by philk** [comment]
Looks like OpenHAB [got this working](https://github.com/openhab/openhab/pull/4431/files) (and on the specific switch I want too, the HS-WD100). Hoping maybe their implementation is useful for getting this into OpenZwave.

**Comment by nechry** [comment]
The Aeon Labs ZW130 WallMote also require this CC

**Comment by michapr** [comment]
Seems that Fibaro Button FGPB-101 also require this CC

have tested it, but does not work in OZW

`            <CommandClass id="91" name="COMMAND_CLASS_CENTRAL_SCENE" version="1" request_flags="4" innif="true" scenecount="0">`
`                <Instance index="1" />`
`                <Value type="int" genre="system" instance="1" index="0" label="Scene Count" units="" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="-2147483648" max="2147483647" value="0" />`
`            </CommandClass>`

**Comment by mainx07** [comment]
I bought the HS-WD100 and then realized this was needed for the double/triple tap functions. Hoping for support on this.

**Comment by leeroymeile** [comment]
I bought a WALLC-S Zwave.Me wall controller that uses central scenes. Hope it gets supported very soon

**Comment by Fishwaldo** [comment]
some work on this is being done in #993

**Comment by tchellomello** [comment]
I got one ZRC-90 as well and please let me know any tests or logs you need. 

Thanks guys

**Comment by sayegh** [comment]
We have modified CentralScene.cpp to dynamically create a value for a given button. Not sure if this is the way to go, but it works for us - here's the file (base 1.4.1):

**Comment by KptnKMan** [comment]
I also have an apparently unusable Fibaro Button FGPB-101.
Running OZW 1.4.2279
Happy to test anything.

**Comment by variousred** [comment]
Ineed this to get my HS-WD100+ switch working with scenes as well :D

**Comment by variousred** [comment]
@sayegh With your `CentralScene.cpp` i still get 
` Warning, Node003, No ValueID created for Scene 1`

**Comment by sayegh** [comment]
@variousred Could you post the entire log block? (All surrounding stuff about Node003?)

Unfortunately we cannot get our hands on a HomeSeer HS-WD100+, and even if, it probably runs on US frequency anyway.

**Comment by variousred** [comment]
@sayegh  I will post this when i get home this evening.

**Comment by domlen** [comment]
Hi all, just came across the same issue while trying to get a **Popp 009303 Battery Wall Controller** to work with Home Assassinate and OZW. It's correctly recognized in the OZWCP and I added a Screenshot of the current settings:  ![screenshot 2016-12-13 22 37 30](https://cloud.githubusercontent.com/assets/2361464/21160320/be91c318-c184-11e6-942a-a44b648ae606.png)

This is what I get in the OZWCP while pressing button 1 and then button 3:
`2016-12-13 22:38:50.133 Detail, Node004,   Received: 0x01, 0x0b, 0x00, 0x04, 0x00, 0x04, 0x05, 0x5b, 0x03, 0xd0, 0x00, 0x01, 0x78
2016-12-13 22:38:50.134 Detail,
2016-12-13 22:38:50.135 Info, Node004, Received Central Scene set from node 4: scene id=1 in 0 seconds. Sending event notification.
2016-12-13 22:38:50.136 Warning, Node004, No ValueID created for Scene 1
2016-12-13 22:38:54.335 Detail, Node004,   Received: 0x01, 0x0b, 0x00, 0x04, 0x00, 0x04, 0x05, 0x5b, 0x03, 0xd1, 0x00, 0x03, 0x7b
2016-12-13 22:38:54.337 Detail,
2016-12-13 22:38:54.337 Info, Node004, Received Central Scene set from node 4: scene id=3 in 0 seconds. Sending event notification.
2016-12-13 22:38:54.338 Warning, Node004, No ValueID created for Scene 3`

For me this looked quiet promising, since I have a get an ID and it said that an event notification will be send. But in Home Assistent and the OZW_Log.txt the following happens:
`016-12-13 22:04:41.540 Detail, Node004,   Received: 0x01, 0x0b, 0x00, 0x04, 0x00, 0x04, 0x05, 0x5b, 0x03, 0xba, 0x00, 0x01, 0x12
2016-12-13 22:04:41.540 Detail, 
2016-12-13 22:04:41.540 Info, Node004, ApplicationCommandHandler - Unhandled Command Class 0x5b
`

I'm very new to the whole ZWave thong and I just wanted to share my finding. Maybe they can help you. 
I'm happy to test or answer anything - just let me know!

**Comment by sayegh** [comment]
Okay, another try for Nodon Soft Remote. Try to add this to your configuration file for the device:

```xml
<CommandClass id="91" name="COMMAND_CLASS_CENTRAL_SCENE" version="1" request_flags="4" innif="true" scenecount="0">
        <Instance index="1" />
        <Value type="int" genre="system" instance="1" index="0" label="Scene Count" units="" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="-2147483648" max="2147483647" value="0" />
        <Value type="int" genre="user" instance="1" index="1" label="Button Bullet" units="" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="-2147483648" max="2147483647" value="0" />
        <Value type="int" genre="user" instance="1" index="2" label="Button Plus" units="" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="-2147483648" max="2147483647" value="0" />
        <Value type="int" genre="user" instance="1" index="3" label="Button Circle" units="" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="-2147483648" max="2147483647" value="0" />
        <Value type="int" genre="user" instance="1" index="4" label="Button Minus" units="" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="-2147483648" max="2147483647" value="0" />
</CommandClass>
```

If you don't have a config file yet, look here:
https://github.com/jeedom/plugin-openzwave/blob/master/ressources/openzwave/config/nodon/crc360xSofremote.xml

**Comment by KptnKMan** [comment]
@sayegh Could you provide any details or instructions on how you were able to configure this?

I'm still trying to configure my Fibaro Button FGPB-101, and I'd really like to find out how to get it working.

**Comment by sayegh** [comment]
@KptnKMan It's a file in the OZW config directory. You need access to the file system; anyway, I obviously don't know the location of the config directory on your system.
Once you're there, follow this thread (and probably make above changes):
https://github.com/OpenZWave/open-zwave/issues/755

**Comment by KptnKMan** [comment]
@sayegh I found the file that is used on my system, and I'm pretty sure it reflects as this file:

https://github.com/jeedom/plugin-openzwave/blob/master/ressources/openzwave/config/fibaro/fgpb101.xml

Is there anything I can provide to provide debug or info?

**Comment by nechry** [comment]
for your record files in this folder: https://github.com/jeedom/plugin-openzwave/tree/master/ressources are no more updated. It's a obsolete folder.

**Comment by KptnKMan** [comment]
@nechry Thanks, I have compared the version of [fgpb101.xml](https://github.com/jeedom/plugin-openzwave/blob/master/ressources/openzwave/config/fibaro/fgpb101.xml) to my local version, which I believe it the latest version shipped with HA+OZW:
/srv/hass/src/python-openzwave/openzwave/config/fibaro/fgpb101.xml

They appear to be identical, does this mean that there is another issue with setting scenes?

@sayegh 
Noted above is my config directory, the file was already included there.

I'm just trying to get this button working correctly, so that I can configure scenes using it.

Any help would be greatly appreciated.

**Comment by sayegh** [comment]
@KptnKMan So we tried the Fibaro button, and apparently OZW sees it and provides a scene value when the button is pressed. 
However, the scene values do not match what I understood from the spec so far, they are 4 digit integers and not these 1...7 values mentioned above. 
No issue for us, since we are developing the gateway software and can easily adapt to any values, but I can imagine other software having issues with these values. Note, this is my first impression, and it's not impossible I got it all wrong. :-)

**Comment by ZyberSE** [comment]
I just bought The Button without doing any research before hand (stupid...), can I get it working somehow (not assigning it to another z-wave actor directly).

**Comment by nechry** [comment]
we do some work in a beta branch:
https://github.com/jeedom/plugin-openzwave/blob/beta/resources/python-openzwave/openzwave/cpp/src/command_classes/CentralScene.cpp
and the results are quite good.

**Comment by ZyberSE** [comment]
@nechry thank you for your reply. Would I be able to check out a beta version of your implementation, build it and run it just as the main version? I'm using it in my Home-Assistant.io setup and are looking for ways to have simple, physical buttons to manually trigger some stuff.
If I could get it working before the v1.6 release I would be super happy =)

**Comment by nechry** [comment]
Replace your actual .cpp and .h for the CentralScene and rebuild the library. We actually do other tweeting on driver, node but it's in alpha. So the safe way to try is just take the CC CentralScene from jeedom branch.

**Comment by philk** [comment]
I'm using that branch with home-assistant and it's fine. python-openzwave has some complaints and Hass doesn't see the scene events but it doesn't break anything. I'm using a god awful hack (tailing the ozw_log via a script) to trigger actions based on scenes for now.

**Comment by luukengelen** [comment]
Hi, Can anyone tell me how to include these .cpp files to homeassistant? I have build a new library, but i don't know how this is used in homeassisatant.

**Comment by KptnKMan** [comment]
Hi, is anyone able to provide some instructions for those of us who would like to test?

Seems like a good idea. :+1:

**Comment by insafjebara** [comment]
Hi all,
I have nodon soft remote and the only values i'm getting are: basic, level, bright, dim, ignore start level, start level, switch all and scene count. In my zwcfg I can see the Scene Id , key attributes ... 
I have changed the CentralScene.cpp.
How can I assign actions to buttons if I can't access the sceneId of each button ? 

Thank you.

**Comment by insafjebara** [comment]
hello everyone,

I am using Nodon soft remote and when I launch the application (MinOZW) I only get this, knowing that I used the in patch #1125 for CentralScene.cpp : 
NodeID: 13 
 	 ValueLabel: Basic 
		 ValueType: 1 
		 ValueUnits:  
		 ValueMin: 0 
		 ValueMax: 255 
------------------------------------------------------------
	 ValueLabel: Level 
		 ValueType: 1 
		 ValueUnits:  
		 ValueMin: 0 
		 ValueMax: 255 
------------------------------------------------------------
	 ValueLabel: Bright 
		 ValueType: 8 
		 ValueUnits:  
		 ValueMin: 0 
		 ValueMax: 0 
------------------------------------------------------------
	 ValueLabel: Dim 
		 ValueType: 8 
		 ValueUnits:  
		 ValueMin: 0 
		 ValueMax: 0 
------------------------------------------------------------
	 ValueLabel: Ignore Start Level 
		 ValueType: 0 
		 ValueUnits:  
		 ValueMin: 0 
		 ValueMax: 0 
------------------------------------------------------------
	 ValueLabel: Start Level 
		 ValueType: 1 
		 ValueUnits:  
		 ValueMin: 0 
		 ValueMax: 255 
------------------------------------------------------------
	 ValueLabel: Switch All 
		 ValueType: 4 
		 ValueUnits:  
		 ValueMin: 0 
		 ValueMax: 0 
------------------------------------------------------------
	 ValueLabel: Scene Count 
		 ValueType: 3 
		 ValueUnits:  
		 ValueMin: -2147483648 
		 ValueMax: 2147483647 

how can I use the scenes to make use of the remote ? how do I access sceneIDs ? do I have to create scenes through the manager ? 
I am able to see this line when I press a button:
"Node013, Received Central Scene set from node 13: scene id=2 with key Attribute 2. Sending event notification."
any help please ?  
Thank you

**Comment by IvanSurovegin** [comment]
Hello!
I am using ZME_KFOB (4 buttons) with latest release of openzwave (1.4.164) and initially got a problem with CentralScene support which is fixed by the patch 
https://github.com/OpenZWave/open-zwave/pull/1125#issuecomment-294678280

With this patch ZME_KFOB can be succesfully used with one exception: if we restart host (controller power off/on, library is started from scratch), the library doesn't react on KFOB keys pressing and 
just shows a report about not handled CC (full log is in attached problem_report.txt):
2018-06-06 08:32:27.597 Info, Node004, ApplicationCommandHandler - Unhandled Command Class 0x5b

I haven't found any info about such problem - only this topic. Changes in XML (as above) didn't help.
I have checked the code around the place of the info message and prepared a small fix which helped me, 
problem_report_solution.txt shows how it works now.

My patch is attached. Probably it is not so correct from the library point of view but works and probably helps somehow somebody.
Also i am interested in oppinion of the library developes on the problem and on the fix.
Thanks!
[problem_report.txt](https://github.com/OpenZWave/open-zwave/files/2076152/problem_report.txt)
[problem_report_solution.txt](https://github.com/OpenZWave/open-zwave/files/2076153/problem_report_solution.txt)
[problem_patch.txt](https://github.com/OpenZWave/open-zwave/files/2076154/problem_patch.txt)

**Comment by Fishwaldo** [comment]
> Hello!
> I am using ZME_KFOB (4 buttons) with latest release of openzwave (1.4.164) and initially got a problem with CentralScene support which is fixed by the patch
> [#1125 (comment)](https://github.com/OpenZWave/open-zwave/pull/1125#issuecomment-294678280)
> 
> With this patch ZME_KFOB can be succesfully used with one exception: if we restart host (controller power off/on, library is started from scratch), the library doesn't react on KFOB keys pressing and
> just shows a report about not handled CC (full log is in attached problem_report.txt):
> 2018-06-06 08:32:27.597 Info, Node004, ApplicationCommandHandler - Unhandled Command Class 0x5b
> 
> I haven't found any info about such problem - only this topic. Changes in XML (as above) didn't help.
> I have checked the code around the place of the info message and prepared a small fix which helped me,
> problem_report_solution.txt shows how it works now.
> 
> My patch is attached. Probably it is not so correct from the library point of view but works and probably helps somehow somebody.
> Also i am interested in oppinion of the library developes on the problem and on the fix.
> Thanks!
> [problem_report.txt](https://github.com/OpenZWave/open-zwave/files/2076152/problem_report.txt)
> [problem_report_solution.txt](https://github.com/OpenZWave/open-zwave/files/2076153/problem_report_solution.txt)
> [problem_patch.txt](https://github.com/OpenZWave/open-zwave/files/2076154/problem_patch.txt)

You just need to wake up the keyfob after restarting your device.

**Comment by Fishwaldo** [comment]
This is completed.

**Comment by Fishwaldo** [comment]
It’s completed in the Dev Branch which will be merged with master onces the remaining items on Milestone 1.6 are complete (and we will make a release then)

**Comment by stromnet** [comment]
Woho, very good news! Great job! :) Will see if I can give it a try :)

**Comment by KptnKMan** [comment]
@Fishwaldo thanks very much. Much appreciated. :)
