### ISSUE TITLE
Patch for Color Control class (0x33)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [OpenZWave/open-zwave#409]
```
I made the following patch to enable support for the color control class (0x33).
It still needs to have some for for the 'get' command which i hope to test soon 
with a Fibaro RGBW node.

It can be used to control the Zipato RGBW bulb, but also the Fibaro RGBW 
supports this class.

With it, you can directly set the color (RGBW)

Attached:
- patch
- modified zipato bulb configuration file
- modified fibaro rgbw configuration file

The Zipato does not seem to react on the 'get' request:

  <!-- COMMAND_CLASS_COLOR get not supported -->
  <CommandClass id="51" getsupported="false"/>

The Fibaro could maybe work by modifying some configuration parameters but is 
not checked yet
 
```

Original issue reported on code.google.com by `gizmo...@gmail.com` on 30 Nov 2014 at 7:24

Attachments:
* [ozwave_color2.patch](https://storage.googleapis.com/google-code-attachments/open-zwave/issue-409/comment-0/ozwave_color2.patch)
* [RGBBulb.xml](https://storage.googleapis.com/google-code-attachments/open-zwave/issue-409/comment-0/RGBBulb.xml)
* [fgrgbwm441.xml](https://storage.googleapis.com/google-code-attachments/open-zwave/issue-409/comment-0/fgrgbwm441.xml)

**Comment by Fishwaldo** [comment]
I figured out the Get syntax - you had to append the Color Channel to the Get Request. But Fibaro always return channel 3 when doing a report. I believe its a bug and pending them to confirm. If so, its going to make this class messy :(

**Comment by Fishwaldo** [comment]
For reference 
We Represent the Color as #RRGGBBWWCWAMCYPR where
RR = Red
GG = Green
BB = Blue
WW = Warm White
CW = Cold White
AM = Amber
CY = Cyan
PR = Purple
 with these conditions:

If the device only supports one type of White, then regardless of Cold White or Warm White, it just outputs RRGGBBWW (Assuming it doesn't support the other colors)

The minimum it will output is
RRGGBB even if any of those colors are not supported (will be set to 00)

if we have somethign like a RGB + CW + PR device then it will be:
RRGGBBCW0000PR
or how about a RGB + CW + WW + AM
RRGGBBCWWWAM
and finally, say its a RGB + AM
RRGGBB00AM

You can check what colors it supports with the ValueID index 254, and from that decode the string.
But I suspect most devices will only ever support RGBW, so it shouldn't be overly complicated to have basic support for them.

**Comment by Fishwaldo** [comment]
pretty much working - but because the Fibaro is such a buggy piece of ****, I can't test unsoliciated reports yet. Aeon are sending me the LED bulb this week, so I should be able to confirm it very soon.... as well as update the Color Index lists.

**Comment by kkuustik** [comment]
Could you please help out a newbie here. I just got a Zipato RGBW bulb and am trying to write some c++ to handle it (I am not using open-zwave-control-panel or anything, just trying to write something on top of openzwave). As far as I understand, you have done some great work over the time and at least some of the bulb functionality should work already. I just do not know how to use the tools.
Currently I am using an older version of openzwave (from February) and added Color.cpp, Color.h, RGBBulb.xml and new CommandClasses.cpp from New-CC branch.
I can turn the bulb on and off (COMMAND_CLASS_SWITCH_MULTILEVEL, label "Level", using  Manager::Get()->SetValue() or COMMAND_CLASS_SWITCH_MULTILEVEL, label "Bright", using Manager::Get()->PressButton()) but it is cold white. I would like to know how to turn on the bulb with warm white light.
Also, If the light is on and I turn it off from the wall switch, how to know from the code that the light is not consuming electricity anymore?

Tanks for the help and patience in advance.

**Comment by Fishwaldo** [comment]
I would just use the New-CC branch instead of patching it in. 

If it doesnt work, please send a full log file (after removing zwcfg_*.xml file and restarting) to the mailing list.

**Comment by Fishwaldo** [comment]
If you switch the light power off, then you cant communicate with it. It will eventually show up as a dead node in OZW. Switching it back on might not bring it out of dead mode unless it sends a message to the controller. Read about dead nodes on the knowledge base.

**Comment by kkuustik** [comment]
Is there any hidden trick to get the warm white light? Does the bulb have to be switched off beforehand (COMMAND_CLASS_SWITCH_MULTILEVEL, label "Level", using Manager::Get()->SetValue(Value ID, 0)) or should it be on? 
Is there a way to know that the node might be dead more quickly than just "eventually" ? For example I have a physical button and after pressing it I would like to get a list of things consuming electricity.  If the light is switched off from the wall switch then that should not be reported after the button click. 
Thanks.

**Comment by Fishwaldo** [comment]
You have to use the COMMAND_CLASS_COLOR

Firstly, Z-Wave devices are NOT meant to be turned off. 

If the light is off, as mentioned, there is no way for Z-Wave to know its off, other that it stops responding when we try to send a message to it. We only send messages either when you initiate something, or if you enable polling. But as mentioned, if the device gets into the Dead Node list, reviving it usually is "not automatic" 

If your light was on, and then you switched it off at the wall switch, OZW would still think your light is on, and report it as such if you checked the ValueID's. No Power = Dead Node. 

please ask further questions on the mailing list
