### ISSUE TITLE
ValueShort initializes the Value Base class as a Byte

### ISSUE THREAD

**Issue by GoogleCodeExporter** [OpenZWave/open-zwave#416]
```
in the constructor of ValueShort:


Value( _homeId, _nodeId, _genre, _commandClassId, _instance, _index, 
ValueID::ValueType_Byte, _label, _units, _readOnly, _writeOnly, false, 
_pollIntensity ),


We should change to ValueID::ValueType_Short but I need to check what if 
anything, will break here. :(
```

Original issue reported on code.google.com by `jus...@dynam.ac` on 12 Dec 2014 at 3:30

**Comment by xs4** [comment]
ValueSchedule also has the same issue. ie uses ValueID::ValueType_Byte iso ValueID::ValueType_Schedule as argument in the constructor.

**Comment by Fishwaldo** [comment]
Argh... Simple Fix be Not!

The Value Class doesn't handle a lot of the different ValueTypes. Particulary in the VerifyRefreshedValue function.

**Comment by Fishwaldo** [comment]
This should be fixed now.
