### ISSUE TITLE
new device configuration

### ISSUE THREAD

**Issue by GoogleCodeExporter** [OpenZWave/open-zwave#464]
```
Hi,

I have these configuration files that still don't exist on the repo

I hope it helps


```

Original issue reported on code.google.com by `santal.m...@gmail.com` on 23 Feb 2015 at 12:41

Attachments:
* [manufacturer_specific.xml](https://storage.googleapis.com/google-code-attachments/open-zwave/issue-464/comment-0/manufacturer_specific.xml)
* [doorlock.xml](https://storage.googleapis.com/google-code-attachments/open-zwave/issue-464/comment-0/doorlock.xml)
* [keypad.xml](https://storage.googleapis.com/google-code-attachments/open-zwave/issue-464/comment-0/keypad.xml)

**Comment by ualex73** [comment]
I added the configuration to the repository, but i tweaked some a little bit. You removed the door lock commandclass, which looks to be mandatory for these type of devices. Now the commandclass isn't "pulled" (get requests), but it still can process data received from the device.
