### ISSUE TITLE
New Aeon Labs Multisensor Gen5 not recognized

### ISSUE THREAD

**Issue by GoogleCodeExporter** [OpenZWave/open-zwave#467]
```
Using Domoticz2.2284, the New Aeon Labs Multisensor Gen5 not recognized.
In in the /domotics/Config directory there is the manufacturer_specific.xml 
which does not contain a valid entry for this Aeon device.

I added one myself:
<Product type="0002" id="004a" name="Multi Sensor G5" 
config="aeon_labs/alms.xml"/>

Like to have this device by default available in OpenZWave

See my post in which the issue was described and solved (user IDavid were my 
posts):

http://www.domoticz.com/forum/viewtopic.php?f=24&t=5545&p=35878&hilit=aeon#p3587
8

thnx for helping
```

Original issue reported on code.google.com by `esmee.da...@gmail.com` on 28 Feb 2015 at 8:20

**Comment by Fishwaldo** [comment]
Related to Issue #352.

**Comment by ualex73** [comment]
@tmartine: can you make the Gen5 PDF available please? Then i can check the content and update the device profile.

**Comment by nechry** [comment]
You can download at
http://doc.eedomus.com/files/Engineering%20Spec%20-%20Aeon%20Labs%20MultiSensor%20Gen5%20V1.02.pdf

there is a good way to send pdf or lof file with github?

**Comment by Fishwaldo** [comment]
Alex, I got all the current Aeon Labs Manuals sent to me. I will upload them to the Wiki soon.

**Comment by ualex73** [comment]
@nechry: thanks for the link/pdf, i will add this one soon

@justin: thanks - then we can update the manufacturer.xml and device profiles

**Comment by Fishwaldo** [comment]
https://github.com/OpenZWave/open-zwave/wiki/Technical-Documents

The New Docs are from Heavy Duty Switch onwards.

**Comment by Fishwaldo** [comment]
Fixed now that the Security rewrite is merged into master.
