### ISSUE TITLE
Fibaro Smoke Sensor FGSD-102

### ISSUE THREAD

**Issue by GoogleCodeExporter** [OpenZWave/open-zwave#469]
```
Hello,
Here is the xml file for the new Fibaro Smoke Sensor FGSD-102.
Can you integrate it ?

Thanks you !
```

Original issue reported on code.google.com by `tmartine...@gmail.com` on 10 Mar 2015 at 12:44

Attachments:
* [fgsd102.xml](https://storage.googleapis.com/google-code-attachments/open-zwave/issue-469/comment-0/fgsd102.xml)
* [manufacturer_specific.xml](https://storage.googleapis.com/google-code-attachments/open-zwave/issue-469/comment-0/manufacturer_specific.xml)

**Comment by ualex73** [comment]
The device is added to the master branch, only i renamed fgsd102 to fgsd002, because that's in the documentation. I also fixed a typo in the device config, which i noticed isn't your fault - it is faulty in a few other configs.
