### ISSUE TITLE
[PATCH] Aeon Labs DSD31 Siren Gen5 and some problems

### ISSUE THREAD

**Issue by GoogleCodeExporter** [OpenZWave/open-zwave#472]
```
Hi,

just purchased an Aeon Labs DSD31 Siren Gen5 (this is a zwave plus device), and 
released a simple patch for supporting Configuration Parameters.

But some problems remain:
- changing parameters will not update the device (attached a log file)
  for example I changed the parameter 37 from int 13 (default) to 51, but nothing happen (my mystake?)

- turning on the siren works, but not turning off... I must turn off the siren 
by hand pressing the hardware button.

Attached the patches and the OZW_Log

King regard

```

Original issue reported on code.google.com by `ugo.v...@gmail.com` on 12 Mar 2015 at 10:37

Attachments:
* [OZW_Log_siren_gen5.txt](https://storage.googleapis.com/google-code-attachments/open-zwave/issue-472/comment-0/OZW_Log_siren_gen5.txt)
* [manufacturer_specific.xml-20150312.patch](https://storage.googleapis.com/google-code-attachments/open-zwave/issue-472/comment-0/manufacturer_specific.xml-20150312.patch)
* [dsd31.xml](https://storage.googleapis.com/google-code-attachments/open-zwave/issue-472/comment-0/dsd31.xml)

**Comment by jin78** [comment]
Hi Justin, do you have posted a patch before the switch from googlecode to github?

**Comment by Fishwaldo** [comment]
Did you follow these steps?
https://github.com/OpenZWave/open-zwave/wiki/Adding-Security-Devices-to-OZW

**Comment by jin78** [comment]
I use domoticz as OZW controller, and domoticz by default set this Security Key:

0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x0E, 0x0F, 0x10

So "I think" the security devices are manager correctly...  anyway I'll look deeper in the guide to understand if Domoticz doesn't manage the Security Key correctly.

If you want I can post a full log when including this device.

Regards

**Comment by Fishwaldo** [comment]
I've just recieved the Aeon Labs donation, the Siren is part of it, so I will work on this soon, but first we need to fix Issue #352 which is WIP at the moment.

**Comment by jin78** [comment]
Good to know! thank you very much for the support!

**Comment by Fishwaldo** [comment]
This should be fixed now that the Security rewrite is merged into master.
