### ISSUE TITLE
Motion sensor is not working (part of Aeon Labs Multisensor Gen5 ZW074)

### ISSUE THREAD

**Issue by Beddie** [OpenZWave/open-zwave#475]
The motion sensor is not set to ON when trying to trigger it by moving my body/hand above the sensor. Parameter 4=1(PIR motion sensor = ON) and parameter 5=1 (basic set command). Also tried parameter 5=2. The sensitivity knob is turned to max level.
Humidity, Luminance and Temperature are more or less working. Motion sensor fix is most urgent.

Config: pi 2 + Razberry 2

http://www.domoticz.com/forum/viewtopic.php?f=24&t=5545

**Comment by strips** [comment]
+1

**Comment by Fishwaldo** [comment]
Most Likely related to Issue #352. thats WIP.

**Comment by Fishwaldo** [comment]
Please track Issue #352 and Issue #467
