### ISSUE TITLE
testissue

### ISSUE THREAD

**Issue by Fishwaldo** [OpenZWave/open-zwave#476]
testissue

**Comment by hari2** [comment]
Reopening, still not fixed

**Comment by Fishwaldo** [comment]
Trying again

**Comment by hari2** [comment]
still not working but I leave this closed

**Comment by hari2** [comment]
Mail reply

Am 16. März 2015 09:40:22 MEZ, schrieb Justin Hammond <notifications@github.com>:
>Closed #476.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/OpenZWave/open-zwave/issues/476#event-255192973

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.
