### ISSUE TITLE
DoorLock 0x5d command class not supported

### ISSUE THREAD

**Issue by kintoki2015** [OpenZWave/open-zwave#483]
Hello I have a door lock and open zwave 1.3.1021 library report me that the command class 0x5d is not supported.

Is that a grave issue ?

**Comment by Fishwaldo** [comment]
No. CC 0x5d is COMMAND_CLASS_ANTITHEFT. I have no idea what it does or what its used for, but you can still lock/unlock etc your door without it.

**Comment by kintoki2015** [comment]
ok but maybe it s to lock the doorlock panel no ?

**Comment by Fishwaldo** [comment]
that should be the COMMAND_CLASS_PROTECTION
