### ISSUE TITLE
Adding support for DragonTech In Wall Dimmer

### ISSUE THREAD

**Issue by stevejbauer** [OpenZWave/open-zwave#502]
The devices from DragonTech are not support in the database.  The device that I have is a DragonTech In Wall Dimmer which is a new zwave plus in wall dimmer for the US.  The link to buy this is on Amazon at:  http://www.amazon.com/Dragon-Tech-WD-100-Z-Wave-Multi-Scene/dp/B00T585DUU/ref=sr_1_1?ie=UTF8&qid=1428292643&sr=8-1&keywords=dragon+tech

I have the database files created for this device.  Did you want me to create a pull request for it?  Also, if I scan the manual, where would you like me to put that at?

**Comment by Fishwaldo** [comment]
Yes. Please open a pull request. 

I assume you followed these instructions:

https://github.com/OpenZWave/open-zwave/wiki/Adding-Devices

**Comment by Fishwaldo** [comment]
and you can email me the manual, i'll upload it to the wiki.

**Comment by stevejbauer** [comment]
Here is the manual.  I had to scan it since I can't find this version of it
online.

**Comment by Fishwaldo** [comment]
You need to email it direct to me. GitHub filters it out... :)

**Comment by Fishwaldo** [comment]
added the doc. Thanks

**Comment by Fishwaldo** [comment]
Closing this.
