### ISSUE TITLE
NorthQ device not reporting reading

### ISSUE THREAD

**Issue by killercode** [OpenZWave/open-zwave#511]
Hi,

I've been trying to use a northQ device but I don't have energy reading at all... the device wakes up goes back to sleep and doesn't report anything in between?

Is this a misconfiguration on the xml file?

**Comment by Fishwaldo** [comment]
No Logs - No Details. Nothing to diagnose this problem..... 
Sorry, we need more info....

**Comment by Fishwaldo** [comment]
Check the Associations on the Device and the Configuration values..... but without the log, I can't comment... so its not that irrelevant after all...

**Comment by killercode** [comment]
Ok I will send you a log
Also do you think that the zwcfg file will be handy?

**Comment by killercode** [comment]
Ok, no problem at all with the lib, I have to poll the value everytime the device wakes up
