### ISSUE TITLE
OZW Network Hanging

### ISSUE THREAD

**Issue by killercode** [OpenZWave/open-zwave#536]
Hi,

there is a problem that I face on OZW for a long time, everytime we have a not properly configured device ( which happens a lot) he gets stuck on it's attempts to communicate and all the messages are kept in queue for a long time.

Is there a way to reduce the attempt time and number of attempts. I believe this could be configurable. In my opinion if the message failed in 5 seconds or so it should be discarted.

Can this be done or clarified?

**Comment by Fishwaldo** [comment]
Fix the problem devices by fixing up the config files. :)

Please use the google groups mailing list for questions, not the Issue Tracker.
