### ISSUE TITLE
LogImpl::QueueDump => crash

### ISSUE THREAD

**Issue by gizmocuz** [OpenZWave/open-zwave#556]
While debugging on Windows, i had a crash, and it's a valid crash:

void LogImpl::QueueDump

Log::Write( LogLevel_Internal, strTemp.c_str() );

value of "strTemp" equals:

"2015-05-14 14:28:47.870 6276 Received SensorMultiLevel report from node 3, instance 1, Luminance: value=16%"

please note the percentage sign at the end, this will let the log function crash

solution:

Log::Write(LogLevel_Internal, "%s", strTemp.c_str());

This might be on other locations as well

/Rob

**Comment by Fishwaldo** [comment]
Good Catch. This was probably the crash that JK was reporting in issue #352
