### ISSUE TITLE
Windows build, problem with winversion.cpp

### ISSUE THREAD

**Issue by gizmocuz** [OpenZWave/open-zwave#557]
When compiling for a second time, the git version is 'added' to the winversion.cpp
and the compiler will complain about duplicate values

is it possible to put this in as the first command in the Build Events/Pre-Build Event Command Line:

del ..\winversion.cpp

**Comment by Fishwaldo** [comment]
Can you do a quick patch/pull request? My windows dev virtual machine is currently sitting in a pile of HDD's in the cupboard :)

Related to PR #555 as it seems vs2013 doesn't migrate this from a vs2010 project file it seems.

**Comment by gizmocuz** [comment]
not that experienced with git, but i think there should be a pull request now

**Comment by Fishwaldo** [comment]
Thanks. Merged. :)
