### ISSUE TITLE
Vision zp3102 (New configuration file)

### ISSUE THREAD

**Issue by gizmocuz** [OpenZWave/open-zwave#584]
I received a PIR sensor to test (it was not working correctly).

I finally got the sensor working correctly, and needed to modify the configuration file.

Is it possible to replace the current one with the attached one?

Most problems where in values being requested that where not answered back, but the status was reporting correctly

i have attached the new configuration file in mailen list at:

https://groups.google.com/forum/#!topic/openzwave/tNk-XtNenYI

With kind regards,
Rob

**Comment by Fishwaldo** [comment]
As commented, can you post of log file while doing inclusion on this device? so many unsupported CC's seems dubious. I just want to confirm before merging.

**Comment by openzwave-dev-watcher** [comment]
dont have the device here anymore.
Without these lines, the sensor was not working, until we manually wake it

still reports the values correctly

**Comment by Erik-NA** [comment]
Please check issue #698 (which should have been fixed but isn't?) and try to use that config file.

**Comment by Fishwaldo** [comment]
Please reopen if this is still a issue
