### ISSUE TITLE
Updated configuration file for Aeon Smart Switch Gen5

### ISSUE THREAD

**Issue by Gert05** [OpenZWave/open-zwave#589]
I have updated the configuration file for the Aeon Smart Switch Gen5.

New functionality includes e.g. the behaviour of the LED.

The device now works flawlessly on Domoticz (on Raspberry Pi).

Change in manufacturer_specific.xml:
<Product type="0003" id="004b" name="Smart Energy Switch G5" config="aeon_labs/ses3.xml"/>

File ses3.xml is uploaded via the OpenZwave forum at Google groups.

**Comment by Fishwaldo** [comment]
I believe Nechry is creating a PR for this.

**Comment by nechry** [comment]
Yes I will submit soon.

**Comment by nechry** [comment]
https://github.com/OpenZWave/open-zwave/pull/595
