### ISSUE TITLE
Setting Date Time

### ISSUE THREAD

**Issue by killercode** [OpenZWave/open-zwave#606]
Hi,

I'm using a NorthQ POwer Meter and I noticed that I can only update the date/time to my system date time... isn't it possible to set the date and time on the parameters?

I tried several combinations of value settings but I was unable, it just updates to my system.

Am I doing something wrong?

**Comment by Fishwaldo** [comment]
No. Not currently. 

As previously mentioned, do NOT use the issue tracker for questions. Please use our Mailing list.
