### ISSUE TITLE
kWh reset counter?

### ISSUE THREAD

**Issue by ado464** [OpenZWave/open-zwave#609]
I am using Aeon Labs Energy Meters, and i can't find any kWh reset anywhere, is there some kind of command that i can send to it to reset or? I am on linux.

Cheers and thanks for this awesome software

**Comment by Fishwaldo** [comment]
Please use the mailing list for questions (https://groups.google.com/forum/#!forum/openzwave)

I believe power cycling the HEM will reset the KWH report.
