### ISSUE TITLE
Sigma UZB-E manufacturer

### ISSUE THREAD

**Issue by fastidio** [OpenZWave/open-zwave#615]
Hi, with my Sigma UZB-E dongle i get this:
        <Node id="1" name="" location="" basic="2" generic="2" specific="1" type="Static PC Controller" listening="true" frequentListening="false" beaming="true" routing="true" max_baud_rate="40000" version="4" query_stage="Complete">
                <Manufacturer id="0000" name="Unknown: id=0000">
                        <Product type="0001" id="0001" name="Unknown: type=0001, id=0001" />
                </Manufacturer>

but I should see a ATTRS{idVendor}=="0658", ATTRS{idProduct}=="0200"

How can I correct it?

thank you.

I attach the domotiga open zwave-controller screenshot
![domotiga](https://cloud.githubusercontent.com/assets/13116234/8427996/c4932da4-1f1b-11e5-9dfe-353ac30e5572.png)

**Comment by Fishwaldo** [comment]
thats the USB id's which is completely different from the Z-Wave ID's. You would need to ask Domotiga about what your trying to achieve.
