### ISSUE TITLE
Full text of Apache 2.0 license needed

### ISSUE THREAD

**Issue by alteholz** [OpenZWave/open-zwave#621]
According to the file header cpp/build/sh2ju.sh is licensed under Apache-2.0. According to §4.a of that license "You must give any other recipients of the Work or Derivative Works a copy of this License"
(-> http://www.apache.org/licenses/LICENSE-2.0). So please add the license text as an extra file to your repository ...

Thanks!
 Thorsten

**Comment by Fishwaldo** [comment]
Thanks
