### ISSUE TITLE
Adding configuration support for Aeotec Smart Energy Illuminator

### ISSUE THREAD

**Issue by LiPeR** [OpenZWave/open-zwave#625]
Hi,

Can you add support for the configurations for this plug ?

No way to reset the plug with the param 255 by the config panel.

http://ozw.my-ho.st/Aeon/Engineering%20Spec%20-%20Aeon%20Labs%20Smart%20Energy%20Illuminator.pdf

Thanks in advance :)

**Comment by Fishwaldo** [comment]
please read https://github.com/OpenZWave/open-zwave/wiki/Adding-Devices
