### ISSUE TITLE
Everspring SP814 configuration not reliable

### ISSUE THREAD

**Issue by iarmstrong** [OpenZWave/open-zwave#627]
I have an Everspring SP814 which proved difficult to configure, with the new values often failing to 'take' and the old values remaining in effect.

The problem appears to be related to the sequence in Value::Set (cpp/src/value_classes/Value.cpp), where the configuration is immediately re-read after being updated. The value re-read is often the old value, and the node continues to use this old value, so it's not simply returned the wrong data.

I managed to work around the problem by introducing a kludge in cpp/src/Driver.cpp to give a delay of one second (don't know how short it can be) between the SetValue and RequestValue commands. With this the configuration procedure becomes reliable. I assume it to be a bug in the SP814 where the request cancels the set, but I don't know if any other command issued too soon can also 'break' the configuration process.

**Comment by Fishwaldo** [comment]
Putting a delay in is as you mentioned a kludge at best for a single device out of the few hundred devices that work correctly, so I'm not keen to do this just for a single device. In the future though, a delayed Get could be benificial for other command classes (mainly dimmers) so if we ever introduce that, then we can fix this. In the mean time, I'll close this issue.
