### ISSUE TITLE
license of AES stuff

### ISSUE THREAD

**Issue by alteholz** [OpenZWave/open-zwave#631]
As you might know I am trying to build an official Debian package from openzwave. At the moment this fails because of the license of your AES stuff. 

It says: "The redistribution and use of this software (with or without changes) is allowed without the payment of fees or royalties provided that ...".

In the eyes of Debian, especially §1 of the Debian Free Software Guidelines (DFSG)[1], the prohibition of sale of the software is a forbidden restriction.

Would it be possible to relicense the AES stuff or use a different implementation?

Thanks!
 Thorsten

[1]https://www.debian.org/social_contract#guidelines

**Comment by Fishwaldo** [comment]
It's not our code to relicense. 

Regardless, I think your reading it wrong. That paragraph is basically saying regardless if you charge for the software, you don't have to pay any royalties/fees to the author of the AES code. 

Anyway, I doubt Debain would accept it (maybe non-free) considering there is patent/trademark and the non-free nature of Zwave in General. RedHat's legal team rejected it for Fedora.
