### ISSUE TITLE
Adding support for Widom Energy Driven switch

### ISSUE THREAD

**Issue by robybob64** [OpenZWave/open-zwave#633]
Energy driven switch is a new widom device that provides voltage, current, power and power factor measurement. More over it may directly control a slave switch in order to activate loads when events occur. 

<Product type="1214" id="0304" />
(first draft XML are ready to be submitted here)

**Comment by robybob64** [comment]
Here you are 
Please insert the following code within widom Manufacturer Id (manufacturer_specific.xml):

    
    <Product type="1214" id="0304" name="UME304 Energy Driven Switch" config="widom/UME304C_S.xml"/>


Then file UME304C_S.xml, first draft, is the following: 

    <?xml version="1.0" encoding="UTF-8"?>
    <Product xmlns='http://code.google.com/p/open-zwave/'>

    

        
        <CommandClass id="112">
                <Value type="list" genre="config"  index="1" label="Device status 1 click" size="1" min="1" max="4" value="1">
                        <Help>Device status when the external switch receives 1 click</Help>
                        <Item label="Toggle (default)" value="1" />
                        <Item label="On" value="2" />
                        <Item label="Off" value="3" />
                        <Item label="Ignore" value="4" />
                </Value>

                <Value type="list" genre="config"  index="20" label="Device status Basic Set" size="1" min="1" max="4" value="1">
                        <Help>Device status when ZWave command Basic Set is received</Help>
                        <Item label="As Received (default)" value="1" />
                        <Item label="Ignore if On" value="2" />
                        <Item label="Ignore if Off" value="3" />
                        <Item label="Ignore" value="4" />
                </Value>

                <Value type="short" genre="config"  index="30" label="Overcurrent level" size="2" min="0" max="4500" value="4500" units="centiAmperes">
                        <Help>C VERSION. Sets the current level above which the time spent above that level is measured. For S VERSION. Sets to 1250 the default and max current level above which the time spent above that level is measured  (Hundredths of Amperes)</Help>
                </Value>

                <Value type="short" genre="config"  index="31" label="Overcurrent time" size="2" min="0" max="10800" value="10" units="seconds">
                        <Help>Sets the time beyond which, in the case of overcurrent at a level higher than that established in parameter 30, an OverCurrent event occurs (seconds)</Help>
                </Value>

                <Value type="list" genre="config"  index="32" label="Next state" size="1" min="0" max="3" value="1">
                        <Help>Defines the next state of the device if an overcurrent event has occurred.</Help>
                        <Item label="Ignore" value="1" />
                        <Item label="On" value="2" />
                        <Item label="Off" value="3" />
                        <Item label="Toggle" value="4" />
                </Value>

                <Value type="int" genre="config"  index="33" label="Meter reset" size="4" min="0" max="4294967296" value="1">
                        <Help>Provides total operating time from last meter reset. When set to 0 it resets the cumulated values of energy and total operating time.</Help>
                </Value>

                <Value type="list" genre="config"  index="34" label="Energy flow" size="1" min="1" max="2" value="1">
                        <Help>Determines whether energy events are related to energy consumed or energy produced</Help>
                        <Item label="Consumed" value="1" />
                        <Item label="Produced" value="2" />
                </Value>

                <Value type="short" genre="config"  index="35" label="UP Power Level" size="2" min="0" max="11250" value="11250" units="Watts">
                        <Help>C VERSION. Sets the level of instantaneous power in Watts beyond which time of permanence above this level is calculated. For S VERSION. Sets to 3000 the default and max level of instantaneous power in Watts beyond which time of permanence above this level is calculated.</Help>
                </Value>

                <Value type="short" genre="config"  index="36" label="UP Power Time" size="2" min="0" max="10800" value="10" units="seconds">
                        <Help>Sets the time in seconds beyond which, if instantaneous power remains at levels exceeding threshold defined by parameter 35, a UP Power event occurs.</Help>
                </Value>

                <Value type="list" genre="config"  index="37" label="UP Power State" size="1" min="0" max="3" value="0">
                        <Help>Defines the next state of the device if an overcurrent event has occurred.</Help>
                        <Item label="Ignore" value="0" />
                        <Item label="On" value="1" />
                        <Item label="Off" value="2" />
                        <Item label="Toggle" value="3" />
                </Value>

                <Value type="byte" genre="config"  index="38" label="UP Power Associated" size="1" min="-1" max="99" value="0">
                        <Help>Defines the status of associated devices in the presence of a UP Power event. From: 1 to 99 for dimming purpose. .0 (OFF) and -1(ON) for switching ON/OFF</Help>
                </Value>

                <Value type="short" genre="config"  index="39" label="DOWN Power Level" size="2" min="0" max="11250" value="0" units="Watts">
                        <Help>Sets the level of instantaneous power in Watts beyond which time of permanence below this level is calculated.</Help>
                </Value>

                <Value type="short" genre="config"  index="40" label="DOWN Power Time" size="2" min="0" max="10800" value="10" units="seconds">
                        <Help>Sets the time in seconds beyond which, if instantaneous power remains at levels below threshold defined by parameter 39, a DOWN Power event occurs.</Help>
                </Value>

                <Value type="list" genre="config"  index="41" label="DOWN Power State" size="1" min="0" max="3" value="0">
                        <Help>Defines the next state of the device in the case of a DOWN Power event occurring.</Help>
                        <Item label="Ignore" value="0" />
                        <Item label="On" value="1" />
                        <Item label="Off" value="2" />
                        <Item label="Toggle" value="3" />
                </Value>

                <Value type="byte" genre="config"  index="42" label="DOWN Power Associated" size="1" min="-1" max="99" value="0">
                        <Help>Defines the status of associated devices in the presence of a DOWN Power event. From: 1 to 99 for dimming purpose.  0 (OFF) and -1(ON) for switching ON/OFF.</Help>
                </Value>

                <Value type="int" genre="config"  index="43" label="Energy Level" size="4" min="0" max="4294967296" value="2000000" units="kWh">
                        <Help>the energy level that once exceeded an Energy Limit event occurs. From 0 to 2.000.000 KWh   Default value: 2.000.000 KWh</Help>
                </Value>

                <Value type="list" genre="config"  index="44" label="Energy Limit State" size="1" min="0" max="3" value="0">
                        <Help>Defines the next state of the device in the case of an Energy Limit event occurs</Help>
                        <Item label="Ignore" value="0" />
                        <Item label="On" value="1" />
                        <Item label="Off" value="2" />
                        <Item label="Toggle" value="3" />
                </Value>

                <Value type="byte" genre="config"  index="45" label="Variation Instantaneous Power" size="1" min="1" max="100" value="10" units="%">
                        <Help>Defines the percentage variation of instantaneous power determining the sending of the report.(Default: 10%)</Help>
                </Value>

                <Value type="byte" genre="config"  index="46" label="Report Time Frequency" size="1" min="1" max="100" value="10" units="minutes">
                        <Help>Defines the maximum time in minutes since the previous report beyond which an Instantaneous Power Report will still be sent. (Default: 10 minutes)</Help>
                </Value>

                <Value type="list" genre="config"  index="47" label="Variation Total Energy" size="1" min="0" max="4" value="3">
                        <Help>Defines the increase of total energy required to generate a report listing the level of total energy to the devices associated to the Energy Notification Group.</Help>
                        <Item label="Ignore" value="0" />
                        <Item label="thousandth of kWh" value="1" />
                        <Item label="hundredth of kWh" value="2" />
                        <Item label="tenth of kWh" value="3" />
                        <Item label="kWh" value="4" />
                </Value>

                <Value type="short" genre="config"  index="48" label="Nominal Voltage" size="2" min="1100" max="2500" value="2300" units="deciVolts">
                        <Help>Defines the nominal voltage value in tenths of volts. Together with parameter No. 49 this is used by the automatic notification system to send reports on variations of voltage.</Help>
                </Value>

                <Value type="byte" genre="config"  index="49" label="Fall in maximum voltage" size="1" min="1" max="100" value="10" units="%">
                        <Help>Defines, as a percentage, the nominal value for permitted fall in maximum voltage.(default 10%)</Help>
                </Value>

                <Value type="byte" genre="config"  index="50" label="Electric parameters subjected to automatic notification" size="1" min="0" max="62" value="30">
                        <Help>
                          Defines which electric parameters, other than power, will be subjected to automatic notification. The value to be set for this parameter must be calculated as the sum of values associated to the individual electric parameter indicated in the table.(default 30)
                          Byte 1 : Bit 7: reserved;
                                          Bit 6:reserved;
                                          Bit 5: Multilevel Sensor: Power Report;
                                          Bit 4: Power factor;
                                          Bit 3: Current;
                                          Bit 2: Voltage;
                                          Bit 1: Energy;
                                          Bit 0: Power;
                        </Help>
                </Value>
                
               <Value type="short" genre="config"  index="51" label="Voltage RMS value" size="2" read_only="true" units="deciVolts" >
                        <Help>Returns the value of voltage RMS at the time of the reading expressed in tenths of Volts..</Help>
               </Value>
               <Value type="short" genre="config"  index="52" label="Current RMS value" size="2" read_only="true" units="centiAmperes" >
                        <Help>Returns the value of current RMS expressed in hundredths of Amperes.</Help>
               </Value>
               <Value type="byte" genre="config"  index="53" label="Power Factor" size="1" read_only="true" units="%" >
                        <Help>Returns the value of power factor as a percentage.</Help>
               </Value>
               <Value type="int" genre="config"  index="54" label="Total energy consumed" size="4" read_only="true" units="Wh" >
                        <Help>Returns the value of total energy consumed expressed in Wh (thousandths of KWh).</Help>
               </Value>
                <Value type="int" genre="config"  index="55" label="Total energy produced" size="4" read_only="true" units="Wh" >
                        <Help>Returns the value of total energy produced expressed in Wh (thousandths of KWh).</Help>
               </Value>
               

                <Value type="list" genre="config"  index="60" label="Start-up status" size="1" min="1" max="3" value="3">
                        <Help>Defines the status of the device following a restart(default 3)</Help>
                        <Item label="ON" value="1" />
                        <Item label="OFF" value="2" />
                        <Item label="Previous status" value="3" />
                      
                </Value>

                <Value type="list" genre="config"  index="61" label="Configuration reset" size="1" min="0" max="4" value="4">
                        <Help>Defines which parameters should be reset to default values.(default 4)</Help>
                        <Item label="Factory reset" value="0" />
                        <Item label="Association reset" value="1" />
                        <Item label="Configuration reset" value="2" />
                        <Item label="ignore" value="4" />
                </Value>

                <Value type="list" genre="config"  index="62" label="Type of external switch" size="1" min="0" max="4" value="4">
                        <Help>Defines the type of external switch connected to the device.(default 4)</Help>
                        <Item label="Ignore" value="0" />
                        <Item label="button" value="1" />
                        <Item label="switch" value="2" />
                        <Item label="Automatic recognition" value="4" />
                </Value>

                <Value type="list" genre="config"  index="63" label="Load control" size="1" min="1" max="4" value="1">
                        <Help>Defines the load control mode.(default 1)</Help>
                        <Item label="Direct control" value="1" />
                        <Item label="Contactor (normally open)" value="2" />
                        <Item label="Contactor (normally closed)" value="3" />
                        <Item label="As external indicator" value="4" />
                </Value>
        </CommandClass>

        
        <CommandClass id="133">
         <Associations num_groups="3">
                        <Group index="1" max_associations="8" label="Devices to receive notifications on: status changes; energy and power levels; device local reset" auto="true"/>
                        <Group index="2" max_associations="8" label="Devices controlled by the Up Power event" auto="false" />
                        <Group index="3" max_associations="8" label="Devices controlled by the Down Power event" auto="false"/>
         </Associations>
        </CommandClass>

</Product>


Please note, there are 2 versions with the same productId (C and S), the previous XML has been confugured for C version. In the case you have S version please manually change param 30 and 35 according instructions.

**Comment by Fishwaldo** [comment]
Next time you cat put it all in one Pull Request.
