### ISSUE TITLE
Fibaro FGK101 error temperature

### ISSUE THREAD

**Issue by Condorello** [OpenZWave/open-zwave#638]
Hi all, my fibaro fgk (4 pieces) report a temperature extra-high, ex 264 celcius degrees from the dallas sensor. I tried three different IC from two different shop in four different fgk with the dame behaviour.
The real temp should be around 28*C whitch is very similar to the reporter 264 dived by 10....
In the night it logged 210*C ehi le the real temp was 20*C, again 210/10 = 21 that is very near to the target... Seems strange that i have 4 fibaro broken or 3 dallas broken...

**Comment by Fishwaldo** [comment]
We only report what the sensors tell us. (There is no maths calculations). If it's not accurate you need to take it up with Fibaro.
