### ISSUE TITLE
Notification has no public constructor.

### ISSUE THREAD

**Issue by toffyrn** [OpenZWave/open-zwave#646]
I am developing some code using openzwave, and would like to have unit test coverage on the zwave event callback (watcher) function. The "Notification" class seems to have only private constructors, and I am for this reason unable to simulate events in my unit tests.

Are there any workarounds for this issue, or is it possible to supply a protected or public constructor?

**Comment by Fishwaldo** [comment]
Nope. It's private as only OZW should construct it and we can extend the notifications if needed without breaking the API. 

I appriciate the value of unit tests, but you might have to find another way.
