### ISSUE TITLE
Popp Smoke Detector 

### ISSUE THREAD

**Issue by wzator** [OpenZWave/open-zwave#652]
### Device from:
http://z-wave.pl/pl/p/Czujnik-dymu-i-temperatury-Z-Wave-Popp/308

### Some info on page:
http://safarimini.appspot.com/www.planete-domotique.com/blog/2015/07/10/le-detecteur-de-fumee-popp-un-detecteur-z-wave-avec-sonde-de-temperature-incluse/

### After inclusion:
 `       <Node id="27" name="" location="" basic="4" generic="161" specific="7" type="Routing Smoke Sensor" listening="false" frequentListening="false" beaming="true" routing="true" max_baud_rate="40000" version="4" query_stage="Probe">`
`                <Manufacturer id="" name="">`
`                        <Product type="" id="" name="Popp Smoke Detector" />`
`                </Manufacturer>`
`                <CommandClasses>`
`                        <CommandClass id="32" name="COMMAND_CLASS_BASIC" version="1" after_mark="true" mapping="113">`
`                                <Instance index="1" />`
`                        </CommandClass>`
`                        <CommandClass id="113" name="COMMAND_CLASS_ALARM" version="1" request_flags="2">`
`                                <Instance index="1" />`
`                                <Value type="byte" genre="user" instance="1" index="0" label="Alarm Type" units="" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="255" value="0" />`
`                                <Value type="byte" genre="user" instance="1" index="1" label="Alarm Level" units="" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="255" value="0" />`
`                        </CommandClass>`
`                        <CommandClass id="114" name="COMMAND_CLASS_MANUFACTURER_SPECIFIC" version="1" request_flags="2">`
`                                <Instance index="1" />`
`                        </CommandClass>`
`                        <CommandClass id="128" name="COMMAND_CLASS_BATTERY" version="1">`
`                                <Instance index="1" />`
`                                <Value type="byte" genre="user" instance="1" index="0" label="Battery Level" units="%" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="255" value="100" />`
`                        </CommandClass>`
`                        <CommandClass id="132" name="COMMAND_CLASS_WAKE_UP" version="1" request_flags="2">`
`                                <Instance index="1" />`
`                                <Value type="int" genre="system" instance="1" index="0" label="Wake-up Interval" units="Seconds" read_only="false" write_only="false" verify_changes="false" poll_intensity="0" min="-2147483648" max="2147483647" value="3600" />`
`                        </CommandClass>`
`                        <CommandClass id="133" name="COMMAND_CLASS_ASSOCIATION" version="1" request_flags="2">`
`                                <Instance index="1" />`
`                                <Associations num_groups="0" />`
`                        </CommandClass>`
`                        <CommandClass id="134" name="COMMAND_CLASS_VERSION" version="1" request_flags="2">`
`                                <Instance index="1" />`
`                                <Value type="string" genre="system" instance="1" index="0" label="Library Version" units="" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="Unknown" />`
`                                <Value type="string" genre="system" instance="1" index="1" label="Protocol Version" units="" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="Unknown" />`
`                                <Value type="string" genre="system" instance="1" index="2" label="Application Version" units="" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="Unknown" />`
`                        </CommandClass>`
`                </CommandClasses>`
        `</Node>`

### After fixing the configuration file log show only:
`2015-08-22 11:58:36.933 Detail, Node027, Queuing (Controller) Delete All Return Routes`
`2015-08-22 11:58:36.933 Detail, Node027, Queuing (Controller) Assign Return Route`
...
`2015-08-22 11:58:36.951 Detail, Node027, AdvanceQueries queryPending=0 queryRetries=0 queryStage=Probe1 live=1`
`2015-08-22 11:58:36.951 Detail, Node027, QueryStage_Probe1`
`2015-08-22 11:58:36.951 Info, Node027, NoOperation::Set - Routing=true`
`2015-08-22 11:58:36.951 Detail, Node027, Queuing (NoOp) NoOperation_Set (Node=27): 0x01, 0x09, 0x00, 0x13, 0x1b, 0x02, 0x00, 0x00, 0x25, 0x1f, 0xc6`
`2015-08-22 11:58:36.951 Detail, Node027, Queuing (Query) Query Stage Complete (Probe1)`
...
`2015-08-22 12:00:10.231 Info, Node027, Sending (NoOp) message (Callback ID=0x1f, Expected Reply=0x13) - NoOperation_Set (Node=27): 0x01, 0x09, 0x00, 0x13, 0x
1b, 0x02, 0x00, 0x00, 0x25, 0x1f, 0xc6`
`2015-08-22 12:00:10.237 Detail, Node027,   Received: 0x01, 0x04, 0x01, 0x13, 0x01, 0xe8`
`2015-08-22 12:00:10.237 Detail, Node027,   ZW_SEND_DATA delivered to Z-Wave stack`

...

`2015-08-22 12:00:16.909 Detail, Node027,   Received: 0x01, 0x05, 0x00, 0x13, 0x1f, 0x01, 0xf7`
`2015-08-22 12:00:16.910 Detail, Node027,   ZW_SEND_DATA Request with callback ID 0x1f received (expected 0x1f)`
`2015-08-22 12:00:16.910 Info, Node027, WARNING: ZW_SEND_DATA failed. No ACK received - device may be asleep.`
`2015-08-22 12:00:16.910 Info, Node027,   Node 27 has been marked as asleep`
`2015-08-22 12:00:16.910 Info, Node027, Node not responding - moving controller command to Wake-Up queue: Delete All Return Routes`
`2015-08-22 12:00:16.910 Info, Node027, Node not responding - moving controller command to Wake-Up queue: Assign Return Route`
`2015-08-22 12:00:16.910 Info, Node027, Node not responding - moving QueryStageComplete command to Wake-Up queue`
`2015-08-22 12:00:16.911 Detail, Node027, Notification: Notification - NoOperation`

**Comment by Fishwaldo** [comment]
The device is asleep. You need to figure out how to wake it up. Untill it wakes up, we can't complete the interview process.
