### ISSUE TITLE
Add scenes to ZME_064435 / zme_05470

### ISSUE THREAD

**Issue by CoMPaTech** [OpenZWave/open-zwave#656]
As I've posted on the [domoticz forum](https://www.domoticz.com/forum/viewtopic.php?f=6&t=7848&sid=af0bdcc773a378ac86ccb29c83359088) adding the 0x2b/43 handle from zme/kfob to the zme 064435 will allow the scene activation to be actionable (instead of 'unknown command handler 0x2b' happening).

The below snip from zwave.me/kfob.xml works perfectly (in our environment) for the single pad wall switch if added to zme_064435, switching the device to scene activation and delete/reincluding it. (Also see link to the instructions for those curious.
```
	<!-- COMMAND_CLASS_SCENE_ACTIVATION. KFob can be configured to send scene commands but does not advertise it -->
	<CommandClass id="43" action="add" getsupported="false"/>
```

**Comment by Fishwaldo** [comment]
Thanks. Applied
