### ISSUE TITLE
Qubino Flush Shutter DC - ZMNHOD1 (New configuration file)

### ISSUE THREAD

**Issue by SkorpionNL** [OpenZWave/open-zwave#667]
Hi,

I wrote the config file for the new Qubino Flush Shutter DC (ZMNHOD1). I've tested it and it works for me. One exception is that I can't get the association part right, so I was hoping someone can take a look at it. When added, it adds more numbers to the association groups than it should.

![qubino](https://cloud.githubusercontent.com/assets/15034038/10370954/73b12fd4-6de1-11e5-82f4-56b577242339.png)

**Comment by openzwave-dev-watcher** [comment]
Op donderdag 8 oktober 2015 17:25:03 UTC+2 schreef SkorpionNL:

**Comment by Fishwaldo** [comment]
Need Log Files to diagnose anything....

**Comment by Fishwaldo** [comment]
No Reply. Closing.
