### ISSUE TITLE
Compile/Build Issue on ARMv5 Arch

### ISSUE THREAD

**Issue by nwcatalyst** [OpenZWave/open-zwave#669]
I'm unable to compile successfully on an Armv5 system (GoFlex Home running ArchLinux). Is this architecture unsupported?

I have all dependencies installed, and the build of openzwave seems to go fine with no errors, but testing via MinOZW yields this error: (is it just a MinOZW issue?)

    [nw@NWCloud MinOZW]$ ls
    Main.cpp  Makefile  MinOZW.in
    [nw@NWCloud MinOZW]$ make
    Linking /home/nw/open-zwave/cpp/examples/MinOZW/.lib/MinOZW
    g++   -o /home/nw/open-zwave/cpp/examples/MinOZW/.lib/MinOZW /home/nw/open-zwave/cpp/examples/MinOZW/.lib/Main.o  -pthread
    /home/nw/open-zwave/cpp/examples/MinOZW/.lib/Main.o: In function `OnNotification(OpenZWave::Notification const*, void*)':
    Main.cpp:(.text+0x2f4): undefined reference to `OpenZWave::Manager::CancelControllerCommand(unsigned int)'
    Main.cpp:(.text+0x488): undefined reference to `OpenZWave::Manager::s_instance'
    /home/nw/open-zwave/cpp/examples/MinOZW/.lib/Main.o: In function `main':
    Main.cpp:(.text.startup+0x44): undefined reference to `OpenZWave::Manager::getVersionAsString()'
    Main.cpp:(.text.startup+0xa8): undefined reference to `OpenZWave::Options::Create(std::string const&, std::string const&, std::string const&)'
    Main.cpp:(.text.startup+0x100): undefined reference to `OpenZWave::Options::AddOptionInt(std::string const&, int)'
    Main.cpp:(.text.startup+0x134): undefined reference to `OpenZWave::Options::AddOptionInt(std::string const&, int)'
    Main.cpp:(.text.startup+0x168): undefined reference to `OpenZWave::Options::AddOptionInt(std::string const&, int)'
    Main.cpp:(.text.startup+0x19c): undefined reference to `OpenZWave::Options::AddOptionInt(std::string const&, int)'
    Main.cpp:(.text.startup+0x1d0): undefined reference to `OpenZWave::Options::AddOptionBool(std::string const&, bool)'
    Main.cpp:(.text.startup+0x204): undefined reference to `OpenZWave::Options::AddOptionBool(std::string const&, bool)'
    Main.cpp:(.text.startup+0x220): undefined reference to `OpenZWave::Options::Lock()'
    Main.cpp:(.text.startup+0x224): undefined reference to `OpenZWave::Manager::Create()'
    Main.cpp:(.text.startup+0x234): undefined reference to `OpenZWave::Manager::AddWatcher(void (*)(OpenZWave::Notification const*, void*), void*)'
    Main.cpp:(.text.startup+0x298): undefined reference to `OpenZWave::Manager::AddDriver(std::string const&, OpenZWave::Driver::ControllerInterface const&)'
    Main.cpp:(.text.startup+0x2f8): undefined reference to `OpenZWave::Manager::RemoveDriver(std::string const&)'
    Main.cpp:(.text.startup+0x318): undefined reference to `OpenZWave::Manager::RemoveWatcher(void (*)(OpenZWave::Notification const*, void*), void*)'
    Main.cpp:(.text.startup+0x31c): undefined reference to `OpenZWave::Manager::Destroy()'
    Main.cpp:(.text.startup+0x320): undefined reference to `OpenZWave::Options::Destroy()'
    Main.cpp:(.text.startup+0x350): undefined reference to `OpenZWave::Manager::RemoveDriver(std::string const&)'
    Main.cpp:(.text.startup+0x36c): undefined reference to `OpenZWave::Manager::AddDriver(std::string const&, OpenZWave::Driver::ControllerInterface const&)'
    Main.cpp:(.text.startup+0x40c): undefined reference to `OpenZWave::Manager::GetDriverStatistics(unsigned int, OpenZWave::Driver::DriverData*)'
    Main.cpp:(.text.startup+0x5f8): undefined reference to `OpenZWave::Options::s_instance'
    Main.cpp:(.text.startup+0x614): undefined reference to `OpenZWave::Manager::s_instance'
    collect2: error: ld returned 1 exit status
    Makefile:51: recipe for target '/home/nw/open-zwave/cpp/examples/MinOZW/.lib/MinOZW' failed

And later, which is what is leading me to believe this is an openzwave issue, attempting to compile Domoticz with openzwave support, the openzwave manager has failed to build correctly. See below for Domoticz output, if that helps...

`[ 62%] Building CXX object CMakeFiles/domoticz.dir/hardware/openzwave/control_panel/ozwcp.cpp.o
/home/nw/domoticz/hardware/openzwave/control_panel/ozwcp.cpp: In member function ‘std::string COpenZWaveControlPanel::DoAdminCommand(const string&, int, int)’:
/home/nw/domoticz/hardware/openzwave/control_panel/ozwcp.cpp:1260:37: warning: ‘bool OpenZWave::Manager::BeginControllerCommand(uint32, OpenZWave::Driver::ControllerCommand, OpenZWave::Driver::pfnControllerCallback_t, void*, bool, uint8, uint8)’ is deprecated [-Wdeprecated-declarations]
    web_controller_update, this, true));
                                     ^
In file included from /home/nw/domoticz/hardware/openzwave/control_panel/ozwcp.cpp:43:0:
/home/nw/domoticz/hardware/openzwave/Manager.h:1715:19: note: declared here
   DEPRECATED bool BeginControllerCommand( uint32 const _homeId, Driver::ControllerCommand _command, Driver::pfnControllerCallback_t _callback = N
                   ^
/home/nw/domoticz/hardware/openzwave/control_panel/ozwcp.cpp:1267:37: warning: ‘bool OpenZWave::Manager::BeginControllerCommand(uint32, OpenZWave::Driver::ControllerCommand, OpenZWave::Driver::pfnControllerCallback_t, void*, bool, uint8, uint8)’ is deprecated [-Wdeprecated-declarations]
    web_controller_update, this, true));
                                     ^
In file included from /home/nw/domoticz/hardware/openzwave/control_panel/ozwcp.cpp:43:0:
/home/nw/domoticz/hardware/openzwave/Manager.h:1715:19: note: declared here
   DEPRECATED bool BeginControllerCommand( uint32 const _homeId, Driver::ControllerCommand _command, Driver::pfnControllerCallback_t _callback = N
                   ^
/home/nw/domoticz/hardware/openzwave/control_panel/ozwcp.cpp:1274:37: warning: ‘bool OpenZWave::Manager::BeginControllerCommand(uint32, OpenZWave::Driver::ControllerCommand, OpenZWave::Driver::pfnControllerCallback_t, void*, bool, uint8, uint8)’ is deprecated [-Wdeprecated-declarations]
    web_controller_update, this, true));
                                     ^
In file included from /home/nw/domoticz/hardware/openzwave/control_panel/ozwcp.cpp:43:0:
/home/nw/domoticz/hardware/openzwave/Manager.h:1715:19: note: declared here
   DEPRECATED bool BeginControllerCommand( uint32 const _homeId, Driver::ControllerCommand _command, Driver::pfnControllerCallback_t _callback = N
                   ^
/home/nw/domoticz/hardware/openzwave/control_panel/ozwcp.cpp:1281:37: warning: ‘bool OpenZWave::Manager::BeginControllerCommand(uint32, OpenZWave::Driver::ControllerCommand, OpenZWave::Driver::pfnControllerCallback_t, void*, bool, uint8, uint8)’ is deprecated [-Wdeprecated-declarations]
    web_controller_update, this, true));
                                     ^
In file included from /home/nw/domoticz/hardware/openzwave/control_panel/ozwcp.cpp:43:0:
/home/nw/domoticz/hardware/openzwave/Manager.h:1715:19: note: declared here
   DEPRECATED bool BeginControllerCommand( uint32 const _homeId, Driver::ControllerCommand _command, Driver::pfnControllerCallback_t _callback = N
                   ^
/home/nw/domoticz/hardware/openzwave/control_panel/ozwcp.cpp:1288:46: warning: ‘bool OpenZWave::Manager::BeginControllerCommand(uint32, OpenZWave::Driver::ControllerCommand, OpenZWave::Driver::pfnControllerCallback_t, void*, bool, uint8, uint8)’ is deprecated [-Wdeprecated-declarations]
    web_controller_update, this, true, node_id));
                                              ^
In file included from /home/nw/domoticz/hardware/openzwave/control_panel/ozwcp.cpp:43:0:
/home/nw/domoticz/hardware/openzwave/Manager.h:1715:19: note: declared here
   DEPRECATED bool BeginControllerCommand( uint32 const _homeId, Driver::ControllerCommand _command, Driver::pfnControllerCallback_t _callback = N
                   ^
/home/nw/domoticz/hardware/openzwave/control_panel/ozwcp.cpp:1295:46: warning: ‘bool OpenZWave::Manager::BeginControllerCommand(uint32, OpenZWave::Driver::ControllerCommand, OpenZWave::Driver::pfnControllerCallback_t, void*, bool, uint8, uint8)’ is deprecated [-Wdeprecated-declarations]
    web_controller_update, this, true, node_id));
                                              ^
In file included from /home/nw/domoticz/hardware/openzwave/control_panel/ozwcp.cpp:43:0:
/home/nw/domoticz/hardware/openzwave/Manager.h:1715:19: note: declared here
   DEPRECATED bool BeginControllerCommand( uint32 const _homeId, Driver::ControllerCommand _command, Driver::pfnControllerCallback_t _callback = N
                   ^
/home/nw/domoticz/hardware/openzwave/control_panel/ozwcp.cpp:1302:46: warning: ‘bool OpenZWave::Manager::BeginControllerCommand(uint32, OpenZWave::Driver::ControllerCommand, OpenZWave::Driver::pfnControllerCallback_t, void*, bool, uint8, uint8)’ is deprecated [-Wdeprecated-declarations]
    web_controller_update, this, true, node_id));
                                              ^
In file included from /home/nw/domoticz/hardware/openzwave/control_panel/ozwcp.cpp:43:0:
/home/nw/domoticz/hardware/openzwave/Manager.h:1715:19: note: declared here
   DEPRECATED bool BeginControllerCommand( uint32 const _homeId, Driver::ControllerCommand _command, Driver::pfnControllerCallback_t _callback = N
                   ^
/home/nw/domoticz/hardware/openzwave/control_panel/ozwcp.cpp:1309:37: warning: ‘bool OpenZWave::Manager::BeginControllerCommand(uint32, OpenZWave::Driver::ControllerCommand, OpenZWave::Driver::pfnControllerCallback_t, void*, bool, uint8, uint8)’ is deprecated [-Wdeprecated-declarations]
    web_controller_update, this, true));
                                     ^
In file included from /home/nw/domoticz/hardware/openzwave/control_panel/ozwcp.cpp:43:0:
/home/nw/domoticz/hardware/openzwave/Manager.h:1715:19: note: declared here
   DEPRECATED bool BeginControllerCommand( uint32 const _homeId, Driver::ControllerCommand _command, Driver::pfnControllerCallback_t _callback = N
                   ^
/home/nw/domoticz/hardware/openzwave/control_panel/ozwcp.cpp:1316:46: warning: ‘bool OpenZWave::Manager::BeginControllerCommand(uint32, OpenZWave::Driver::ControllerCommand, OpenZWave::Driver::pfnControllerCallback_t, void*, bool, uint8, uint8)’ is deprecated [-Wdeprecated-declarations]
    web_controller_update, this, true, node_id));
                                              ^
In file included from /home/nw/domoticz/hardware/openzwave/control_panel/ozwcp.cpp:43:0:
/home/nw/domoticz/hardware/openzwave/Manager.h:1715:19: note: declared here
   DEPRECATED bool BeginControllerCommand( uint32 const _homeId, Driver::ControllerCommand _command, Driver::pfnControllerCallback_t _callback = N
                   ^
/home/nw/domoticz/hardware/openzwave/control_panel/ozwcp.cpp:1323:46: warning: ‘bool OpenZWave::Manager::BeginControllerCommand(uint32, OpenZWave::Driver::ControllerCommand, OpenZWave::Driver::pfnControllerCallback_t, void*, bool, uint8, uint8)’ is deprecated [-Wdeprecated-declarations]
    web_controller_update, this, true, node_id));
                                              ^
In file included from /home/nw/domoticz/hardware/openzwave/control_panel/ozwcp.cpp:43:0:
/home/nw/domoticz/hardware/openzwave/Manager.h:1715:19: note: declared here
   DEPRECATED bool BeginControllerCommand( uint32 const _homeId, Driver::ControllerCommand _command, Driver::pfnControllerCallback_t _callback = N
                   ^
/home/nw/domoticz/hardware/openzwave/control_panel/ozwcp.cpp:1330:46: warning: ‘bool OpenZWave::Manager::BeginControllerCommand(uint32, OpenZWave::Driver::ControllerCommand, OpenZWave::Driver::pfnControllerCallback_t, void*, bool, uint8, uint8)’ is deprecated [-Wdeprecated-declarations]
    web_controller_update, this, true, node_id));
                                              ^
In file included from /home/nw/domoticz/hardware/openzwave/control_panel/ozwcp.cpp:43:0:
/home/nw/domoticz/hardware/openzwave/Manager.h:1715:19: note: declared here
   DEPRECATED bool BeginControllerCommand( uint32 const _homeId, Driver::ControllerCommand _command, Driver::pfnControllerCallback_t _callback = N
                   ^
/home/nw/domoticz/hardware/openzwave/control_panel/ozwcp.cpp:1337:46: warning: ‘bool OpenZWave::Manager::BeginControllerCommand(uint32, OpenZWave::Driver::ControllerCommand, OpenZWave::Driver::pfnControllerCallback_t, void*, bool, uint8, uint8)’ is deprecated [-Wdeprecated-declarations]
    web_controller_update, this, true, node_id));
                                              ^
In file included from /home/nw/domoticz/hardware/openzwave/control_panel/ozwcp.cpp:43:0:
/home/nw/domoticz/hardware/openzwave/Manager.h:1715:19: note: declared here
   DEPRECATED bool BeginControllerCommand( uint32 const _homeId, Driver::ControllerCommand _command, Driver::pfnControllerCallback_t _callback = N
                   ^
/home/nw/domoticz/hardware/openzwave/control_panel/ozwcp.cpp:1344:46: warning: ‘bool OpenZWave::Manager::BeginControllerCommand(uint32, OpenZWave::Driver::ControllerCommand, OpenZWave::Driver::pfnControllerCallback_t, void*, bool, uint8, uint8)’ is deprecated [-Wdeprecated-declarations]
    web_controller_update, this, true, node_id));
                                              ^
In file included from /home/nw/domoticz/hardware/openzwave/control_panel/ozwcp.cpp:43:0:
/home/nw/domoticz/hardware/openzwave/Manager.h:1715:19: note: declared here
   DEPRECATED bool BeginControllerCommand( uint32 const _homeId, Driver::ControllerCommand _command, Driver::pfnControllerCallback_t _callback = N
                   ^
/home/nw/domoticz/hardware/openzwave/control_panel/ozwcp.cpp:1351:46: warning: ‘bool OpenZWave::Manager::BeginControllerCommand(uint32, OpenZWave::Driver::ControllerCommand, OpenZWave::Driver::pfnControllerCallback_t, void*, bool, uint8, uint8)’ is deprecated [-Wdeprecated-declarations]
    web_controller_update, this, true, node_id));
                                              ^
In file included from /home/nw/domoticz/hardware/openzwave/control_panel/ozwcp.cpp:43:0:
/home/nw/domoticz/hardware/openzwave/Manager.h:1715:19: note: declared here
   DEPRECATED bool BeginControllerCommand( uint32 const _homeId, Driver::ControllerCommand _command, Driver::pfnControllerCallback_t _callback = N
                   ^
/home/nw/domoticz/hardware/openzwave/control_panel/ozwcp.cpp:1358:57: warning: ‘bool OpenZWave::Manager::BeginControllerCommand(uint32, OpenZWave::Driver::ControllerCommand, OpenZWave::Driver::pfnControllerCallback_t, void*, bool, uint8, uint8)’ is deprecated [-Wdeprecated-declarations]
    web_controller_update, this, true, node_id, button_id));
                                                         ^
In file included from /home/nw/domoticz/hardware/openzwave/control_panel/ozwcp.cpp:43:0:
/home/nw/domoticz/hardware/openzwave/Manager.h:1715:19: note: declared here
   DEPRECATED bool BeginControllerCommand( uint32 const _homeId, Driver::ControllerCommand _command, Driver::pfnControllerCallback_t _callback = N
                   ^
/home/nw/domoticz/hardware/openzwave/control_panel/ozwcp.cpp:1365:57: warning: ‘bool OpenZWave::Manager::BeginControllerCommand(uint32, OpenZWave::Driver::ControllerCommand, OpenZWave::Driver::pfnControllerCallback_t, void*, bool, uint8, uint8)’ is deprecated [-Wdeprecated-declarations]
    web_controller_update, this, true, node_id, button_id));
                                                         ^
In file included from /home/nw/domoticz/hardware/openzwave/control_panel/ozwcp.cpp:43:0:
/home/nw/domoticz/hardware/openzwave/Manager.h:1715:19: note: declared here
   DEPRECATED bool BeginControllerCommand( uint32 const _homeId, Driver::ControllerCommand _command, Driver::pfnControllerCallback_t _callback = N`

I have tried recompiling both openzwave and domoticz from scratch about 5x now.

If I can provide any more info to assist in the resolution just let me know.

Appreciate the support!

**Comment by Fishwaldo** [comment]
in case you didn't see the replies on the list:
https://groups.google.com/forum/#!topic/openzwave/YsrPamTTaHo
