### ISSUE TITLE
Qubino ZMNHIA2 config file update

### ISSUE THREAD

**Issue by meslow** [OpenZWave/open-zwave#680]
Made some config File updates for Qubino ZMNHIA2

Added missing parameter number : 4 - 5 - 10 - 11 - 12 - 60 and 61

https://groups.google.com/d/msg/openzwave/DDSakAm4N6w/sZjq7NVzAQAJ

Thank's

**Comment by meslow** [comment]
I've update the config file but there's always an issue with COMMAND_CLASS_THERMOSTAT_SETPOINT.

I've try to moddify the value using OpenZWave Control Panel but after refresh le value is set back to 0.0 °C

Qubino comfimed the value can be SET and read using instance 1 class 0x43.

**Comment by Fishwaldo** [comment]
I'd need a log file to see what's going on. Please remove any zwcfg_*.xml file when restarting your app

**Comment by meslow** [comment]
I'm not very familiar with debbuging on Domoticz and OZW, whitch logs do you need and how to get them ?

I'll produce them a soon

**Comment by meslow** [comment]
Here are some log from domoticz

![capture](https://cloud.githubusercontent.com/assets/15234007/10979944/beaf64c2-83ff-11e5-8a2c-bcc4eeb6a49c.PNG)

**Comment by nechry** [comment]
hello, 

I just complete a working config file in jeedom fork
https://github.com/jeedom/plugin-openzwave/commit/3a14ac8592141b0c4c67975ea29ec51785d301a2
it's work perfectly

we will merge very sone all pending config to openzwave

**Comment by Fishwaldo** [comment]
Again, I'll wait for the Jeedom PR.
