### ISSUE TITLE
Get WakeUp /Battery Value

### ISSUE THREAD

**Issue by m0rphi** [OpenZWave/open-zwave#683]
Hi All,

I am interested in getting the wakeup interval value and the battery value of a node.
In openzwave the **CommandClass Wakeup and Battery** are implemented, and I wanted to trigger a GET request to the node, to get the current values.
I found out when you first set the wakeup, the get wakeup will be queued automatically.
![image](https://cloud.githubusercontent.com/assets/10657553/10834423/8a9c539a-7e99-11e5-9367-d24c6c589636.png)

Is it possible to trigger only the **WakeupCmd_IntervalGet** method? In the manager class there is no method for getting the wakeup intervall.
Similar thing is when getting the Battery value of a node. Polling will be an option, but I want to execute the **"get battery"** method only once. (found something in the documentation with BatteryCmd_Get http://www.openzwave.com/dev/Battery_8cpp.html#a8cee67732789cc2c5aadc89e31959310 )

Thanks in advance for your help!

**Comment by Fishwaldo** [comment]
(please use the mailing list for general questions).

You don't need to "Get" anything. Z-Wave is generally event driven and for "static" data like the Wakeup interval, its retrieved when OZW starts up, so it will appear as a ValueID already.

For Battery, most devices will send a Battery update when they send reports, so there is no need to "get" that either.

If reports are not working, then turn on polling for the ValueID's you are interested in, but it will cost you battery life in a lot of cases.
