### ISSUE TITLE
Everspring HAC01

### ISSUE THREAD

**Issue by FafaDomo** [OpenZWave/open-zwave#691]
<?xml version="1.0" encoding="utf-8"?>

<Product xmlns='http://code.google.com/p/open-zwave/'>
  
  <CommandClass id="112">
    <Value type="byte" genre="config" index="1" label="Basic Set Level" min="0" max="99" value="1">
      <Help>Basic Set Level
     0 -> Off
     1 - 99 -> On(binary switch device); dim level (multilevel switch device)
     </Help>
    </Value>
   
    <Value type="byte" genre="config" index="2" label="Amount of delay" min="0" max="127" value="0">
      <Help>determine the delay time setting to send the Basic Set Off command when manual switch opens
     0 -> immediately Off
     1 - 127 -> delay 1 ~ 127 second to Off
     </Help>
    </Value>
  </CommandClass>
 
  <CommandClass id="32" setasreport="true" />
  <CommandClass id="96" mapping="endpoints" />
 
  <CommandClass id="133">
    <Associations num_groups="1">
      <Group index="1" max_associations="5" label="Group 1" auto="true"/>
    </Associations>
  </CommandClass>

</Product>

**Comment by nechry** [comment]
it's a missing device configuration? We need product and type and id. Check wiki for adding device
https://github.com/OpenZWave/open-zwave/wiki/Adding-Devices

**Comment by FafaDomo** [comment]
Yes, it is ! Sorry I'm a newbie, it's my first zwave conf file...
<Manufacturer id="0060" name="Everspring"> (already in database)
Product Type ID: 	0x0010
Product ID: 	0x0001
Product Name: 	In-wall remote module HAC01
Brand Name: 	Everspring
Product Code: 	EVR_HAC01

**Comment by Fishwaldo** [comment]
its all mangled. Can you please post the config file to the mailing list (or open a Pull Request).

**Comment by Fishwaldo** [comment]
Ping. Please repost the changes to the mailing list, otherwise Ill close this.

**Comment by Fishwaldo** [comment]
Closing as no response

**Comment by openzwave-dev-watcher** [comment]
Hi, may i reopen this thread ? I found that device configuration on the 
domoticz french website i saved it as HAC01.xml in Everspring dir.
cat manufacturer_specific.xml | grep hac

 <Product type="0010" id="0001" name="HAC01 In-wall Remote Module" config=
"everspring/hac01.xml"/>

cat everspring/hac01.xml 

<?xml version="1.0" encoding="utf-8"?>

<Product xmlns='http://code.google.com/p/open-zwave/'>
  
  <CommandClass id="112">
    <Value type="byte" genre="config" index="1" label="Basic Set Level" min=
"0" max="99" value="1">
      <Help>Basic Set Level
     0 -> Off
     1 - 99 -> On(binary switch device); dim level (multilevel switch 
device)
     </Help>
    </Value>
   
    <Value type="byte" genre="config" index="2" label="Amount of delay" min=
"0" max="127" value="0">
      <Help>determine the delay time setting to send the Basic Set Off 
command when manual switch opens
     0 -> immediately Off
     1 - 127 -> delay 1 ~ 127 second to Off
     </Help>
    </Value>
  </CommandClass>
 
  <CommandClass id="32" setasreport="true" />
  <CommandClass id="96" mapping="endpoints" />
 
  <CommandClass id="133">
    <Associations num_groups="1">
      <Group index="1" max_associations="5" label="Group 1" auto="true"/>
    </Associations>
  </CommandClass>

</Product>

**Comment by openzwave-dev-watcher** [comment]
Please open a new issue on Github.

**Comment by Fishwaldo** [comment]
thats fine.

**Comment by nechry** [comment]
already existe:
https://github.com/OpenZWave/open-zwave/blob/master/config/manufacturer_specific.xml#L293
