### ISSUE TITLE
Thermostat setpoint units scaling different on r/w

### ISSUE THREAD

**Issue by Nico0084** [OpenZWave/open-zwave#697]
Hi 
on master
on ThermostatSetpoint class units handle is not the same on r/w : 

Write : 
https://github.com/OpenZWave/open-zwave/blob/847d3857eaeb4ba685b97d606f9759a828eefc79/cpp/src/command_classes/ThermostatSetpoint.cpp#L291

Read: 
https://github.com/OpenZWave/open-zwave/blob/847d3857eaeb4ba685b97d606f9759a828eefc79/cpp/src/command_classes/ThermostatSetpoint.cpp#L233

**Comment by Fishwaldo** [comment]
There is nothing wrong with that.

Bear in mind that the strcmp returns 0 for matches, so scale will be "1" for F and "0" for C. That catches a few people out. :)
