### ISSUE TITLE
ZMNHND1 Qubino Flush 1D relay configuration file

### ISSUE THREAD

**Issue by hanscbecker** [OpenZWave/open-zwave#702]
This is my first use of GitHub, so apologies in advance if I screw up.

I attach a configuration file for the Qubino ZMNHND1 Flush 1D relay that works for me (Domoticz & OpenZwave on Mac OS X). It is adapted from the ZMNHAD1 config file with only minor alterations.

The corresponding entry in manufacturer_specific.xml is
< Product type="0002" id="0053" name="ZMNHND1 Flush 1D relay" config="qubino/ZMNHND1.xml"/>

I hope this helps, and thanks for all efforts.
[ZMNHND1.xml.txt](https://github.com/OpenZWave/open-zwave/files/45026/ZMNHND1.xml.txt)

**Comment by Fishwaldo** [comment]
Thanks!
