### ISSUE TITLE
New device Sensative Strips-MaZw

### ISSUE THREAD

**Issue by michapr** [OpenZWave/open-zwave#715]
Please add config for the device - have tested, it is working.
http://www.pepper1.net/zwavedb/device/831

        <Manufacturer id="019a" name="Sensative AB">
                <Product type="0003" id="0003" name="Strips-MaZw" config="sensative/strips-mazw.xml" />
        </Manufacturer>

File attached.

Michael
[strips-mazw.zip](https://github.com/OpenZWave/open-zwave/files/68380/strips-mazw.zip)

**Comment by Fishwaldo** [comment]
Thanks!
