### ISSUE TITLE
GIT-VS-VERSION-GEN.bat Fails when there is a space in the folder hierarchy

### ISSUE THREAD

**Issue by dechutes** [OpenZWave/open-zwave#717]
When doing a build in VS (I was using the dotnet framework, but building the OpenZWave project) There is an error that the winversion.cpp file is missing.  The build config deletes that file then runs GIT-VS-VERSION-GEN.bat to regenerate it, but if your folder structure contains a space the batch file fails and the winversion.cpp file is never created.

**Comment by Fishwaldo** [comment]
Fixed in adf34678b22d89cfc38bf11c8f924e81d50ebf11
