### ISSUE TITLE
Configuration file for Qubino ZMNHJD1

### ISSUE THREAD

**Issue by stephaneguillard** [OpenZWave/open-zwave#729]
Please find attached a working, tested configuration file for Qubino Flush dimmer for pilot wire electric heater control.

[ZMNHJD1 - Micromodule fil pilote V2 Z-Wave+.zip](https://github.com/OpenZWave/open-zwave/files/83003/ZMNHJD1.-.Micromodule.fil.pilote.V2.Z-Wave.zip)

**Comment by Fishwaldo** [comment]
Thanks
