### ISSUE TITLE
fibarro FGRM222 no respone for button values

### ISSUE THREAD

**Issue by ATT-JBO** [OpenZWave/open-zwave#731]
Hi,
I'm testing the openzwave lib (python version). Works ok, except for the values of type 'button',  currently only tested on the fibarro FGRM222 (command class 38: 'open' and 'close' commands). There doesn't appear to be a response at all. I am sending a boolean value. Am I doing something wrong?

Thanks.

**Comment by Fishwaldo** [comment]
please post general questions (with log files) to the mailing list, and not here.
