### ISSUE TITLE
ZWNotification.Type.ValueChanged .net wrapper

### ISSUE THREAD

**Issue by marioeirea** [OpenZWave/open-zwave#747]
When a device is being polled, even if it's value has not changed, the notification with type ValueChanged is fired:

![image](https://cloud.githubusercontent.com/assets/16754092/12385493/a6005278-bd8a-11e5-9ddd-9de3315609c1.png)

ValueRefreshed does not seem to ever fire if the when the node is polled.

**Comment by Fishwaldo** [comment]
make sure "SuppressValueRefresh" is not set in any options.xml or application setting it via the Options class. 
OnValueRefreshed will only ever be triggered when SetChangeVerified is enabled for a ValueID. 

Any other questions, please post to the mailing list.

**Comment by marioeirea** [comment]
Correct me if I am wrong, but is the ValueChanged event supposed to fire only when the value of the node has changed not refreshed? Currently, every time the device is polled it fires an event that the value was changed even if it did not.

I made sure SuppressValueRefresh was not set.

**Comment by Fishwaldo** [comment]
Please see the ValueChanged discussion on the mailing list yesterday
