### ISSUE TITLE
NodOn, Soft Remote, CRC-3-6-00, Soft Remote Switch

### ISSUE THREAD

**Issue by etamminga** [OpenZWave/open-zwave#755]
Hi,

I'd like to ask for the following Product to be included in the manufacturer_specific.xml in the NodOn section:

```
<Manufacturer id="0165" name="NodOn">
...
                <Product type="0002" id="0002" name="CRC-3-6-00 Soft Remote" config="nodon/crc360softremote.xml"/>
...
</Manufacturer>
```

The config file crc360softremote.xml can be a copy of the file nodon/crc360softremote.xml. The configuration elements are the same.

Regards,
Erik

**Comment by nechry** [comment]
this config will be merged very soon
https://github.com/jeedom/plugin-openzwave/blob/master/ressources/openzwave/config/nodon/crc360xSofremote.xml
With many others config file and fix.
