### ISSUE TITLE
.Net wrapper missing GetChangeVerified(ZWValueID v)

### ISSUE THREAD

**Issue by marioeirea** [OpenZWave/open-zwave#756]
ZWManager.h

bool GetChangeVerified( ZWValueID^ id ) { return Manager::Get()->GetChangeVerified(id->CreateUnmanagedValueID()); }

**Comment by Fishwaldo** [comment]
its in the Dev branch:
https://github.com/OpenZWave/open-zwave/blob/Dev/dotnet/src/ZWManager.h#L1272
