### ISSUE TITLE
vision security zg8101

### ISSUE THREAD

**Issue by seblang** [OpenZWave/open-zwave#772]
i am using domotcz and it's impossible for me to associate the security vison gz8101 sensor to my zwavekey!
the sensor appear in openzwave list but .....
somebody have a solution?
thanks

**Comment by gizmocuz** [comment]
Did you post this on the Domoticz forum?
Did you try with other software?
Also try excluding first, and then including

**Comment by seblang** [comment]
Hi Yes I have post it on domoticz.
I have no other software.
Exclusive include done but nothing.

**Comment by gizmocuz** [comment]
try other software

**Comment by Fishwaldo** [comment]
Please use the mailing list for support...
