### ISSUE TITLE
Improve support for Aeotec Double Smart switch

### ISSUE THREAD

**Issue by dnpwwo** [OpenZWave/open-zwave#774]
Update manufacturer xml, works better if line 63 is:

<Product type="0003" id="0011" name="Micro Double Switch"  config="aeotec/msesv2.xml"/>

**Comment by nechry** [comment]
We don't see your line. Check Styling markdown for code

**Comment by dnpwwo** [comment]
Product type="0003" id="0011" name="Micro Double Switch"  config="aeotec/msesv2.xml"

**Comment by Fishwaldo** [comment]
Thanks!
