### ISSUE TITLE
Build doesn't seem to install libopenzwave.so.1.4 in a sensible place

### ISSUE THREAD

**Issue by dhylands** [OpenZWave/open-zwave#777]
I'm running Ubuntu 14.04 LTS.

Now, my machine does have /lib64 with a single entry in it:

2009 >ls -l /lib64
total 0
lrwxrwxrwx 1 root root 32 Feb 25  2015 ld-linux-x86-64.so.2 -> /lib/x86_64-linux-gnu/ld-2.19.so*

There is no /usr/local/lib64 directory.

Looking at cpp/build/support.mk, it has:
```
#if /lib64 exists, then setup x86_64 library path to lib64 (good indication if a linux has /lib and lib64). 
#Else, if it doesnt, then set as /lib. This is used in the make install target 
ifeq ($(wildcard /lib64),)
instlibdir.x86_64 = /lib/
else
instlibdir.x86_64 = /lib64/
endif
instlibdir.default   = /lib/

#our actual install location for the library
ifneq ($(instlibdir.$(MACHINE)),)
instlibdir ?= $(PREFIX)$(instlibdir.$(MACHINE))
else
instlibdir ?= $(PREFIX)$(instlibdir.default)
endif
```
Shouldn't  it be testing $(PREFIX)/lib64 rather that /lib64 ?

**Comment by Fishwaldo** [comment]
The test for /lib64 is not testing for "install" location, its testing if the distribution is 32 bit or 64 bit and it contributes to the install location in the second section above.

As you noted, your distribution does not have /usr/local/lib64 but I assume its a 64 bit distro, hence this test would fail. 

There is no other "simple" way to do this test unless we want to introduce complexities into the build like AutoConf or cmake etc.
