### ISSUE TITLE
Domoticz OpenZWave: Driver Failed!! raspberry pi 3

### ISSUE THREAD

**Issue by onsmam** [OpenZWave/open-zwave#788]
try-ed to upgrade to pi 3 and get the following error:

Error: OpenZWave: Driver Failed!!

try-ed the new stick in pi 2 with razberry, this works, so only difference is the Pi 3, and its hardware...
try-ed to re-install openzwave with no succes. still OpenZWave: Driver Failed!!

**Comment by gizmocuz** [comment]
This has absolutely nothing to do with OZW.
If you had searched the Domoticz forum before, or even the internet, you could have found out that there is an issue with the RPI3, and razberry

**Comment by onsmam** [comment]
if you had checked this issue sooner than you had noticed that the answer was not available the time of writing...

**Comment by gizmocuz** [comment]
When reporting problems with Domoticz, it might be an idea to report this on the Domoticz forum first?

**Comment by onsmam** [comment]
OpenZWave: Driver Failed!! might have something to do witch openzwave..... en at the same time the question was asked... maybe here some one with the same problem.. 

thank you for the kind support....

**Comment by gizmocuz** [comment]
?

**Comment by jdagerot** [comment]
It would have been nice to redirect new readers on where to look for a solution, I've put a fair amount on trying to find anything about this problem but can't find anything when googling, I'm just getting back on this page.

**Comment by gizmocuz** [comment]
Okey, let me put it like this, the next time you have problems with Domoticz/OZW please contact Microsoft first, because it is probably their default USB driver that has issues.
