### ISSUE TITLE
SetValueRaw not represented in DotNet Wrapper

### ISSUE THREAD

**Issue by dechutes** [OpenZWave/open-zwave#790]
Hello,
I'm not sure this is where to ask this, but I have been trying to add the setvalueraw to the dotnet wrapper and can't get it to work.  Could someone point me in the right direction?

Thank you!

**Comment by bufferUnderrun** [comment]
Hi,

I use the dotnet wrapper too and maybe i can help. 
Could you post the code you're trying to add ?

**Comment by dechutes** [comment]
Hi bufferUnderrun,
Thanks so much for the offer.  I'm trying to access the:
bool SetValue( ValueID const& _id, uint8 const* _value, uint8 const _length );
in Manager.h

It allows me to send an array of bytes that are not translated.  

I was working on this here:
https://groups.google.com/forum/#!topic/openzwave/vxpUsHtxZj4

but I couldn't figure out the C# to C++ conversion.

Any help would be greatly appreciated!

**Comment by Fishwaldo** [comment]
@OpenZWave/openzwave-dotnet-uwp  I assume you will do this?

**Comment by dotMorten** [comment]
Yup. Issue already logged. I'd love to implement it, but need to understand how and when to use it first, so I can test it :-)

**Comment by dechutes** [comment]
I can help with that.  The original reason for the request is I have a Quickset door lock and the codes for it require raw values to be sent, it doesn't work with string, int or any other type that is already represented in the the dotnet wrapper.  I am able to view the codes after getting them as string and converting the bytes to values.  The only thing missing right now is how to get the byte values in dotnet to convert to the same in c++.  I have tried reading up on this, but don't understand the whole pointer thing.  It's really just a conversion error right now.  the code already exists in c++ to write it i just can't get a reference to that method to compile.

**Comment by dotMorten** [comment]
Let's move the discussion over to  https://github.com/OpenZWave/openzwave-dotnet-uwp/issues/2
