### ISSUE TITLE
Enerwave zwn-rsm2 device shares device id with existing device, would like to add parameter

### ISSUE THREAD

**Issue by instantchow** [OpenZWave/open-zwave#801]
The Enerwave ZWN-RSM2 Smart Dual Relay Switch Module ([pdf](http://enerwaveautomation.com/wp-content/uploads/products/zwnrsm2/zwn-rsm2_ac_092514.pdf)) carries the same product ID and device ID as the ZW-20R. There does not seem to be any parameter collision between these two devices as the ZW-20R has one parameter at index 1 while the RSM2 has one parameter at index 3.

I have added the ZWN-RSM2 singular config parameter to the existing zw20r.xml config file. Perhaps they can coexist?

https://github.com/instantchow/open-zwave/commit/bee97ad45a2ad432bc1cce58b7127ec97d4a8abb

Since I don't own the 20R Dual outlet device I cannot tell you definitively if this will be a problem. Perhaps @chadparry (original contributor for this device) can help.

also somewhat related #141

**Comment by chadparry** [comment]
I can test a config with the ZW20R if that will help. I agree that there 
isn't any reason they should have a problem coexisting. But it will be 
confusing for users, because inactive config entries will be published. 
I can't think of any solution to avoid that.

**Comment by Fishwaldo** [comment]
Unfortunately having non-existent config values will cause timeouts when OZW starts up, and both config values will be exposed in OZW. Best to bitch to the manufacturer about using duplicate ID's

**Comment by Fishwaldo** [comment]
When #141 is done, we can add this.

**Comment by kentcalero** [comment]
this seems to still be a problem, I'm experiencing it with zw20r (cannot find in zwave alliance db) and zwn-rsm1. How do we handle different devices sharing the same ID?

**Comment by nechry** [comment]
We add a commented entry in database pointing on a specific xml file. You must manually comment and uncomment the two entries. It's a manuel action. There files are only useful at the inclusion, if you dont remove your zwcfg file they dont used anymore. It's a workaround but at the moment it's the only solution we have

**Comment by kentcalero** [comment]
That's what I figured. A solution for the future could be an update to manually set the config file for each node. This will also allow for easy updating after the node is added. This should not be a complicated add as it's just a button that performs the load procedure and the specific file name entered by the user.

Kent L. Calero

Sent from the field through my iPhone.

On Feb 25, 2017, at 11:42 AM, Jean-François Auger <notifications@github.com<mailto:notifications@github.com>> wrote:


We add a commented entry in database pointing on a specific xml file. You must manually comment and uncomment the two entries. It's a manuel action. There files are only useful at the inclusion, if you dont remove your zwcfg file they dont used anymore. It's a workaround but at the moment it's the only solution we have

**Comment by Fishwaldo** [comment]
Closing this. Not much we can do if a manufacturer messes up
