### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by Forbinn** [OpenZWave/open-zwave#807]
Hello,

I found an error in the documentation of the Notification class and more precisely the Notification::Type_ControllerCommand enumeration value. Indeed the documentation said that:
* Notification::GetEvent returns a Driver::ControllerCommand and
* Notification::GetNotification returns a Driver::ControllerState

but in fact and after looking at the code on github directly (https://github.com/OpenZWave/open-zwave/blob/master/cpp/src/Driver.cpp#L5511) I found that:

* Notification::GetEvent returns a Driver::ControllerState and
* Notification::GetNotification returns a Driver::ControllerError

I hope this will help you.

Regards,
Vincent

**Comment by Fishwaldo** [comment]
Could you point out where in the Doco you are seeing this? 

I've just checked, and I can't find the references you make.

**Comment by Forbinn** [comment]
I found the mistake right here: http://www.openzwave.com/dev/classOpenZWave_1_1Notification.html#a5fa14ba721a25a4c84e0fbbedd767d54aadeff93abdefc102a9798f62eb0f3461

**Comment by Fishwaldo** [comment]
Fixed. Thanks
