### ISSUE TITLE
Please add support for zwave device: Manufacturer id="0115" name="Z-Wave.Me" Product type="1000" id="0300" name="ZME_RC2"

### ISSUE THREAD

**Issue by Ramon00** [OpenZWave/open-zwave#839]
Please add support for the zwave device attached in the zip file.
 Manufacturer id="0115" name="Z-Wave.Me" Product type="1000" id="0300" name="ZME_RC2"
[zme_RC2.zip](https://github.com/OpenZWave/open-zwave/files/211285/zme_RC2.zip)

Thank you

**Comment by nechry** [comment]
This device is include already.

**Comment by Ramon00** [comment]
ah yes you are right. It wasnt last time i looked... meh. You can close this issue.
