### ISSUE TITLE
RaZBerry card 0x0400/0x0002 not recognised

### ISSUE THREAD

**Issue by travellingkiwi** [OpenZWave/open-zwave#868]
Newer version of RaZBerry zwave+ perhaps?

**Comment by openzwave-dev-watcher** [comment]
Was this on a PI 3?  Had to turn off the Bluetooth to make one work.

**Comment by travellingkiwi** [comment]
Nope. Pi-2. It works OK. But just does't get recognised correctly until you edit the manufacturer codes file.

**Comment by travellingkiwi** [comment]
Added a pull request to add this device #869

**Comment by nechry** [comment]
close by https://github.com/OpenZWave/open-zwave/pull/869
