### ISSUE TITLE
Devices Unknown

### ISSUE THREAD

**Issue by echo7alpha** [OpenZWave/open-zwave#887]
Hello, 

Recently I was able to get help in Domoticz forum to get my devices recognized. They were all U.S. versions: Aeotec Siren Gen5, Fibaro Motion Sensor  V3.2, Zipato RFID. Would it be possible to add these three lines into the file so it won't affect the next update?

https://www.domoticz.com/forum/viewtopic.php?f=6&t=11965

**Comment by nechry** [comment]
we normally merge jeedom devices config. I added there definitions:
https://github.com/jeedom/plugin-openzwave/commit/66f148ff6ac843cb57127a5cb65916c688be721e

**Comment by Fishwaldo** [comment]
@nechry when is the Jeedom Merge happening?

**Comment by nechry** [comment]
@sarakha63 will normally send the PRs really soon.

**Comment by Fishwaldo** [comment]
@nechry can we close this?

**Comment by nechry** [comment]
https://github.com/OpenZWave/open-zwave/commit/d22da1fa4437e19f4884b41d11e31f14e1a6104d
