### ISSUE TITLE
Error, Cannot find a path to the configuration files at ./config/. Exiting...

### ISSUE THREAD

**Issue by rbaindourov** [OpenZWave/open-zwave#906]
So sorry, about being noisy in regards to this issue.

I realize that I have double posted at ozwcp project.

But I am currently experiencing a problem which I have tracked down to open-zwave:

```
pi@raspberrypi:~/zwave-cp $ sudo ./ozwcp 
2016-06-07 20:19:18.765 Error, Cannot find a path to the configuration files at ./config/. Exiting...
2016-06-07 20:19:18.766 Error, Exception: Options.cpp:91 - 1 - Cannot Find Configuration Files
Error: Options.cpp:91 - Cannot Find Configuration Files
```

Can someone help me in resolving this problem, please?

**Comment by Fishwaldo** [comment]
copy the config folder from the openzwave library into the ozw-control-panel directory where you run ozwcp from. 

For any other questions, please use our mailing list:
https://groups.google.com/forum/#!forum/openzwave
