### ISSUE TITLE
How to add a node on ZWave network

### ISSUE THREAD

**Issue by jingbosu** [OpenZWave/open-zwave#917]
Hello guys, I want to add a node on ZWave network just with the openzwave library without using any interface (like Domoticz or OZW-Control-Panel), could someone tell my if it's possible to do that and which documents (or which classes) I can use to achieve this functionality?

It seems that what I need to do is to active the mode "Inclusion node" of my controller (maybe not correct), so can I active this function permanently? 

Thanks in advance for your help,

Best wishes,

Jingbo

**Comment by Fishwaldo** [comment]
Hi,
This is a issue tracker and not a support forum. 

Please use our Forums for Questions regarding OpenZWave: 
https://groups.google.com/forum/#!forum/openzwave

Thanks
