### ISSUE TITLE
Memory Leak in SwitchMultilevel

### ISSUE THREAD

**Issue by jmattioni** [OpenZWave/open-zwave#924]
After using the PressButton function in a test environment a memory leak occurred on exit for Value "Ignore Start Level". This was traced to a code segment in SwitchMultilevel failing to release the Value after Getting it. The segment of affected code and the proposed fix are as follows:

if( ValueBool* ignoreStartLevel = static_cast<ValueBool*>( GetValue( _instance, SwitchMultilevelIndex_IgnoreStartLevel ) ) )
	{
		if( ignoreStartLevel->GetValue() )
		{
//			ignoreStartLevel->Release(); // (Release was here in original code)
			// Set the ignore start level flag
			direction |= 0x20;
		}
		//// (JDM) - must always release!
		ignoreStartLevel->Release(); // Release needs to be here
	}

**Comment by Fishwaldo** [comment]
Good Catch. Thanks
