### ISSUE TITLE
DSB29 stops responding after time in Domoticz

### ISSUE THREAD

**Issue by ben423423n32j14e** [OpenZWave/open-zwave#926]
The solution was to change: CommandClass id="32" setasreport="true"

to: CommandClass id="32" setasreport="false"

https://github.com/OpenZWave/open-zwave/blob/master/config/aeotec/dsb29.xml

The devices then had to be excluded and re-included in the network.

I have 3 of these sensors in my home and the issue was present and resolved on all 3.

Please consider updating the master.

Cheers

**Comment by ben423423n32j14e** [comment]
Submitted pull request with the changed file.

**Comment by nechry** [comment]
I have this device from more of 4 year with this config and iÎ never got any issues
