### ISSUE TITLE
Include install_name in LDFLAGS on OS X 

### ISSUE THREAD

**Issue by irundaia** [OpenZWave/open-zwave#947]
I've been trying to update [the homebrew formula](https://github.com/homebrew/homebrew-core/pull/3268) for openzwave for some time now. Unfortunately, after I've compiled openzwave in homebrew, the install_name of the dylib seems to be incorrect.

This can be fixed with the following replacement:

```
inreplace "cpp/build/Makefile",
      "LDFLAGS += -dynamiclib",
      "LDFLAGS += -dynamiclib -install_name #{lib}/$(SHARED_LIB_NAME)"
```

But I think it would be better if this were to be included in the original Makefile. Could you guys please include the install_name in the original Makefile?

**Comment by Fishwaldo** [comment]
Done. Although in future, please double check your code. The examples you provided was completely wrong - #{lib} basically commented out the rest of the line, and regardless, ${lib} isn't defined at all, so it ended up as /libopenzwave-1.4.dylib which would break things even further.
