### ISSUE TITLE
Qubino ZMNHBDx firmware S5

### ISSUE THREAD

**Issue by jotakar** [OpenZWave/open-zwave#949]
I've read that Qubino has updated firmware of Flush 2 Relays. The new version is S5, and I've read that it doesn't send reports about switch status, as S4 did. 
Which is the new in this firmware version? I can't find anything, or anybody who use this version, in order to know the reason of this version. 
Thanks

**Comment by Fishwaldo** [comment]
Hi,
This is a issue tracker and not a support forum. 

Please use our Forums for Questions regarding OpenZWave: 
https://groups.google.com/forum/#!forum/openzwave

Thanks

**Comment by jotakar** [comment]
You're right. Sorry.
