### ISSUE TITLE
Duco CO2 sensor

### ISSUE THREAD

**Issue by ronvangestel** [OpenZWave/open-zwave#952]
i'm trying to add my CO2 sensor from Duco. but i can't get it to work. could someone please send me in the right direction.
i made the xml file. i only get a ligth dimmer instead of a c02 reading and a temp that never changes.

[http://www.pepper-one.de/zwavedb/device/139](url)

xml file:
[ronvangestel.asuscomm.com/CO2.xml](url)

**Comment by Fishwaldo** [comment]
Could you please send a OZW_Log.txt file of this device?

Please shutdown your app, remove zwcfg_*.xml and restart the app, and let it run for a while.

**Comment by Fishwaldo** [comment]
No Feedback. Closing.
