### ISSUE TITLE
sigma design uzb eu not detected

### ISSUE THREAD

**Issue by tbelqdx** [OpenZWave/open-zwave#953]
Hi,
I am trying to use an uzb eu dongle from sigma design as a Zwave controller for my windows 10 Iot.
I'm using this sample and iot explorer to try detecting the dongle:[Here]( https://github.com/ms-iot/samples/tree/develop/AllJoyn/Samples/ZWaveAdapter)

Unfortunately , the dongle is not detected. Maybe because there is no config file for this configuration? I couldn't find any for sigma design.
Do somebody had the same problem?
Thank you

**Comment by Fishwaldo** [comment]
Not being too farmilar with the MS IOT framework, but you might have to install the Serial Driver for the dongle into Windows first. Once thats done, the device should appear as a COM port. 

This isn't a OZW issue though. Any further questions, please use our mailing list:

https://groups.google.com/forum/#!forum/openzwave

Thanks
