### ISSUE TITLE
please add water flow meter

### ISSUE THREAD

**Issue by michapr** [OpenZWave/open-zwave#955]
Can you please add type for water flow meter?
(Sensor Multilevel V8)

Sample device description here:
http://products.z-wavealliance.org/products/1690
http://products.z-wavealliance.org/products/1690/configs
manual: http://products.z-wavealliance.org/ProductManual/File?folder=&filename=Manuals/1690/User%20Manual%20FMI%20-%2029Feb2016.pdf

Thanks!

**Comment by nechry** [comment]
Please provide required files
see: https://github.com/OpenZWave/open-zwave/wiki/Adding-Devices
and propose a Pull request instead.
