### ISSUE TITLE
missing support for linking with uclibc++

### ISSUE THREAD

**Issue by nihilus** [OpenZWave/open-zwave#964]
GetColor() method should be rewritten to support linkage with uclibc++ forembedded devices. I will attach my patch tomorrow which use strtoul(). I've tested my patch against an Aeotec lightbulb.

**Comment by Fishwaldo** [comment]
why? Whats wrong with the current implementation?

**Comment by nihilus** [comment]
@Fishwaldo it is uclibc++ that doesn't handle sstreams.

**Comment by nihilus** [comment]
``
Index: cpp/src/command_classes/Color.cpp
===================================================================
--- cpp/src/command_classes/Color.cpp	(revision 16819)
+++ cpp/src/command_classes/Color.cpp	(working copy)
@@ -309,7 +309,13 @@
 	string result = rgbstring.substr(((position - 1) * 2) +1, 2);
 	std::stringstream ss(result);
 	uint16 rawresult;
+
+	/* Markus - Breaks uClibc++ so use strtoul */
+#if 1
+	rawresult = static_cast<uint16>(strtoul(result.c_str(), NULL, 16));
+#else
 	ss >> std::hex >> rawresult;
+#endif
 	return rawresult;
 }
 
``

**Comment by Fishwaldo** [comment]
I think there is going to be more "broken" cases here.... (on Dev branch as well)

might have to make our own "strtoul" type function in Utils.cpp/h and use that when we need to convert etc. 

what about the reverse, would this be broken as well:
`string OpenZWave::intToString( int x ) {
        return static_cast< std::ostringstream & >( ( std::ostringstream() << std::dec << x ) ).str();
}
`

**Comment by nihilus** [comment]
Actually that does compile. Seems to be related to stringstreams.

**Comment by nihilus** [comment]
This seems to have been fixed in uClibc++ 0.2.4.

**Comment by Fishwaldo** [comment]
so is the fix required?

**Comment by nihilus** [comment]
No

**Comment by Fishwaldo** [comment]
thanks
