### ISSUE TITLE
Multilevel Power Switch marked dead

### ISSUE THREAD

**Issue by psavva** [OpenZWave/open-zwave#975]
Dear Devs, 

I'm using the OZW library in the Domoticz automation system.
I have "Multilevel Power Switch" from Merten, which is basically a dimmable wall insert, it runs off mains power.

If for any reason, the node is marked as dead (probably interference), it's not possible to get the node back to an alive state, without removing, and re-adding the node completely. 
It may be marked dead again after a few minutes, and becomes unusable.

Please can you tell me what logs you need, and how to enable them. 
I am happy to provide all the information you need to help the project.

I see that many people face the same sort of issue on the Mains powered modules  when researching the internet if there are any solutions.

One interesting thing I find in the logs is "Dropping command because node is presumed dead", which would indicate that the node is communicating, but communications are ignored due to it's "dead" status?

**Comment by nechry** [comment]
Try to use TestNetworkNode to do a ping to the presumed dead node, or you can also try to use the cmd SendNodeInformation. I use there two helper to Relive most Dead node in jeedom. 
Also, ensure your network coverage is good around this node.

This isn't a OZW issue though. Any further questions, please use our mailing list:

https://groups.google.com/forum/#!forum/openzwave
