### ISSUE TITLE
Device support for Heatit thermostat updated

### ISSUE THREAD

**Issue by gijs69** [OpenZWave/open-zwave#996]
I made a number of changes to get the Heatit Thermostat to wrok properly. 

hope it helps others in getting it to work

**Comment by nechry** [comment]
Can you share it?

**Comment by gijs69** [comment]
It seam I cannot upload it to the bug tracker.

Maybe you know how to do that. 

Anyway, here it is.

**Comment by nechry** [comment]
If you update the xml file you need to create a PR and I will validate and merge.

if you paste xml content her we will not see, use the Markdown for code

**Comment by gijs69** [comment]
[https://www.dropbox.com/s/f8yvrju4rt5mx8l/heatit021.xml?dl=0](url)

is the link to the file. I never created a PR before :) Maybe it is faster if you pickup this file.

**Comment by nechry** [comment]
ok for this time but please in future provide a PR. 
You test every mode? Any complains for this thermostat?

**Comment by gijs69** [comment]
As far as I can see everything works just fine right now.

**Comment by nechry** [comment]
please also always do a
make xmltest
before submit a config file
see my little change:
https://github.com/OpenZWave/open-zwave/commit/691d1f17438e716b155c659bc6fe4ad6bcac5d10
